### ISSUE TITLE
Add support for Python 3.10

### ISSUE THREAD

**Issue by sliverc** [django-json-api/django-rest-framework-json-api#1001]
## Description of the Bug Report

Python 3.10 has been [released](https://www.python.org/downloads/release/python-3100/) and we should add support to DJA. See #846 as reference for implementation.

## Checklist

- [x] Certain that this is a bug (if unsure or you have a question use [discussions](https://github.com/django-json-api/django-rest-framework-json-api/discussions) instead)
- [x] Code snippet or unit test added to reproduce bug

**Comment by auvipy** [comment]
I want to handle this one
