### ISSUE TITLE
Confusing validation error when submitting JSON in Django REST API format

### ISSUE THREAD

**Issue by ncoghlan** [django-json-api/django-rest-framework-json-api#107]
Thanks for creating this project! I really like both Django REST Framework and the design of jsonapi.org, so being able to use them together is excellent.

However, with the current 2.0.0a2 release, I found an interesting problem with the interaction between DRFJA's validation errors, and DRF's presentation of those errors through the browsable API: https://github.com/tomchristie/django-rest-framework/issues/3446

What appears to be happening is that when a create request is submitted using DRF's default format (i.e. an attribute mapping at the top level of the JSON request), DRFJA is raising ValidationError with the details attribute set to a list, which DRF then attempts to treat as a mapping.

Assuming I've identified the origins of the error correctly, If the exception details stored a mapping instead, that could both report the field name that was expected, as well as avoid the secondary failure in DRF's error handling.

**Comment by ncoghlan** [comment]
Just noting that I'm *not* entirely sure of my description of *how* the error happens. As I noted on the DRF issue, I'm learning the details of how POST requests are handled as part of trying to figure out the origins of this issue, so there are gaps in my understanding of the normal sequence of events.

**Comment by jsenecal** [comment]
Could you test against the develop branch? Many fixes have been pushed since the pypi release...

**Comment by jerel** [comment]
I also just tagged alpha-3 so you can update to that tag if you like. To install the develop branch you can install with pip like so `-e git+https://github.com/django-json-api/django-rest-framework-json-api.git@develop#egg=django-json-api`

**Comment by hankthetank** [comment]
According to the jsonapi.org shouldn't the response code be 422 when validation error occurs? Is there and easy way to configure that today or do I need to write a custom exception handler? Thanks for your effort on this!

**Comment by jsenecal** [comment]
@ncoghlan did that fix your issue ? We'll close this in the meantime - we'll reopen if needed !

**Comment by ncoghlan** [comment]
Sorry for the delayed response - I also needed to change the container build process to have git available (at least for the time being) and only got around to doing that today. Switching to the develop branch does indeed populate the "raw data" form correctly in the browsable API and also reports a suitable error when receiving a document in classic DRF format:

    {
        "errors": {
            "detail": "Received document does not contain primary data"
        }
    }
