### ISSUE TITLE
Incorrect type. Expected pk value, received OrderedDict when updating a relationship

### ISSUE THREAD

**Issue by schtibe** [django-json-api/django-rest-framework-json-api#111]
I get this error:

    {'errors': [{'detail': 'Incorrect type. Expected pk value, received '
                       'OrderedDict.',
             'source': {'pointer': '/data/attributes/title'},
             'status': '400'}]}

since commit d654c757e9c034961261b642987c86a8affc2392 when I run my unit test. The data I send is 

        data = {
            "data": {
                "type": "customers",
                "id":   self.lukeId,
                "relationships": {
                    "title": {
                        "data": { "type": "titles", "id": "2" }
                    }
                }
            }
        }

What is that change for / is my data wrong?

**Comment by jsenecal** [comment]
I would say that this commit title says it all: 'Relationships parsing are now only handled by compatible fields'

In more details: another field was introduced shortly around the time of that commit in: https://github.com/django-json-api/django-rest-framework-json-api/commit/23d0af686ca9ad69ac8c63f45a7a08bf9656a459

This fields handles the JSONAPI spec completely and should replace any related fields you might want to use - Both for performance and features.

Let me know if you need more help on this.

**Comment by schtibe** [comment]
Just noticed that I didn't mention that I send this data via PATCH.
I struggle to understand what 'compatible fields' means.

**Comment by jsenecal** [comment]
It means that the parser now only parses `resource identifier objects` ([spec](http://jsonapi.org/format/#document-resource-identifier-objects)) in relationships. - for that, you need fields that understand `resource identifier objects` like the above ResourceRelatedField.

**Comment by jerel** [comment]
Is that error only shown for this one issue? If so perhaps we could improve the error with something like "`title` cannot be parsed. Are you sure it extends `ResourceRelatedField` and the payload complies with the jsonapi.org spec?"

**Comment by jsenecal** [comment]
@jerel we would require to override ALL DRF related fields in that case as we cant get the serializers fields from the parser

**Comment by jsenecal** [comment]
@schtibe can you try to use the ResourceRelatedField and give us an update on this issue ?

**Comment by schtibe** [comment]
@jsenecal yes it seems to work, thank you!

**Comment by schtibe** [comment]
Although using ResourceRelatedField makes it mandatory, even though I added allow_null=True

**Comment by jerel** [comment]
Does your model also have the relationship field set to `null=True, blank=True`?

**Comment by jsenecal** [comment]
Also, the setting is usually required=false on the relations field... See http://www.django-rest-framework.org/api-guide/serializers/#validation there is a note about this...

**Comment by schtibe** [comment]
It was required=false. Thanks @jsenecal
