### ISSUE TITLE
RelationshipView in serializer

### ISSUE THREAD

**Issue by andorov** [django-json-api/django-rest-framework-json-api#112]
I have set up a RelationshipView view with a working url.  How do I specify in a serializer to use that url for the relationship?

    comments = serializers.HyperlinkedIdentityField(view_name='post-relationships',lookup_field='comments')

throws 

    Could not resolve URL for hyperlinked relationship using view name "post-relationships". You may have failed to include the related model in your API, or incorrectly configured the `lookup_field` attribute on this field.`

I'd be happy to update the documentation.

**Comment by jsenecal** [comment]
I built ResourceRelatedField field for that - Here's how I use it:
```python
departments = ResourceRelatedField(
        related_link_view_name='organization-departments-list',
        related_link_url_kwarg='organization_pk',
        self_link_view_name='organization-relationships',
        read_only=True,
        many=True,
        required=False
    )
```

**Comment by andorov** [comment]
How would it be with multiple word models (ie `MasterPost` has many `BabyPost`).  I've tried hyphen and pluralization variants on the below -

    departments = ResourceRelatedField(
        related_link_view_name='masterpost-babyposts-list',
        related_link_url_kwarg='master_post_pk',
        self_link_view_name='masterpost-relationships',
        read_only=True,
        many=True,
        required=False
    )

**Comment by jsenecal** [comment]
what is your urlconf ?

**Comment by andorov** [comment]
url(r'^api/master_posts/(?P<pk>[^/.]+)/relationships/(?P<related_field>\w+)',
        views.MasterPostRelationshipView.as_view(),
        name='masterpost-relationships'),

**Comment by jsenecal** [comment]
Sorry - I missed that answer, did you eventually figure it out ?

**Comment by jsenecal** [comment]
Closing this, let us know :)
