### ISSUE TITLE
How to filter relationship?

### ISSUE THREAD

**Issue by lsowen** [django-json-api/django-rest-framework-json-api#115]
If I am getting the details of an object (e.g. ```Build```), which has a one-to-many relationship with another object (e.g. ```BuildArtifact```), how do I limit what related objects are listed in the ```relationships``` key?  

For example, I if ```BuildArtifact.type``` can be both ```PUBLIC``` and ```PRIVATE```, and if I want to show certain users only the ```PUBLIC``` relationships.  To do this, I have to access the ```request.user```, and adjust the relationship ```queryset```.  

Attempting to do this in the ```ModelSerializer.get_fields()``` method seems like it should work, but doesn't because the ```extract_relationships()``` method used to build the response JSON object goes directly the model instance and queries the relationship directly.  (See [this section](https://github.com/django-json-api/django-rest-framework-json-api/blob/cf8a930268c152d14b9ac9f4c337fdbf61ee1e0e/rest_framework_json_api/utils.py#L263-L274) of ```extract_relationships()``` for the relevant code).

**Comment by jsenecal** [comment]
Filtering is not something meant to be done by this library. Unless I don't understand your end goal, what you are requesting should be done through the filtering abilities of DRF itself... See the relevant information [here](http://www.django-rest-framework.org/api-guide/filtering/).

**Comment by jsenecal** [comment]
I will close this issue for now, we'll reopen if needed

**Comment by lsowen** [comment]
@jsenecal I don't think I did a good job explaining.

Pretend that the user issues a request to ``/api/builds/27`` and gets the following response:

```json

{
    "data": {
        "type": "Build",
        "id": "22",
        "attributes": {
            "created_at": "2015-10-03T04:13:51.318430Z",
            "updated_at": "2015-10-03T04:14:17.959069Z"
        },
        "relationships": {
            "artifacts": {
                "meta": {
                    "count": 3
                },
                "data": [
                    {
                        "type": "BuildArtifact",
                        "id": "3"
                    },
                    {
                        "type": "BuildArtifact",
                        "id": "2"
                    },
                    {
                        "type": "BuildArtifact",
                        "id": "1"
                    }
                ]
            }
        }
    }
}
```

However, the user only has view permission on ```BuildArtifact``` Ids1 and 2 (ie no ability to view id 3).  So, I need to be able to filter out id 3 when the relationship is built.  This doesn't seem to be currently possible because when the relationship is building it calls ```.all()``` on the model field instead of the serializer field (which would be able to have a custom queryset based on the current request user).

Thoughts?

**Comment by jsenecal** [comment]
The behavior you are expecting can be accomplished by overriding the get_queryset method on the viewset as explained [here](http://www.django-rest-framework.org/api-guide/filtering/#overriding-the-initial-queryset). This is how I personally do it. 

I understand that you might have a scenario where the queryset is different per field. In that case the queryset should be defined on the field itself. Basically extract relationships makes the .all() call to convert a relatedmanager into a queryset. The manager should already have filtered the results. Basically if you remove the json:api renderer, are the choices available in the browsable api form?

**Comment by lsowen** [comment]
@jsenecal That filters the ```list``` method for the "target" model (e.g. if I access the list of ```BuildArtifact```s at ```/api/build_artifacts```), correct?  (Which I am currently doing to filter which items the user can see)

However, I want to filter which items are shown to the user in the ```relationships``` key of a response.

**Comment by leifurhauks** [comment]
@lsowen, if I understand correctly, you need to filter the queryset on a to-many related field, such as `artifacts` in your example above, based on the user who sent the request. You could try setting the queryset on that field in the __init__ of the serializer, something like the following:

```python
class BuildSerializer(serializers.ModelSerializer):
    def __init__(self, *args, **kwargs):
        super(BuildSerializer, self).__init__(*args, **kwargs)
        user = self.context['request'].user
        self.fields['artifacts'].queryset = BuildArtifact.objects.filter('put query logic here that tests against user')
```

There's more about modifying serializer fields during initialization [here](http://www.django-rest-framework.org/api-guide/serializers/#dynamically-modifying-fields) . Also I assumed that the request object is in your serializer's context; if you're using a viewset this should happen automatically thanks to the `get_serializer` method on viewsets.

**Comment by jsenecal** [comment]
@leifurhauks - you beat me to it - thanks :+1:

**Comment by lsowen** [comment]
@jsenecal @leifurhauks That is similar to what I was thinking.  I have tried:
1. Overriding the queryset by specifying a field on the serializer
2. Overriding the querset in ```__init__```
3. Overriding the queryset in ```get_fields()```
4. Overriding the field in ```get_fields()```.  

Unfortunately none of those methods seem to work, I think because ```rest_framework_json_api.utils.extract_relationships()``` uses the model field instead of the serializer field to get the "result set".  See [here](https://github.com/django-json-api/django-rest-framework-json-api/blob/cf8a930268c152d14b9ac9f4c337fdbf61ee1e0e/rest_framework_json_api/utils.py#L263) and [here](https://github.com/django-json-api/django-rest-framework-json-api/blob/cf8a930268c152d14b9ac9f4c337fdbf61ee1e0e/rest_framework_json_api/utils.py#L346-L359).

To be honest, I'm not even sure how filtering could be implemented in a general case, but I was hoping you might have some ideas on how to kludge in a filtering mechanism.

**Comment by lsowen** [comment]
@jsenecal @leifurhauks As you both already knew, the shortcoming was not on the part of this library.  Instead, it doesn't look like there is a built in way to filter relationships in django-rest.

However, I was able to accomplish what I needed by extending a couple of built in classes.  I've put together a small demo which will hopefully help anyone who needs to do similar in the future:  https://gist.github.com/lsowen/99dedd98227f518336a2#file-serializers-py

Definitely let me know if either of you know of a better way, or a way to make this more general.

I appreciate both of your help, and this lib is awesome.  Thanks!

**Comment by jsenecal** [comment]
@lsowen thanks for your feedback :)
