### ISSUE TITLE
ResourceRelatedField is too rigid for type validation

### ISSUE THREAD

**Issue by jsenecal** [django-json-api/django-rest-framework-json-api#124]
Opening this on behalf of @martinmaillard (https://github.com/django-json-api/django-rest-framework-json-api/issues/122#issuecomment-146879198)

`ResourceRelatedField` is way too rigid when it checks the valid type. It gets the expected type from the queryset, which means that:
- it's not possible to customize the type of a relation (what is allowed by the resource_name on the serializer)
- it's not possible to allow multiple types to be valid for one relation (useful with polymorphic relationships)

**Comment by jerel** [comment]
Related to this we can now specify the type manually by passing `model=FooModel` to the ResourceRelatedField. https://github.com/django-json-api/django-rest-framework-json-api/blob/develop/example/serializers.py#L29-L30

This does not solve the multiple types feature request.

**Comment by sliverc** [comment]
With #306 and introduction of polymorphic models support I think this issue has been addressed.

Therefore closing. If you see an area of this issue which has not been addresses please comment.
