### ISSUE TITLE
Including data fails on a List endpoint

### ISSUE THREAD

**Issue by jerel** [django-json-api/django-rest-framework-json-api#130]
/api/widgets?include=parent_widget
```
rest_framework_json_api/utils.py", line 419, in extract_included
    relation_instance_or_manager = getattr(resource_instance, field_name)
AttributeError: 'NoneType' object has no attribute 'parent_widget'
```

**Comment by rollokb** [comment]
Obviously an Http 500 error code is not the correct response. Personally I'm unsure what should be returned. Does JSON-API allow for includes on resource collections?

**Comment by jsenecal** [comment]
@rollokb I think @jerel is making ourselves a note here - :smile: 

While I personally don't have similar issues with the code I wrote (beside some issues that were encountered namely in #127 and #126)

Otherwise, @jerel for the sake of clarity - it is true that adding your models and serializers could help here :)

**Comment by jerel** [comment]
Yeah, I'm recording the issue for anyone that wants to fix or that hits the same error. I doubt I'll work on it before Thursday. http://jsonapi.org does not explicitly say if inclusion should work on a collection endpoint but the very last example here shows it: http://jsonapi.org/format/#fetching-includes

``` python
from rest_framework_json_api import serializers

class WidgetSerializer(serializers.ModelSerializer):

    included_serializers = {
        'parent_widget': ParentWidgetSerializer,
    }

    class Meta:
        model = Widget
        fields = ('id', 'parent_widget',)
```
where the `Widget` model has a foreign key pointing at `ParentWidget`. Detail views work fine, this is just a List issue.
