### ISSUE TITLE
Including data fails on lists

### ISSUE THREAD

**Issue by schtibe** [django-json-api/django-rest-framework-json-api#131]
If the inclusion parameter is used in retrieving a list of models, every relation is only considered once (utils.py line 417 removes the relation once)

```python
        try:
            included_resources.remove(field_name)
            new_included_resources = [key.replace('%s.' % field_name, '', 1) for key in included_resources]
            relation_instance_or_manager = getattr(resource_instance, field_name)
            serializer_data = resource.get(field_name)
        except ValueError:
            # Skip fields not in requested included resources
            continue
```

Example:

Assuming table `Person`:

pk | fruit (fk to `Fruit`) | Person
----|-------------------------------| ------------
1 | 1 | John
2 | 1 | Jack
3 | 2 | Jill

and table `Fruit`:

pk | name
-----|---------
1 | apple
2 | banana

Now let's do `GET /api/v1/person?include=fruit` which is programmed to return all persons

Gives roughly following result (I wrote this from memory ):

```json
	{
		"data": [{
				"type": "persons",
				"id": 1,
				"attributes": { "name": "John" },
				"relationships": {
					"fruit": {
						"data": { "type": "fruit", "id": "1" }
					}
				}
			},
			{
				"type": "persons",
				"id": 2,
				"attributes": { "name": "Jack" },
				"relationships": {
					"fruit": {
						"data": { "type": "fruit", "id": "1" }
					}
				}
			},
			{
				"type": "persons",
				"id": 3,
				"attributes": { "name": "Jill" },
				"relationships": {
					"fruit": {
						"data": { "type": "fruit", "id": "2" }
					}
				}
			}
		# so far so good, now here it gets interesting
		],
		"included": [{
			"type": "fruit",
			"id": 1,
			"attributes": {
				"name": "apple"
			}
		}]
		# banana is missing, even though the person 3 references it
	},
```

**Comment by schtibe** [comment]
I think the problem is that the renderer passes the `included_resources` by reference (lines 110 and 119 in renderers.py). Another way to fix this for my test case would be to pass by value:

```python
included = utils.extract_included(fields, resource, resource_instance, list(included_resources))```

**Comment by jerel** [comment]
Could you install the latest from the develop branch and test it? The symptoms you describe sound suspiciously similar to a bug I fixed yesterday in the same area of the code.

**Comment by jerel** [comment]
@schtibe would it be possible for you to write a failing test for your use case? Here is the file it should go in and you can copy the existing `multiple_entries` test: https://github.com/django-json-api/django-rest-framework-json-api/blob/develop/example/tests/integration/test_includes.py

I wrote a test and a fix for the `include` bug I was seeing and I didn't run across the issue you're reporting. If we can get a test around it we can fix it.

**Comment by schtibe** [comment]
@jerel sure, check out https://github.com/adfinis-sygroup/django-rest-framework-json-api/blob/included_test/example/tests/integration/test_includes.py

**Comment by jerel** [comment]
@schtibe thank you!

**Comment by jsenecal** [comment]
@schtibe here is the test I wrote for that particular issue: https://github.com/django-json-api/django-rest-framework-json-api/blob/feature/compound_documents/example/tests/integration/test_includes.py#L15

I'm working on a fix - hang in there :)

**Comment by topaxi** [comment]
Works for me now, thanks :+1:
