### ISSUE TITLE
support for complex members?

### ISSUE THREAD

**Issue by jamesturk** [django-json-api/django-rest-framework-json-api#139]
I have a use case where I don't need/want an endpoint for every model, this seems to be in line w/ the spec which says "Complex data structures involving JSON objects and arrays are allowed as attribute values."

As an example w/ a model that has 1..N 'Source' objects.

```
class Source(models.Model):
    obj = models.ForeignKey(ParentObj, related_name='sources')
    url = models.URLField()
```

Would it be possible to have the serialization of 'ParentObj' to include ```'sources': [{'url': '...'}, {'url': '...}]```

(If not I'd be open to taking a swing at it & implementation suggestions would be welcome)

**Comment by jsenecal** [comment]
have you tried using [ListFields](http://www.django-rest-framework.org/api-guide/fields/#listfield) for that ?

**Comment by jamesturk** [comment]
ah yeah, good point that seems like it'll work fine.  in case anyone finds this issue looking for something that'll work this seems to work well for me:

```
class InlineListField(serializers.ListField):
    def __init__(self, *args, **kwargs):
        self.include = kwargs.pop('include', [])
        self.exclude = kwargs.pop('exclude', [])
        super().__init__(*args, **kwargs)

    def _get_fields(self, obj):
        if self.include:
            included_fields = self.include
        else:
            included_fields = [k for k in obj.__dict__.keys()
                               if not k.startswith('_') and k not in self.exclude]
        return {f: getattr(obj, f) for f in included_fields}

    def to_representation(self, obj):
        return [self._get_fields(i) for i in obj]
```

used like

```
    contact_details = InlineListField(source='contact_details.all', exclude=['id', 'person_id'])
```
