### ISSUE TITLE
get_serializer_class() should be used to get the serializer_class of views

### ISSUE THREAD

**Issue by mkohram** [django-json-api/django-rest-framework-json-api#143]
To get the `serializer_class` attribute of views the `get_serializer_class()` should be used. DRF allows you to override this function and using the attribute directly as in [here](https://github.com/django-json-api/django-rest-framework-json-api/blob/d22cc0aa4b338b5c034cb6eefad9162ea81241dd/rest_framework_json_api/utils.py#L59) is a bug.

**Comment by jsenecal** [comment]
Thanks for reporting this. We'll look into this.
