### ISSUE TITLE
No straightforward way for bound methods to return relations.

### ISSUE THREAD

**Issue by rollokb** [django-json-api/django-rest-framework-json-api#148]
Sometimes I need to get a relationship based from a function on a model like this.

    class Post(models.Model):
        # attributes and stuff
       
       def user_recommendation(self, user)
           return self.recommends.get(user=user)

 In vanila DRF it is possible to use methods like `user_recommendation` by overriding `RelatedField` or using a`SerializerMethodField`.  However neither of those methods work with DRF-JSON-API. Using a `SerializerMethodField` results in the relation being placed in attributes, not relations.

While subclassing `RelatedField` fails because at this point in the [renderer](https://github.com/django-json-api/django-rest-framework-json-api/blob/develop/rest_framework_json_api/utils.py#L325) attempts to get an id from`relation_instance_or_manager`, but will fail because it's a bound method.

-----

To get the relationship of user_recommendation I have to resort to a dirty hack. Where I subclass `HyperlinkedRelatedField` or `PKRelatedField`, and override `get_attribute` like this.

    class RecommendationField(serializers.HyperlinkedRelatedField):
        def get_attribute(self, instance): 
            request = self.context['request']
            recommendation = instance.user_recommendation(request.user)
            instance.user_recommendation.__dict__['pk'] = recommendation.pk
            return recommendation

Problematically, this breaks `extract_included`.

-----

Would something along the lines of a `RelatedSerializerMethodField`, be the right solution to this?

**Comment by rollokb** [comment]
Sorry to waste time, I found a much better fix.

**Comment by leifurhauks** [comment]
Could you write a brief description of the solution you found for the next
person who has the same question?
Le 2015-10-28 21:38, "Rollo Konig-Brock" <notifications@github.com> a
écrit :

**Comment by rollokb** [comment]
Sure.

    class RecommendationField(serializers.HyperlinkedRelatedField):
        def get_attribute(self, instance):
            request = self.context['request']

            if getattr(instance, '_user_recomendation', None) is None:
                instance._user_recomendation = instance.user_recomendation
                instance.user_recomendation = instance._user_recomendation(request.user)

            return instance.user_recomendation

I can cache then swap the value.

**Comment by jerel** [comment]
To use a function on the model you can use the `source` field on a `ResourceRelatedField` like this: https://github.com/django-json-api/django-rest-framework-json-api/blob/develop/example/serializers.py#L27-L28

If you need the context you can instead specify the source on the serializer: https://github.com/django-json-api/django-rest-framework-json-api/blob/develop/example/serializers.py#L29-L30

Offering those in case one of them helps you. I'll try to document them better tomorrow

**Comment by rollokb** [comment]
I can't pass in parameters with ResourceRelatedField though. Overriding get_attribute works for me, it's a bit of a weird usage anyway.
