### ISSUE TITLE
Including relations of relations requires include to be listed twice.

### ISSUE THREAD

**Issue by rollokb** [django-json-api/django-rest-framework-json-api#149]
http://jsonapi.org/format/#fetching-includes

> In order to request resources related to other resources, a dot-separated path for each relationship name can be specified:

------

Currently a request like this will fail to include anything.

    /articles/1?include=comments.author

However it will work if I include `comments` and `comments.author`.

    /articles/1?include=comments,comments.author

**Comment by rollokb** [comment]
I'd like to work on this.

**Comment by jerel** [comment]
I had noticed this quirk also. Do you feel like it's a bug or a feature. I'm not sure that including `comments.author` without `comments` makes sense.

**Comment by rollokb** [comment]
From the spec:

> Because compound documents require full linkage, intermediate resources in a multi-part path must be returned along with the leaf nodes

I think it's a bug. I think the JSON API spec asks for intermediate resources to be returned. Right now DRF-JSON API doesn't return anything.

**Comment by jerel** [comment]
Ah yes. It does spell it out there in the spec.

**Comment by rollokb** [comment]
I'm happy to fix this myself over the weekend.

**Comment by jsenecal** [comment]
It's not a bug, but rather a missing feature IMO... Including `comments.author` is very different from including `comments-author` and including comments.author without including comments would be silly...

The cited specs is talking about the `comment-author` I think...

**Comment by rollokb** [comment]
@jsenecal are you sure including `comments.author` is different from `comments,comments.author`? Other than the latter being needlessly redundant?

**Comment by jsenecal** [comment]
Yes, well, I do understand the redundancy.

The example we have here might not be the best one.

Let's use `comments.tags`...
Not all comments have tags. Including all comments when we really are in fact interested in tags is wasted machine time.

**Comment by jsenecal** [comment]
Although, reading the [spec](http://jsonapi.org/format/#fetching-includes) referenced by https://github.com/django-json-api/django-rest-framework-json-api/issues/149#issuecomment-152068402 it appears that it is actually the other way around and that including `comments.author` should include all comments as well.

Feel free to work on this but be warned that it's a feature easy to break and I'm not sure the tests in place are covering all the possible use cases.

**Comment by rollokb** [comment]
Talking of tests the `utils.py` methods don't have any, before I write a fix, I'd like to make some headway on that. 

Some of the functions are quite long and might be more testable if broken up.

**Comment by jerel** [comment]
The tests for utils.py are here https://github.com/django-json-api/django-rest-framework-json-api/blob/develop/example/tests/unit/test_utils.py

**Comment by jsenecal** [comment]
@rollokb any success on implementing broken tests ?
