### ISSUE TITLE
support nested objects

### ISSUE THREAD

**Issue by patroqueeet** [django-json-api/django-rest-framework-json-api#157]
Dear,

thanks for this great module here!

Question while using it for my project:

emberjs sends JSON-API complient nested `venue` data:
```
{"data":{
 "attributes":{
  "bought-at":null,
  "sold-at":null
 },
 "venue":{
   "data":{
    "attributes":{
     "title":"Brackenweg 13, 01936 Schwepnitz, Deutschland",
     "place-id":"ChIJwzCB6gs3CEcRDw0G3kCOU34",
     "lat":51.33011,
     "lon":13.965159999999969},
    "type":"venues"
   }
  },
 "type":"landlords"}}
```

according to drf frontend it needs:
```
{"data":{
 "attributes":{
  "bought-at":null,
  "sold-at":null,
  "venue":{
   "title":"Brackenweg 13, 01936 Schwepnitz, Deutschland",
   "place-id":"ChIJwzCB6gs3CEcRDw0G3kCOU34",
   "lat":51.33011,
   "lon":13.965159999999969
  },
  "type":"venues"},
"type":"landlords"}
}
```

for my serializer:
```
from rating.models import Rating
from location.models import Venue
from utils.images import get_location_images
from landlord.models import Landlord

from rest_framework import serializers

class LandlordSerializer(serializers.HyperlinkedModelSerializer):
    venue = VenueSerializer()

    class Meta:
        model = Landlord
        fields = ('venue', 'sold_at', 'bought_at', 'id')
```

I'm running your latest 2.0.0.beta.2

I read your docu, read the code, read the example. still I'm too stupid to make it work.

I'd be extremely glad for a quick hint or a docu update.

**Comment by jsenecal** [comment]
Nested objects are described in the JSON:API format [here](http://jsonapi.org/format/#document-compound-documents) but nothing stops you from using some sort of SerializerMethodField and do the rendering here.

Would that explanation help your use case ?

**Comment by patroqueeet** [comment]
dear, thanks for the link. according to that, either one - what ember sends and what drf needs is neither json api compatible. so 'm not smarter now :)

but I believe the pull request I sent you will resolve that hopefully. though it does not meet json api requirements. should we drop the pull request accordingly?

best

j

**Comment by jsenecal** [comment]
Sorry for the lack of follow-up. Did you resolve your issue?

**Comment by patroqueeet** [comment]
dear, my pull request is working with ember.js JSONSerializer for now. But I'd love to be able to use JSONApi standards. does `django-json-api` fulluy sopport the above referenced standards? if so, I will try to move my app asap to that.
