### ISSUE TITLE
Relation types only take into account model names which are not always correct.

### ISSUE THREAD

**Issue by bierdybard** [django-json-api/django-rest-framework-json-api#166]
Example:

```
#models.py
class Ticket(models.Model)
    #auto pk
    handle = models.CharField(max_length=255)

class Task(models.Model)
    #auto pk
    label = models.CharField(max_length=255)
    ticket = models.ForeignKey(Ticket, blank=True, null=True)

#views.py
class TicketViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = Ticket.objects.all()
    serializer_class = serializers.TicketSerializer
    resource_name = 'service-now-ticket'

class TaskViewSet(viewsets.ModelViewSet):
    queryset = Task.objects.all()
    serializer_class = serializers.TaskSerializer
    resource_name = 'task'

#serializers.py
from rest_framework_json_api import serializers

class TicketSerializer(serializers.ModelSerializer):
    class Meta:
        model = models.Ticket
        fields = (
            'id',
            'handle',
        )

class TaskSerializer(serializers.ModelSerializer):
    ticket = serializers.ResourceRelatedField(read_only=True)
    class Meta:
        model = models.Task
        field = (
            'id',
            'label',
            'ticket',
        )
```

When invoked, the desired output for Task is:
```
{
    "data": {
        "type": "task",
        "id": "126",
        "attributes": {
            "label": "This is a task"
        },
        "relationships": {
            "ticket": {
                "data": {
                    "type": "service-now-tickets",
                    "id": "91734"
                }
            }
        }
    }
}
```

However, the actual output is:
```
{
    "data": {
        "type": "task",
        "id": "126",
        "attributes": {
            "label": "This is a task"
        },
        "relationships": {
            "ticket": {
                "data": {
                    "type": "tickets",
                    "id": "91734"
                }
            }
        }
    }
}
```

**Comment by bierdybard** [comment]
It appears that `ResourceRelatedField` is calling `get_resource_type_from_instance()` for its `type` value, which bases the type solely on the model name.

I think an appropriate solution here would be to add an explicit `resource_type` argument to the ResourceRelatedField constructor that would be used both in output and input validation.

I'll begin work on a PR with a failing test case and fix unless there are any concerns.

**Comment by jsenecal** [comment]
While your proposed solution works for your use case, another discussion in another issue/pr (sorry I'm on my mobile) described the possibility of using a custom Meta class on the models to define custom types.

**Comment by bierdybard** [comment]
Aha, I see #152 .

I'm on board with that, and I think it's a more elegant way to handle it because it gets the data where it should be, on the model. It looks like the places that previously relied on _meta.model.__name__ have been changed to point at that, as well.

I'll close this issue in favor of that solution.

**Comment by bierdybard** [comment]
I considered this a bit more this morning, and it came to me that there is another case that #152 does not cover that this type of solution may be appropriate for.

There may be instances where for various reasons multiple serializers/API endpoints refer back to the same model. An override of this type would be useful in those situations as well.

Thoughts?

**Comment by jsenecal** [comment]
Proxy models?

**Comment by bierdybard** [comment]
That is an elegant and simple solution that only someone who has been buried so long in his code that he forgot to come up for air can miss. 😂 Consider this closed.
