### ISSUE TITLE
Creating object with relation

### ISSUE THREAD

**Issue by riklaunim** [django-json-api/django-rest-framework-json-api#173]
I'm having problem with making ember create request to work with DRF + DRF-json-api#0ceeddd9eaf02d60be7b5ea0574a4ce2623a3e8b when the created model has a relation ChildModel -> FK(Place).

Ember posts the Place ID:

    {'starts_at': '2015-12-14', 'id': None, 'ends_at': '2016-01-14', 'title': 'test', 'contents': 'test'
    , 'place': OrderedDict([('id', '92'), ('type', 'places')]), 'language': 'pl', 'is_active': False}

And DRF serializer class for the Child model API has:

    place = serializers.HyperlinkedRelatedField(many=False, view_name='api:places-detail', read_only=True)

Yet it can't create child because place_id ends up null when trying to INSERT it.

I can override create method in the API view and fetch place from that JSON data and set place/place_id values on request.data but that doesn't help either - like if something was overriding or ignoring my data.

Is there a special create/update/delete configuration for DRF-json-api APIs?

**Comment by jerel** [comment]
It looks to me like your Ember Data configuration is not running as JSON API. Make sure your application adapter extends `DS.JSONAPIAdapter` on the client and that you're using the `rest_framework_json_api` renderer and parser on the server.

**Comment by riklaunim** [comment]
I do have `DS.JSONAPIAdapter` in ember, and 

```
parser_classes = [
        rest_framework_json_api.parsers.JSONParser,
        rest_framework.parsers.FormParser,
        rest_framework.parsers.MultiPartParser,
]
renderer_classes = [
        rest_framework_json_api.renderers.JSONRenderer,
        rest_framework.renderers.BrowsableAPIRenderer,
]
metadata_class = rest_framework_json_api.metadata.JSONAPIMetadata
paginator_class = rest_framework_json_api.pagination.PageNumberPagination
...
```
in the API endpoint

**Comment by jerel** [comment]
That looks right. What about your Ember Data application serializer? Is it extending `DS.JSONAPISerializer`?

**Comment by riklaunim** [comment]
That was missing,  it changed the POSTed data to something like this:

    {"data":{"attributes":{"title":"test"},"relationships":{"place":{"data":{"type":"places","id" :"92"}}},"type":"someModel"}}

but still place_id is null.

**Comment by jerel** [comment]
That's looking correct now. Note that `place` is contained in the `relationships` object now and not in the `attributes`. The server side parser should take it apart and make the `place` model available in the serializer. If you add:
``` py
def validate(self, obj):
    import ipdb;ipdb.set_trace()
```
to your serializer then you can inspect `obj` to see if place has a value (it should). If not then the issue is server side.

**Comment by riklaunim** [comment]
In validate(self, attrs) the attrs have all values but no `place`.

**Comment by jerel** [comment]
I notice now that the payload that Ember Data is sending has a plural `places` type for the relationship. Make sure that it's the same on both client and server.

I would probably drop a debugger in `extract_relationships` in `rest_framework_json_api` and follow it through to see what's happening.

**Comment by riklaunim** [comment]
I'll check. I'm updating to the latest django-rest-framework-json-api checkout and see if that will change anything. Looking on the traceback - it looks like it doesn't hit django-rest-framework-json-api anywhere on it's way down to the exception. Maybe that's the problem.

**Comment by riklaunim** [comment]
looks like extract_relationships is never hit when posting.

**Comment by riklaunim** [comment]
I've narrowed down the problem. In serializer I tried to use:
```
place = PrimaryKeyRelatedField(many=False, queryset=Place.objects.all())
```
And that throw good error that instead of ID it got an OrderDict (when calling to_internal_value). So by subclassing that field to:

```
class PrimaryKeyRelatedField(serializers.PrimaryKeyRelatedField):
    def to_internal_value(self, data):
        return self.get_queryset().get(pk=data['id'])
```
It did work. So the actual problem is that the dict from relationship wasn't recognized as valid field value.

**Comment by riklaunim** [comment]
works on latest version with proper configuration ;)
