### ISSUE TITLE
Django 1.9 moves/renames ReverseManyRelatedObjectsDescriptor

### ISSUE THREAD

**Issue by lsowen** [django-json-api/django-rest-framework-json-api#176]
Per the [release notes](https://docs.djangoproject.com/en/1.9/releases/1.9/#removed-features-1-9), ReverseManyRelatedObjectsDescriptor has been moved from ``django.db.models.fields.related`` to ``jango.db.models.fields.related_descriptors`` and renamed to ``ReverseManyToOneDescriptor``.

I believe the only use of this in in https://github.com/django-json-api/django-rest-framework-json-api/blob/4f9a7aa3bb4797a618a8bf060e7269109a3540cf/rest_framework_json_api/metadata.py#L48

I would be willing to make the change, I'm just not sure the best way to support both 1.9 and 1.8 version.

**Comment by jerel** [comment]
@lsowen I'd be happy for you to contribute the change! Doing the import in metadata.py a little like this should provide backward compatibility:
``` py
try:
    from django.db.models.fields.related_descriptors import ReverseManyToOneDescriptor as ReverseDescriptor
except ImportError:
    from django.db.models.fields.related import ReverseManyRelatedObjectsDescriptor as ReverseDescriptor
```

**Comment by abdulhaq-e** [comment]
>ReverseManyRelatedObjectsDescriptor has been moved from django.db.models.fields.related to jango.db.models.fields.related_descriptors and renamed to ReverseManyToOneDescriptor.

Can you please look at this commit by @jamesturk https://github.com/django-json-api/django-rest-framework-json-api/commit/a487332d9b00c8690b9136b4888ad10283d68db1

I think he already handles this issue. Besides, according to the release notes, the following changes has been made:
> ReverseSingleRelatedObjectDescriptor ---> ForwardManyToOneDescriptor
SingleRelatedObjectDescriptor ---> ReverseOneToOneDescriptor
ForeignRelatedObjectsDescriptor ---> ReverseManyToOneDescriptor
ManyRelatedObjectsDescriptor ---> ManyToManyDescriptor

There is no mention of  ReverseManyRelatedObjectsDescriptor. I think they merged `ReverseManyRelatedObjectsDescriptor` (which is on [L54](https://github.com/django-json-api/django-rest-framework-json-api/blob/a487332d9b00c8690b9136b4888ad10283d68db1/rest_framework_json_api/metadata.py#L54)) and `ManyRelatedObjectsDescriptor` (which is on [L53](https://github.com/django-json-api/django-rest-framework-json-api/blob/a487332d9b00c8690b9136b4888ad10283d68db1/rest_framework_json_api/metadata.py#L53)) into `ManyToManyDescriptor` (source code comments says that the latter handles forward and reverse operations). Perhaps the merge was made even before 1.9, maybe they were merged into `ManyRelatedObjectsDescriptor` which was then renamed in 1.9.

So I don't think renaming is an issue here, the try/except handles it. What puzzles me is your first point about moving the descriptors to `related_descriptors.py`. How do the tests pass? In particular, why do lines [L47-49](https://github.com/django-json-api/django-rest-framework-json-api/blob/a487332d9b00c8690b9136b4888ad10283d68db1/rest_framework_json_api/metadata.py#L47-L49) work? It should be `related_descriptor.***`

**Comment by jerel** [comment]
I'm running Django 1.9 and am unable to replicate this. Can someone give a scenario where it fails? Otherwise I'll close this

**Comment by lsowen** [comment]
@jerel What version of this module are you using?  I was using whatever the lastest on pypi at the time was, which might be causing the issue.  I will attempt to retest this weekend and see if I can recreate (and get a clean test case).

**Comment by jerel** [comment]
I've been using `develop`, now am on v2.0.0-beta.1

**Comment by jerel** [comment]
If you were running one of the alpha tags then yes, this is likely fixed in develop since that was tagged.

**Comment by jerel** [comment]
I'm going to close this since it sounds like it was an issue in an early release. If the behavior still exists in `develop` then we'll reopen
