### ISSUE TITLE
Configure type inflection rules

### ISSUE THREAD

**Issue by gonvaled** [django-json-api/django-rest-framework-json-api#186]
`EmberData` is `POST`ing:

```
    {
      "data": {
        "attributes": {
          "name": "The project name",
          "description": "The project description",
          "price": 123
        },
        "relationships": {
          "onwer": {
            "data": null
          }
        },
        "type": "projects"
      }
    }
```

And `Django` (`django-rest-framework-json-api` I guess) is complaining with a `409 Conflict`:

```
    {
      "errors": {
        "detail": "The resource object's type (projects) is not the type that constitute the collection represented by the endpoint (project)."
      }
    }
```

Apparently the `JSONApi` spec [does not][1] enforce an inflection rule. How can I tell `django-rest-framework-json-api` to accept plurals for the type?

  [1]: http://jsonapi.org/format/#document-resource-object-identification

**Comment by gonvaled** [comment]
It seems there is a configuration paramater which (afaik) is not mentioned in the documentation:

```
JSON_API_PLURALIZE_RELATION_TYPE = True
```

https://github.com/django-json-api/django-rest-framework-json-api/blob/develop/rest_framework_json_api/utils.py#L143

**Comment by jerel** [comment]
It should already be documented here under Relationship Types http://django-rest-framework-json-api.readthedocs.org/en/latest/usage.html#inflecting-object-and-relation-keys

**Comment by gonvaled** [comment]
You are right, sorry. I was not able to find this. I am closing the issue then.
