### ISSUE TITLE
pip install djangorestframework-jsonapi fails

### ISSUE THREAD

**Issue by mblayman** [django-json-api/django-rest-framework-json-api#191]
Running `pip install djangorestframework-jsonapi` fails as documented on Read the Docs. I believe the reason is that pip fails to recognize all the available version numbers appropriately.

According to the setuptools docs, the `-` in the version number makes the posted version a "post-release" number. https://pythonhosted.org/setuptools/setuptools.html#specifying-your-project-s-version

Here is the output I saw when I tried to run the command:

```bash
$ pip install djangorestframework-jsonapi
Downloading/unpacking djangorestframework-jsonapi
  Could not find a version that satisfies the requirement djangorestframework-jsonapi \
(from versions: 2.0.0-alpha.1, 2.0.0-alpha.2, 2.0.0-alpha.3, 2.0.0-alpha, 2.0.0-beta.1)
Cleaning up...
No distributions matching the version for djangorestframework-jsonapi
Storing debug log for failure in /home/matt/.pip/pip.log
```

I don't know for sure, but my guess is that in the absence of an actual version (i.e., `2.0.0`), pip gives up when it only finds post release versions.

**Comment by mblayman** [comment]
I should add that `pip install djangorestframework-jsonapi==2.0.0-beta.1` **does** work. Maybe the solution until the project comes out of beta with a `2.0.0` release is to document pip install with the specific version specifier.

**Comment by kevin-brown** [comment]
The latest release is 2.0.0-beta.1, which pip will not automatically install because it is an unstable version. The older versions, 1.3.2 and below, are [not available on PyPI](https://pypi.python.org/simple/djangorestframework-jsonapi/) because it was previously called [`rest_framework_ember`](https://pypi.python.org/pypi/rest_framework_ember/).

You can still install the beta versions by explicitly specifying them.

**Comment by holandes22** [comment]
alternatively, you can use the --pre flag

    pip install --pre djangorestframework-jsonapi

**Comment by mblayman** [comment]
At some point, `pip` fixed this problem in a newer version. I tried `pip install djangorestframework-jsonapi` on my Mac this morning and it worked without issue. My Mac has pip version `7.0.3`.

The command failed on the pip version that comes with Ubuntu 14.04. That version is `1.5.4`.
