### ISSUE TITLE
Set custom "type" for ResourceRelatedField

### ISSUE THREAD

**Issue by EmilTemirov** [django-json-api/django-rest-framework-json-api#193]
Hi, all! 
I have the following Django model:
```python
class Comment(model.Model):
    text = models.TextField()
    parent_comment = models.ForeignKey('self', null=True, blank=True, on_delete=models.CASCADE)
```
I want to be able to obtain a list of comments with "parent" in relationships, for example:
```javascript
{
  "data": [
    {
       "type": "comments",
        "id": "1",
        "attributes": {
          "text": "First comment"
        },
        "relationships": {
          "parent": {
            "data": null
          } 
        }
    },
    {
       "type": "comments",
        "id": "2",
        "attributes": {
          "text": "Child comment"
        },
        "relationships": {
          "parent": {
            "data": {
              "type": "comments",
              "id": 1
            }
          } 
        }
    },
  ]
}
```

My serializer:
```python
class CommentSerializer(ModelSerializer):
    parent = ResourceRelatedField(source='parent_comment', read_only=True)

    class Meta:
        model = Comment
        fields = ('text', 'parent',)
```
In my ViewSet I have defined resource_name = 'comments', but it is doesn't work for "parent" in relationships. At the present time, "type" of "parent" is "Comment". How can I fix this issue?

**Comment by leifurhauks** [comment]
It should now possible to specify the resource name on the model class, thanks to #152 .

for example:
```python
class Comment(models.Model):
    class JSONAPIMeta:
        resource_name = 'comments'
   # the rest of the model definition...
```

**Comment by jerel** [comment]
leifurhauks' example should solve this. I'll close and if it doesn't fix then let us know.

**Comment by EmilTemirov** [comment]
Thanks! Please, describe this feature in the documentation. 
Actually, I have found in sources that there is possible to set model attribute in the ResourceRelatedField, for example:
```python
class MySerializer(serializers.ModelSerializer):
    parent = relations.ResourceRelatedField(source='comment_parent', model=Comment, read_only=True)
```
But it does not work. It will work properly if override the following lines in renderers.py:
```python
@staticmethod
def extract_relationships(fields, resource, resource_instance):
       # ....
       if isinstance(field, ResourceRelatedField):
                # special case for ResourceRelatedField
                if hasattr(field, 'model'):
                    res_data = resource.get(field_name)
                    relation_data = {
                        'data': OrderedDict([('type', relation_type), ('id', res_data['id'])]) if res_data else None
                    }
                else:
                    relation_data = {
                        'data': resource.get(field_name)
                    }
       # ....
```
I'm not sure that it is right approach, so will use leifurhauks' solution, but it very seems like a bug -)

**Comment by leifurhauks** [comment]
If I remember correctly, the ResourceRelatedField used to use the model kwarg to determine the type name when read-only, but I think this behaviour may have been changed since then to support heterogeneous to-many relationships (e.g. polymorphic relationships with objects of more than one type).
