### ISSUE TITLE
POST request Unit Test

### ISSUE THREAD

**Issue by snewcomer** [django-json-api/django-rest-framework-json-api#202]
I'm trying to get a post request to work in a unit test.  A few things jump out.  
1.  An `attributes` key is not provided in the POST request, but I get it back in the response as shown by the first assertEqual, a passing test.  However, I do not get back any `relationships` data.  
2.  I can't use the serializer `ExampleSerializer` to generate the data to send in the post request like I did with Django REST.

So do I have to explicitly setup my data to pass in the post request?  A bit confused because I didn't pass an `attributes` key.  Also is `relationships` data always returned or do I need a `source` keyword in the ResourceRelatedField or something?  Any thoughts on my test setup or serializer setup would be great.

Unit Test Setup
```
    def setUp(self):
        self.person = create_person()
        self.example = factory.create_single_example()
        serializer = ExampleCreateSerializer(self.example)
        self.data = serializer.data
        del self.data['assignee']
        self.data['relationships'] = {"assignee": {"data": { "type": "people", "id": str(self.person.id)}}}
        self.data.update({
            'id': str(uuid.uuid4()),
        })
        self.response = self.client.post('/api/example/', self.data)
```
self.data
`{'id': '111...uuid', 'name': 'wat', 'relationships': {'assignee': 'data': {'type': 'people', 'id': '3333...uuid'}}}`

Unit Test
```
    def test_data(self):
        data = json.loads(self.response.content.decode('utf8'))
        attributes = data['data']['attributes']
        relationships = data['data']['relationships']
        self.assertEqual(self.data['name'], attributes['name']) #passes
        self.assertEqual(self.data['relationships']['assignee']['data']['id'], relationships['assignee']['data']['id']) #does not return `relationships` data
```
Serializer
```
class ExampleCreateSerializer(BaseCreateSerializer):
    assignee = ResourceRelatedField(model=Person, read_only=True)
    class Meta:
        model = Example
        fields = ('id', 'name', 'assignee')
```

**Comment by jerel** [comment]
It doesn't look like your POST payload is structured according to spec. It should be a `data` object with `type` and  `attributes` keys. That likely means that the relationship is not created and so won't be in the output.

The `ExampleCreateSerializer` only creates a serialized representation of the model. Placing it inside a `data` object and etc is handled by the renderer so you'll need to do it manually here.

**Comment by snewcomer** [comment]
Ah thank you!  So a couple of notes:
0.  Had to structure the payload according to the spec explicitly  Thought I could use the serializer to generate the correct data.
`self.data = {"data": {"type": "examples", "id": str(uuid.uuid4()), "attributes": {"name":"wat"}}}`
1.  Had to include a content type
`self.response = self.client.post('/api/example/', json.dumps(self.data), content_type="application/vnd.api+json")`
2.  And then I had to json.dumps(self.data) to get it in double quotes.

Hope it helps somebody, although that was so simple, it probably won't!

**Comment by snewcomer** [comment]
Also, for some reason, the ResourceRelatedField needs to be setup like this and not like above.

    `assignee = ResourceRelatedField(queryset=Person.objects)`
