### ISSUE TITLE
Resource name - relationships

### ISSUE THREAD

**Issue by snewcomer** [django-json-api/django-rest-framework-json-api#206]
Is is possible to set the resource name on relationship objects, where foo belongs to the status model?  It keeps returning 'Statuses' in the json relationships object for the Foo model.  However, I set the resource_name as show below...

```
class FooListSerializer(serializers.ModelSerializer):

    class Meta:
        model = Foo
        fields = ('id', 'name', 'status')
```
```
class Status(BaseNameModel):

    objects = StatusManager()

    class JSONAPIMeta:
        resource_name = 'status'
```

**Comment by jerel** [comment]
@snewcomer which version are you on? I believe your code should work on v2.0.0-beta.2 but it won't on earlier versions.

Alternatively `status` should be derived from the model name without manually setting `resource_name` if you have `JSON_API_FORMAT_RELATION_KEYS` set to underscore.

**Comment by snewcomer** [comment]
The changelogs are always a good idea to review.  Live and learn!  Thanks.
