### ISSUE TITLE
Problem getting JSON response to contain JSON API data attribute, etc.

### ISSUE THREAD

**Issue by davidthewatson** [django-json-api/django-rest-framework-json-api#208]
I am using Django REST Framework JSON API:

https://github.com/django-json-api/django-rest-framework-json-api

I have the following model:

    class Question(BaseModel):
        text = models.TextField(unique=True)
        members = models.ManyToManyField(Member, related_name='questions')

        def __str__(self):
            return self.text

        class JSONAPIMeta:
            resource_name = "questions"

    class Answer(BaseModel):
        text = models.TextField(blank=True)
        icon = models.TextField()
        question = models.ForeignKey(Question, related_name='answers')

        def __str__(self):
            return self.text or self.icon

        class JSONAPIMeta:
            resource_name = "answers"

and the following serializers:

    class AnswerSerializer(serializers.ModelSerializer):
        class Meta:
            model = Answer
            fields = ('text', 'icon')

    class QuestionSerializer(serializers.ModelSerializer):
        answers = AnswerSerializer(many=True, read_only=True)

        class Meta:
            model = Question
            fields = ('text', 'answers')

and the following views:

    class QuestionViewSet(viewsets.ReadOnlyModelViewSet):
        """
        API endpoint that allows questions and answers to be read.
        """
        queryset = Question.objects.all()
        serializer_class = QuestionSerializer
        renderers = renderers.JSONRenderer
        parsers = parsers.JSONParser

However, when I test the API asking for pk=1, the JSON response does not conform to the JSON API specs:

    {"text": "Are you dizzy?", "answers": [{"text": "No", "icon": "icon-no"}, {"text": "A little dizzy", "icon": "icon-dizzy-somewhat"}, {"text": "Very dizzy", "icon": "icon-dizzy-very"}]}

I'm importing the various renderers and parsers from the DRF JSON API package, and the endpoints are being generated by the viewset. How can I make the responses contain the proper data attribute and conform to the JSON API spec?

**Comment by leifurhauks** [comment]
Have you set the JSON API renderer as the default renderer in your DRF settings? Or, if not, are you setting the `Accept` header to `application/vnd.api+json`?

**Comment by davidthewatson** [comment]
Thanks for your response.

I'm using the JSON API renderers explicitly in the views, i.e.

    from rest_framework_json_api import renderers, parsers

So defaults are a no-op.

I'll try changing the Accept header in my tests and report back.

**Comment by leifurhauks** [comment]
Ah, sorry about that, I ought to have figured that out from your code snippets.

I could be mistaken, but I think the `renderers` class attribute on the viewset should be an iterable (likewise for `parsers`). You could try changing
```
renderers = renderers.JSONRenderer
```
to
```
renderers = (renderers.JSONRenderer,)
```
and see if that fixes it to use the correct renderer. The response you posted looks like the standard DRF JSON renderer.

**Comment by davidthewatson** [comment]
Thanks, again.

Turns out that setting the accept header to application/vnd.api+json generates a 406. That surprised me and seems to suggest that the JSON API renderers are not hooked up.

And I was puzzling over the plurality of the attributes in renderers and parsers with the singularity of the rvalues. I changed to the tuple spec as you suggested, but the results are still the same.

I even restarted the django debug server because it seemed weird. Then I ran with renderers and parsers removed and the client side result was the same.

Then I decided to look at the base classes. BINGO! It's not renderers and parsers. It's:

    renderer_classes = (renderers.JSONRenderer,)
    parser_classes = (parsers.JSONParser,)

And then the response looked like this, of course:

    {
      "data": {
        "type": "questions",
        "id": "1",
        "attributes": {
          "text": "Are you dizzy?"
        },
        "relationships": {
          "answers": {
            "data": [
              {
                "type": "answers",
                "id": "1"
              },
              {
                "type": "answers",
                "id": "2"
              },
              {
                "type": "answers",
                "id": "3"
              }
            ]
          }
        }
      }

Now I can't even find the code example that I copied this pattern from. It may not exist! Sorry for the trouble @leifurhauks, but thanks for the debugging help. I'd be happy to make a pull request on the docs with the specific viewset example so that this never happens again.

**Comment by davidthewatson** [comment]
The only trouble that I'm having now is that my tests are still returning the undecorated JSON, not the JSON API spec, even when I set the accept header as application/vnd.api+json. Calls from a real client return expected results without setting the accept header.

Any idea how to get the tests to return the expected JSON API responses? My tests look like:

    response = self.csrf_client.get(url, HTTP_AUTHORIZATION=self.auth)

and I also tried:

    response = self.csrf_client.get(url, HTTP_AUTHORIZATION=self.auth, **{'Accept': 'application/vnd.api+json'})

**Comment by leifurhauks** [comment]
An unfortunate peculiarity of the django test client is that headers need to be in the WSGI format, thus `HTTP_ACCEPT` instead of `Accept`. I had the same problem once; I ended spending about two or three hours debugging with the test client before I figured that out.

**Comment by davidthewatson** [comment]
Thanks! Got it fixed. Closing.
