### ISSUE TITLE
Included key with get_serializer_class

### ISSUE THREAD

**Issue by snewcomer** [django-json-api/django-rest-framework-json-api#209]
`get_serializer_class` method on the view doesn't work when trying to get included resources.  Is this a pull request you would be open to (w/ tests of course!)?

**Comment by snewcomer** [comment]
This line seems to be the source of the err.

https://github.com/django-json-api/django-rest-framework-json-api/blob/4488068295574d19974c304b7c9f903ff10c810e/rest_framework_json_api/serializers.py#L97

**Comment by jerel** [comment]
@snewcomer from what I see that seems it should be replaced with a call to `get_serializer_class`. I would welcome a PR with test coverage

**Comment by jerel** [comment]
Closed by #213
