### ISSUE TITLE
Using EXCEPTION_HANDLER is not compatible with multiple DRF configurations

### ISSUE THREAD

**Issue by riklaunim** [django-json-api/django-rest-framework-json-api#214]
To get proper error responses EXCEPTION_HANDLER must be set as mentioned in #188 however EXCEPTION_HANDLER is the only setting that can't be set on a class, thus preventing multi-configuration projects -  I have vanilla-DRF and JSONApi views in the project.

The source of the problem is in https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/views.py#L413 where exception_handler = self.settings.EXCEPTION_HANDLER

I asked on DRF irc channel about it and it was suggested that the renderer itself could handle that error response formatting. Can't say how that would fit, but it's either that or slight modification to the base view class in DRF so that it's easier to change the exception handler (instead of hacking with deepcopy of self.settings or copy-pasting the whole method).

**Comment by jerel** [comment]
For now I imagine that the best workaround would be to create a mixin that overrides the DRF `handle_exception` and either calls the `super` implementation or does something custom based on other view attributes.

If we moved the exception formatting to the renderer what would be the nicest API to call it with? Are you setting the DRF renderer or the DRF-JA renderer on each view class? I'm happy to review a pull request if you have time to implement something. I would think [this code could easily be extracted](https://github.com/django-json-api/django-rest-framework-json-api/blob/3c9ab1888065e54024c4de9450f0c79e4ff5e0cc/rest_framework_json_api/exceptions.py#L22-L73) to a `format_drf_errors` util method or to the renderer.

**Comment by riklaunim** [comment]
I have one base class with all DRF-JA settings that every API View inherits. Will take a look at it.

**Comment by riklaunim** [comment]
Looking at the DRF interface the best way would be to change it a bit - https://github.com/tomchristie/django-rest-framework/pull/4045 - if that gets merged no change to exception handle would be needed, as it could be set via method override.

**Comment by jerel** [comment]
Closed by #222
