### ISSUE TITLE
Missing "errors" field in error response

### ISSUE THREAD

**Issue by joeyespo** [django-json-api/django-rest-framework-json-api#218]
The 400-level errors are responding with a JSON array containing error objects, but the JSON API spec [requires](http://jsonapi.org/format/#document-top-level) a top-level `error` field.

##### To reproduce

1. Use `serializer.is_valid(raise_exception=True)` in an API view
2. Send invalid JSON from the client to *any* API endpoint

    Example:
    ```js
    ajax({
      url: '/my/api',
      contentType: 'application/vnd.api+json',
      type: 'POST',
      data: 'not JSON'
    });
    ```

    Expected response:
    ```json
    {
      "errors": [
        {
          "status": "400",
          "source": {"pointer": "/data"},
          "detail": "JSON parse error - No JSON object could be decoded"
        }
      ]
    }
    ```

    Actual response:    
    ```json
      [
        {
          "status": "400",
          "source": {"pointer": "/data"},
          "detail": "JSON parse error - No JSON object could be decoded"
        }
      ]
    ```

It seems like the exception handler is [properly setting the resource name](https://github.com/django-json-api/django-rest-framework-json-api/blob/v2.0.0-beta.2/rest_framework_json_api/exceptions.py#L72), which *should* be used [here](https://github.com/django-json-api/django-rest-framework-json-api/blob/v2.0.0-beta.2/rest_framework_json_api/renderers.py#L376-L405). The former gets called, but the latter does not. DRF seems to have taken over, responding with this project's `exception_handler` as-is.

##### My requirements

```
...
Django==1.9.1
djangorestframework==3.3.3
djangorestframework-jsonapi==2.0.0-beta.2
...
```

##### My config

```py
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework_json_api.renderers.JSONRenderer',
    ),
    'DEFAULT_PARSER_CLASSES': (
        'rest_framework_json_api.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ),
    'EXCEPTION_HANDLER': 'rest_framework_json_api.exceptions.exception_handler',
}
```

**Comment by jerel** [comment]
@joeyespo thanks for the detailed bug report. Did you end up finding a fix and would you like to open a PR? If not I'll try to get to it myself. I'm guessing that the issue has something to do with calling `serializer.is_valid(raise_exception=True)` manually rather than by the view itself.

**Comment by joeyespo** [comment]
@jerel Thanks for the reply! I did. I got something working locally for both this and #214. I'll open a PR within the next couple days.

**Comment by jerel** [comment]
@joeyespo good to hear! I did just merge a pull request (#222) that moves the error formatting to utils.py. Not much changed with the implementation but you'll want to pull that in before opening your PR

**Comment by joeyespo** [comment]
Ok. Rebased and opening the PR now. Feel free to rename any variables or completely change it.
