### ISSUE TITLE
The get_resource_type_from_serializer bug

### ISSUE THREAD

**Issue by EmilTemirov** [django-json-api/django-rest-framework-json-api#219]
django-rest-framework-json-api v2.0.0-beta.2
I have defined `resource_name` attribute into Meta class of my serializer:
```python 
class MySerializer(serializers.Serializer):
    email = serializers.EmailField(required=True)
    class Meta:
        resource_name = 'user'
```
In this case the `get_resource_type_from_serializer` will always raise AttributeError, because there isn't defined the `model` attribute.
Code of `get_resource_type_from_serializer`:
```python
def get_resource_type_from_serializer(serializer):
    return getattr(
        serializer.Meta,
        'resource_name',
        get_resource_type_from_model(serializer.Meta.model))
```

**Comment by scottfisk** [comment]
I just PRed a fix for this.
