### ISSUE TITLE
GenericRelation Support

### ISSUE THREAD

**Issue by snewcomer** [django-json-api/django-rest-framework-json-api#224]
Is GenericRelation support possible?  This is how I would do it with Django rest.  Can't get this to work however as I am getting the `is not JSON serializable` error.  Guessing there might be some serialization issue with json api?

```
# Serializer
class FooSerializer(serializers.ModelSerializer):

    included_serializers = {
        'news': NewsSerializer,
    }

    class Meta:
        model = LSEquity
        fields = ('id', 'news')


# News Serializer
class NewsSerializer(serializers.ModelSerializer):

    class Meta:
        model = News
        fields = ('id', 'description', 'date')


# Foo Model
class FooModel(models.Model):
    news = GenericRelation(News)


# News Model
class News(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    description = models.TextField(max_length=200, blank=True)
    date = models.DateTimeField(blank=True, null=True)
    content_type = models.ForeignKey(ContentType)
    object_id = models.UUIDField()
    content_object = GenericForeignKey('content_type', 'object_id')

    class JSONAPIMeta:
        resource_name = 'news'
```

I'd be happy to add some "documentation" through the examples and work through it that way.  That is of course if somebody has not already come across this!

**Comment by jerel** [comment]
I have not tried to use GenericForeignKey so it's possible that it's not implemented. If you want to open a PR with tests I'll happily review it

**Comment by patroqueeet** [comment]
+1

**Comment by snewcomer** [comment]
https://github.com/snewcomer/django-rest-framework-json-api/commit/ac5c0e1e72f3708847af5fe933c299f7e906c755

Here is the commit.  Existing failing test here: https://github.com/django-json-api/django-rest-framework-json-api/blob/develop/example/tests/integration/test_includes.py#L43

**Comment by snewcomer** [comment]
Any thoughts on getting Generic Relation support?  Sry wish I could contribute but a bit overloaded right now (as we all are :) )
