### ISSUE TITLE
DateRangeField fails

### ISSUE THREAD

**Issue by dbinetti** [django-json-api/django-rest-framework-json-api#227]
Not sure this is a JSON API issue, but tests seem to pass with the other libraries, so throwing this over the wall....

Basically, I'm trying to create an unbounded DateRange field (postgres).  More difficult to explain that to simply show, so there's a test repo here:

https://github.com/dbinetti/djangodaterange

Hopefully that's clear enough

**Comment by jerel** [comment]
What behavior are you expecting and what behavior are you getting instead?

**Comment by dbinetti** [comment]
I am trying to POST a record including an unbounded DateRangeField, meaning
that either the "upper" or "lower" fields may be null.   (ref for the
field: http://initd.org/psycopg/docs/extras.html#range-data-types)

I expect the field to save/be created.  I'm getting an error "This field
may not be null."

Also, it's in the test repo itself, so you can run it and see the results.

**Comment by jerel** [comment]
I've spent some time tracing this and other than the DRF browsable interface not handling the DateRangeField correctly when used with json-api I don't see any problems with our package and DateRangeField. I do see the behavior that you describe but it is a 400 ValidationError (which we don't throw). We only catch DRF validation errors and format them. When dropping a debugger in a serializer I see the unmangled data being passed in so our parser isn't stripping it out. Also, saving a bounded DateRange works fine so I'm suspecting there's an issue with the validator.
