### ISSUE TITLE
Included serializers and relationships

### ISSUE THREAD

**Issue by khornberg** [django-json-api/django-rest-framework-json-api#232]
Should a `ModelSerializer` that has `included_serializers` NOT return relationships?
It seems that this is possible. Ought it be so?

According to the [compound documents](http://jsonapi.org/format/#document-compound-documents) section this change *may* produce an invalid response.

> Compound documents require "full linkage", meaning that every included resource MUST be identified by at least one resource identifier object in the same document. These resource identifier objects could either be primary data or represent resource linkage contained within primary or included resources.

So, if resource identifier objects for the requested primary resources are only included in the relationships of the primary resources, then not including relationships would make an invalid response. 

Using the JSON API spec as an example and removing the relationships like #231 proposes would cause the response to not have any of the resource identifier objects.

```
{
  "data": [{
    "type": "articles",
    "id": "1",
    "attributes": {
      "title": "JSON API paints my bikeshed!"
    },
    "links": {
      "self": "http://example.com/articles/1"
    }
  }],
  "included": [{
    "type": "people",
    "id": "9",
    "attributes": {
      "first-name": "Dan",
      "last-name": "Gebhardt",
      "twitter": "dgeb"
    },
    "links": {
      "self": "http://example.com/people/9"
    }
  }, {
    "type": "comments",
    "id": "5",
    "attributes": {
      "body": "First!"
    },
    "relationships": {
      "author": {
        "data": { "type": "people", "id": "2" }
      }
    },
    "links": {
      "self": "http://example.com/comments/5"
    }
  }, {
    "type": "comments",
    "id": "12",
    "attributes": {
      "body": "I like XML better"
    },
    "relationships": {
      "author": {
        "data": { "type": "people", "id": "9" }
      }
    },
    "links": {
      "self": "http://example.com/comments/12"
    }
  }]
}
```

**Comment by jerel** [comment]
Closing this as I'm not aware of it being possible to exclude relationships at this time. If there is a need for it feel free to reopen.
