### ISSUE TITLE
field.related RemovedInDjango110Warning

### ISSUE THREAD

**Issue by tpilara** [django-json-api/django-rest-framework-json-api#248]
This is likely an easy fix, I think the only tricky thing is making sure that this remains backwards compatible when making the change to field.remote_field.

This warning is seen using Django 1.9.

`rest_framework_json_api/utils.py:194: RemovedInDjango110Warning: Usage of field.related has been deprecated. Use field.remote_field instead.`

[Link to relevant line](https://github.com/django-json-api/django-rest-framework-json-api/blob/54f1dcd86bd571e83988c228e6ab3e3f72093d27/rest_framework_json_api/utils.py#L194)

**Comment by jerel** [comment]
Wrapping `field.remote_field` in a try/catch to fall back to `field.related` should be the right route forward on this if someone wants to tackle it

**Comment by alexahn** [comment]
See https://github.com/django-json-api/django-rest-framework-json-api/pull/255
