### ISSUE TITLE
Creation of related resources is not supported

### ISSUE THREAD

**Issue by morenoh149** [django-json-api/django-rest-framework-json-api#252]
Correct me if I'm wrong as I don't have much django experience.

Creation of related resources via the `relationships` key is unsupported. See http://jsonapi.org/format/upcoming/#crud-creating For example
```
{
    "data": {
        "type": "posts",
        "id": null,
        "attributes": {
            "headline": "This is a test, this is only a test",
            "bodyText": "And this is the body text for the blog entry. To see comments included in this payload visit: /entries/1?include=comments",
            "pubDate": null,
            "modDate": null
        },
      "relationships": {
            "blog": {
                "data": {
                    "type": "blog",
                    "attributes": {
                        "name": "Personal"
                    }
                }
            },
        "meta": {
            "bodyFormat": null
        }
    }
}
```

this could be achieved by adding a `create` method on the serializers. See http://www.django-rest-framework.org/api-guide/relations/#writable-nested-serializers in https://github.com/django-json-api/django-rest-framework-json-api/blob/develop/example/serializers.py

Please let me know if this would be a welcome feature and I will submit a PR.

**Comment by jerel** [comment]
Do you mean creation of the link to an existing model or creation of the related model at the same time? Relationship linking should be handled. Are you importing serializers from `rest_framework_json_api` and setting up your related fields as mentioned here? http://django-rest-framework-json-api.readthedocs.io/en/v2.0.1/usage.html#related-fields

**Comment by morenoh149** [comment]
I meant the latter. I will read that page now. I'm also starting to doubt the jsonapi spec even allows creating multiple related resources at once.

**Comment by scottfisk** [comment]
Looks like this feature may be coming to the jsonapi spec in 1.1:
http://jsonapi.org/about/#roadmap 
https://github.com/json-api/json-api/issues/795

**Comment by morenoh149** [comment]
ah so it's not in the spec yet. So perhaps we should wait until supporting it in DRFJA.

**Comment by morenoh149** [comment]
But while I have your ear if anyone could enlighten me over at https://github.com/json-api/json-api/issues/795#issuecomment-224625507 I'd appreciate it.

**Comment by BillBrower** [comment]
@morenoh149 Has any progress been made on this?

**Comment by morenoh149** [comment]
@BillBrower It's just beyond the scope of jsonapi v1. If you read the linked issue you'll see that they are planning it for v1.1 but there is no eta (I wouldn't wait for it, just build something that works for your situation).

**Comment by BillBrower** [comment]
Thanks @morenoh149!
