### ISSUE TITLE
Side Loading Without Include Parameter

### ISSUE THREAD

**Issue by lllama** [django-json-api/django-rest-framework-json-api#254]
Is it possible to have an example of how to sideload data without relying on the client to supply the `include` parameter? I have a `ModelViewSet` where I want to push some related data to the client but I can't find an easy way to do this.

**Comment by jerel** [comment]
Are you asking about a way to add data to `included` even if the query param `include` is not present or a way to add arbitrary data to the payload (this isn't allowed by the spec). If it's the former check out https://github.com/django-json-api/django-rest-framework-json-api/pull/250

**Comment by lllama** [comment]
Yep - it's the former. I'd like to get things into the `included` part of the response. Apologies for the issue noise - I didn't think to look in the pull requests.
