### ISSUE TITLE
Django 1.10rc1 'ForeignKey' object has not attribute 'related'

### ISSUE THREAD

**Issue by tomtom5152** [django-json-api/django-rest-framework-json-api#262]
When attempting to use the json_api renderer with Django 1.10rc1 I'm getting a strange error about field.related not being set. It appears this was a private attribute that was deprecated in 1.8 and has [finally been removed](https://docs.djangoproject.com/en/dev/releases/1.10/#features-removed-in-1-10).

Partial trace
```python
lib/python3.5/site-packages/rest_framework_json_api/utils.py", line 194, in get_related_resource_type
    relation_model = parent_model_relation.field.related.model
AttributeError: 'ForeignKey' object has no attribute 'related'
```

**Comment by jerel** [comment]
When is this error happening? I don't have enough information to recreate it.

Bonus points if you can write a failing test for it (we're now testing against Django 1.10 since it's been released)

**Comment by raphdg** [comment]
Here's some more info about this, I've encountered the same issue when serializing results from a model with a ManyToMany relationship.

```
  File "./env/lib/python2.7/site-packages/rest_framework_json_api/utils.py", line 194, in get_related_resource_type
    relation_model = parent_model_relation.field.related.model
AttributeError: 'ManyToManyField' object has no attribute 'related'
```

I was using Django 1.10.
Reverting Django to the 1.9, I got this deprecation warning

```
./env/lib/python2.7/site-packages/rest_framework_json_api/utils.py:194: RemovedInDjango110Warning: Usage of field.related has been deprecated. Use field.remote_field instead.
  relation_model = parent_model_relation.field.related.model
```

**Comment by jgoclawski** [comment]
Wasn't this fixed in #248 and already merged into master? I guess we need a PyPI release :)

**Comment by tomtom5152** [comment]
Having just checked the repo out at HEAD I can confirm that it is fixed for me at least, as for a PyPi release, that would be much appreciated

**Comment by jerel** [comment]
Thanks for confirming. We'll try to get 2.1.0 out shortly
