### ISSUE TITLE
OneToOneFields not serializing

### ISSUE THREAD

**Issue by lllama** [django-json-api/django-rest-framework-json-api#263]
I've changed my model to use a OneToOneField instead of a ForeignKey and the relationship is no longer serializing. If I switch back to a ForeignKey with unique=True then the relation is serialized but I have warnings in the Django console about OneToOneFields being a better option.

Is there a recommended way to serialize OneToOne relationships?

**Comment by alexahn** [comment]
I'm also witnessing strange behavior with OneToOneFields. Most notably, that I cannot change the name of the field without breaking the `included_serializers` functionality for the OneToOneField.

**Comment by jerel** [comment]
Do you think you could isolate this issue further? We do have a OneToOne field in our example app / tests so it seems like we'd have found the issue if it didn't work at all.

**Comment by jerel** [comment]
I'm going to close this until we have more information.

A PR with the behavior demonstrated in a test would be ideal, but not required.

**Comment by mapeveri** [comment]
I have the same problem. Any solution?.

Thanks!

**Comment by mapeveri** [comment]
My solution: Use this field SerializerMethodResourceRelatedField
