### ISSUE TITLE
Rename package

### ISSUE THREAD

**Issue by gaker** [django-json-api/django-rest-framework-json-api#27]
We made a mistake when initially naming this package with making it so EmberJS-centric.  

With a 2.0 release, let's include what is currently in master, plus renaming.  To maintain backwards compatibility and make things not too difficult, we can do a 1.6 release with what is in master as well.

Package naming suggestions, as well as thoughts/concerns are appreciated.

**Comment by erichonkanen** [comment]
hey @gaker, are you renaming the package or the repo name?

 It seems that a lot of rest framework packages follow something like "djangorestframework-PACKAGE"

Another one I use is https://github.com/GetBlimp/django-rest-framework-jwt

Some others:
OAuth - djangorestframework-oauth
XML - djangorestframework-xml
YAML - djangorestframework-yaml
JSONP - djangorestframework-jsonp

djangorestframework-emberdata or some variant seems logical

**Comment by jerel** [comment]
I vote for `django_json_api` as the package/repo name. I started hacking on a branch over here https://github.com/django-json-api/rest_framework_ember/commits/json-api but it can be changed. My reasoning for not including "Django REST Framework" in the name is just due to length

**Comment by erichonkanen** [comment]
I see.. I think the question is how tightly coupled is the package to drf and ember/data? It seems very tightly coupled especially to drf so it might make sense to do something like:

repo: github.com/django-json-api/django-rest-framework-json-api

package: rest_framework_jsonapi

(This made me think that it would be nice if there was a bucket github org for all rest framework packages/contributors)

**Comment by jerel** [comment]
This package wouldn't exist without DRF so I guess we could say it's tightly coupled ;) It's not impossible that Tom will add Flask support sometime in the future (I've seen it mentioned as "nothing technical prevents it but it's not planned").

This package isn't really tied to Ember Data: Ember Data is moving toward using the [jsonapi.org](jsonapi.org) spec as the default adapter so if we implement the spec it should Just Work™. The organizers of json-api were at EmberConf last week and mentioned a 1.0 release on Friday (they didn't quite make it obviously but it's very close to final).

**Comment by erichonkanen** [comment]
ah yes, after I posted that I wondered if ember was moving to jsonapi... 

what about django-rest-framework-json/rest_framework_json ?

whatever works!

ps how was ember conf? wanted to go but was sold out :/

**Comment by jerel** [comment]
I like that naming scheme as the repo matches the rest of DRF's packages pretty well and imports would be easy to remember: `rest_framework.renderer` vs `rest_framework_json.renderer`. It is a long repo name but that probably doesn't matter...

@erichonkanen EmberConf was awesome. Here's the playlist of talks if you haven't seen them already: https://www.youtube.com/watch?v=o12-90Dm-Qs&list=PLE7tQUdRKcyacwiUPs0CjPYt6tJub4xXU

**Comment by erichonkanen** [comment]
sweet! checking that out.. yeah the other drf/ember repo I use has same naming:

```
'rest_framework_jwt.authentication'
```
etc etc

**Comment by erichonkanen** [comment]
hey hey, any idea when a new tag will be cut with this? currently I still have to use specific egg in requirements... 

also, if there is any more work to be done on this lib or another one I'm looking for more open source work! cheers

**Comment by jerel** [comment]
I'm starting a new (long term) project tomorrow that will use this package
so I plan to be using it heavily in the near future.

One of the first things (if you want to look into it) is getting tests
passing with the latest DRF.

**Comment by erichonkanen** [comment]
cool cool, I'll submit a pr with tox for testing and test with latest sometime later this week

**Comment by gaker** [comment]
Thanks Eric!

**Comment by erichonkanen** [comment]
@jerel did you have any consensus on naming of this package?

I propose:

folder/url: /django-rest-framework-json-api/

setup.py name (e.g. pip install ___ ): djangorestframework-jsonapi

package name: rest_framework_jsonapi

let me know your thoughts.. Im starting a new branch to update testing and possibly cleanup some of the docs

**Comment by jerel** [comment]
This looks pretty good. My only worry is the perceived inconsistency in underscoring `rest_framework` but not `jsonapi`. Would it make sense to either drop "api" or underscore `json_api`?
Looks like the camel case package does it like this https://github.com/vbabiy/djangorestframework-camel-case
</ bikeshed>

What are your thoughts @gaker?

**Comment by erichonkanen** [comment]
I think `rest_framework_json_api` is fine too since the package is all about adapting to the json api spec

**Comment by erichonkanen** [comment]
@jerel I made some initial updates to setup.py and package naming, going to go through it more thoroughly and read more of the json-api spec this weekend...

Regarding the mixin for handling the []'s in url, is that ember specific or something json-api specific? just wondering bc it's useful but if not part of json-api maybe it shouldn't be included?

**Comment by jerel** [comment]
The multiple ID mixin was written with Ember in mind. I can't remember off the top of my head of the JSON API spec uses multiple IDs or not. I'd like to leave it in regardless since it's just a mixin that can be ignored if it's not being used.
