### ISSUE TITLE
Incorrect resource type on inverse proxy models?

### ISSUE THREAD

**Issue by dolgafar** [django-json-api/django-rest-framework-json-api#285]
Hello,

I've used the proxy model approach as suggested in #166, this works nicely and you can even assign different permissions to resources based on this in Django.

But when I use the inverse relation (related_name), the resource name is taken from the "base model" and not the proxy model. Normally it would use the JSONAPI meta on the proxy model, but this can't be used in this case.

Does it make sense? :) I should say, I'm quite new to drf json-api, but it rocks really well with Ember.

I've removed the inverse relation field for now, because it confuses Ember data, but I loose a lot of finesse and included data option.

Could it be possible to set resource_name manually on the ResourceRelatedField ? Or is there some other smart way I haven't figured out?

Thanks a lot for a great package...

**Comment by sliverc** [comment]
I think #306 addresses your issue where `resource_name` can be configured on an serializer resp. also `included_serializers` for relations. Closing this issue but please comment if this doesn't fix your issue.
