### ISSUE TITLE
Only class based views supported for resource_names

### ISSUE THREAD

**Issue by lllama** [django-json-api/django-rest-framework-json-api#293]
In particular, when trying to determine a resource type, all of the checks performed assume an instance of a view class, and so will end up returning a view function's name as a last resort.

**Comment by lllama** [comment]
For anyone else running into this, I solved my issue by using this decorator. (You could just set `resource_name` as my_api_func.view_class.resource_name = "Whatever". Pick whichever you like the look of)
```
def add_resource_name(resource_name):
    def wrap(f):
        f.view_class.resource_name = resource_name
        return f
    return wrap
```

**Comment by sliverc** [comment]
Closing this issue as there is a workaround. Another solution would be to define the resource_name on the serializer.

**Comment by lllama** [comment]
Pretty sure that setting on the serializer will not work, as the view's function name will trump it. The decorator is the only reliable method I've found so far. Just FYI.
