### ISSUE TITLE
resource id field should be based on serializer lookup_field

### ISSUE THREAD

**Issue by AndreiHondrari** [django-json-api/django-rest-framework-json-api#295]
Currently if you have a lookup_field on serializers that is different from the 'pk', you will be able to do `/api/objects/{new_lookup_field}' but in the payload the "id" will still be the numerical one that django uses by default. This goes for GET and PATCH. I think this is an inconsistency.

**Comment by AndreiHondrari** [comment]
I started implementing something like this over [here](https://github.com/django-json-api/django-rest-framework-json-api/compare/develop...AndreiHondrari:id_replace_by_lookup_field)

**Comment by sliverc** [comment]
I think #155 also addresses this issue and there is an open PR #409 

Closing this issue to focus on #155 If you think this is a different issue though please comment.
