### ISSUE TITLE
When side-loading data, renderer checks the model instance for the field name first, instead of the serirializer

### ISSUE THREAD

**Issue by chrisclark** [django-json-api/django-rest-framework-json-api#301]
Let's say I have code like this (a little contrived, but simple):

``` python
# Models

class LineItem(models.Model):
    product = models.CharField(max_length=256)
    charged = models.BooleanField(default=False)


class Order(models.Model):
    items = models.ManyToManyField(LineItem)

    @property
    def charged_items(self):
        return self.items.filter(charged=True)

# Serializers

class LineItemRelatedField(ManyRelatedField):
    model = LineItem

class OrderSerializer(HyperlinkedModelSerializer):

    items = LineItemRelatedField(
        child_relation=ResourceRelatedField(
            related_link_view_name='order-items',
            related_link_url_kwarg='order_pk',
            self_link_view_name='order-relationships',
            read_only=True,
        ),
        source='charged_items'
    )

    included_serializers = {
        'items': 'serializers.LineItemSerializer',
    }
```

Let's say I now request /api/orders/?include=items

The expected behavior would be for the items collection, as specified on the OrderSerializer (namely, only the charged_items) to be included. However instead, because of:

https://github.com/django-json-api/django-rest-framework-json-api/blob/develop/rest_framework_json_api/renderers.py#L276

The Order model instance is checked instead and order.items() is used as the source for the included data. This causes the side-loaded data to not match the returned relationship data on the primary object.

The order of the checks in the referenced code should be changed to examine the Serializer first, then the model instance.

**Comment by sliverc** [comment]
Changing the order is kind of critical as it is not backwards compatible and the error might then just occur the other way around when `charged_items` and `items` are defined on the serializer.

I think the better way is instead of using a property `charged_items` on the model to use `SerializerMethodResourceRelatedField` on the serializer to define `charged_items`.

This issue is fairly old so I am closing hoping that this helps. Otherwise please comment.
