### ISSUE TITLE
Error raised when sending OPTIONS request to relationship view

### ISSUE THREAD

**Issue by valerymelou** [django-json-api/django-rest-framework-json-api#315]
Hi.
I'm trying to send an OPTIONS request to a relationship view and the server raises a `RuntimeError` saying `ResourceIdentifierObjectsSerializer must be initialized with a model class`. I took a look in the code and I don't see how `RelationshipView` may specify the model class explicitly or implicitly. I don't have too much experience with the package itself so could someone please take a look at this?

**Comment by n2ygk** [comment]
See [the declaration of ResourceIdentifierObjectSerializer](https://github.com/django-json-api/django-rest-framework-json-api/blob/master/rest_framework_json_api/serializers.py#L30-L34) where it looks like the `model_class` and `instance` have to be provided as an optional argument. In the debugger, neither is set. I'm not quite sure where that is supposed to happen. Will try to find it.

**Comment by n2ygk** [comment]
I added a serializer_class and this appears to have fixed it:
```python
class WidgetRelationshipView(RelationshipView):
    queryset = Widget.objects
    serializer_class = WidgetSerializer # <<<--- add this
    self_link_view_name = 'widget-relationships'
```

**Comment by n2ygk** [comment]
But the response for coreapi and swagger are both based on application/json and not application/vnd.api+json so it's the coreapi schema, not jsonapi's.
