### ISSUE TITLE
include usage

### ISSUE THREAD

**Issue by morenoh149** [django-json-api/django-rest-framework-json-api#318]
I'm having difficulty understanding how to use `?include=...`. Say I have drfja properly installed, do you simply write your viewset code and `include` query params are available?

Or do you have to manually call http://django-rest-framework-json-api.readthedocs.io/en/stable/api.html?highlight=include#extract-included I'm confused.

**Comment by abdulhaq-e** [comment]
Hello, there is nothing special about views, it's the serialiser that you must customise:

To allow querying with `?include=profile`:
```python
class UserSerialiser(serializers.ModelSerializer):

    included_serializers = {
        'profile': 'Gienah.administration.serialisers.FacultySerialiser',
    }

    class Meta:
        model = User
        fields = ('name', 'profile')
```

To include `profile` by default:

```python
class UserSerialiser(serializers.ModelSerializer):

    included_serializers = {
        'profile': 'Gienah.administration.serialisers.FacultySerialiser',
    }

    class Meta:
        model = User
        fields = ('name', 'profile')

    class JSONAPIMeta:
        included_resources = ['profile']
```

**Comment by morenoh149** [comment]
okay. Say I have a viewset and a serializer. The viewset has a method `activity`. I attempted `/resource/:id/activity?include=foo` and did not receive the related foo.

```python
#  views.py
class ResourceViewSet():
  def activity():
    return rest_framework.response.Response(...)
```

```python
# serializers.py
class ResourceHyperlinkedSerializer():
  included_serializers = {
    'foo': '...'
  }
  class Meta:
    model = Resource
    fields = ('foo')
```

**Comment by sliverc** [comment]
I think to be able to assist you better could you expand on how your `ResourceViewSet` looks like?

Maybe create a gist with the full implementation of the view if possible. Most likely the problem is hidden there somewhere...
