### ISSUE TITLE
Add support for cursor based pagination

### ISSUE THREAD

**Issue by hoIIer** [django-json-api/django-rest-framework-json-api#320]
After lots of head scratching we just determined that our test was failing because it has cursor pagination enabled, does this package support it or what would be needed to make it work?

```
class FooViewSet(viewsets.ModelViewSet):
    serializer_class = serializers.FooSerializer
    pagination_class = FooCursorPagination

    def get_queryset(self):
        qs = models.Foo.objects.all()
        return qs
```

**Comment by sliverc** [comment]
Marking as help wanted if someone wants to pick up the PR. As a side node `renderer_context` won't fail anymore when it is `None` - this has been fixed with #396
