### ISSUE TITLE
ResourceRelatedMethodField which is rendered to relationships and works like SerializerMethodField

### ISSUE THREAD

**Issue by xssChauhan** [django-json-api/django-rest-framework-json-api#327]
I've run into a need where i need to use `SerializerMethodField` but need to render it into `relationships` finally.
Right now, I'm using a hook in the `JSONRenderer` to move the field into `relationships` from `attributes`.
The framework accepts all other relation types as attributes  [except these](https://github.com/django-json-api/django-rest-framework-json-api/blob/develop/rest_framework_json_api/renderers.py#L52)

`ResourceRelatedField` is too restrictive as it does not allow me to modify the retrieval process.

A way to be able to to this is a `SerializerMethodField` like way to fetch data , and then render it as relationship.

A `ResourceRelatedMethodField` would be a nice solution.

**Comment by vivekbhagwat** [comment]
@xssChauhan is `SerializerMethodResourceRelatedField` what you're looking for? 

https://github.com/django-json-api/django-rest-framework-json-api/blob/master/example/serializers.py#L46

**Comment by xssChauhan** [comment]
@vivekbhagwat Yes, this is it. Thanks. Closing this issue.
