### ISSUE TITLE
SerializerMethodField data not rendered as json-api

### ISSUE THREAD

**Issue by xssChauhan** [django-json-api/django-rest-framework-json-api#328]
Any data emanating from  a `SerializerMethodField` is not rendered using JSONAPI specification.
It is rendered just as it was fetched from the method.

**Comment by sliverc** [comment]
Can you give a code sample reproducing this?

I have used `SerializerMethodField` many times and have never encountered this issue.

**Comment by sliverc** [comment]
As there hasn't been any feedback closing this issue. In case issue still exists please comment with necessary details and we can reopen this issue again.
