### ISSUE TITLE
specify included resources upon serialization

### ISSUE THREAD

**Issue by gregorypease280** [django-json-api/django-rest-framework-json-api#331]
Hi, I was wondering if there was a way to do something like 

`PersonSerializer(person_object, included_resources=['career']).data`?
I'm not exactly sure how I can specify included fields during serialization without declaring them in the url (my project uses serializers for things other than web pages)

Thanks!

**Comment by mblayman** [comment]
@gregorypease280 Does this documentation help? http://django-rest-framework-json-api.readthedocs.io/en/latest/usage.html#included

It shows how to use included resources with serializers. I would guess (but haven't tested to confirm) that if you set up your serializers using that feature, the resulting data would include the expected content.

**Comment by sliverc** [comment]
As above mentioned you have to define it in the serializer as json api meta:
``` 
    class JSONAPIMeta:
        included_resources = ['career']
```
Closing this issue. If there are still questions concerning this feel free to comment.
