### ISSUE TITLE
Redesign auto prefetching

### ISSUE THREAD

**Issue by bor3ham** [django-json-api/django-rest-framework-json-api#334]
It would be good if related models are only queried from the database as they are asked for, for example a query to `/entries?include=author` automatically does a `.select_related('author')` whereas the base viewset queryset does not

I have tried to address this with the `ModelViewSet` in `rest_framework_json_api/views.py`, but it still has issues:

- It assumes the `include` param names match the `model` names - not always the case as the `include` param names align to the `serializer` fields
- Foreign keys are fine, but m2m / reverse foreign key sets will still require another db query to get the id's so would ideally be prefetched
- There are probably another tonne of assumptions around my individual use case I haven't realised yet

A better solution would be aware of the serializer, but still respect DRF's abstraction layers (rather than just touching everything at once). Any ideas?

**Comment by aidanlister** [comment]
@mblayman we can close this one in lieu of the other PRs (it's also  Uptick)

**Comment by mblayman** [comment]
I agree. If there are other aspects that the PRs don't cover, we can open a similar issue focusing on those details.
