### ISSUE TITLE
unexpected resource type for models with self-join

### ISSUE THREAD

**Issue by dbinetti** [django-json-api/django-rest-framework-json-api#335]

**Comment by dbinetti** [comment]
I have a model that encompasses a large hierarchy (set up as a self-join with the standard parent/children FKs).  Then, I've set up different serializers to reflect different subsets of that main model (based on a `level` field.).  Each individual serializer works fine except that the type of the model returned by the `relationships` field reflects the overarching model as opposed to the `resource_name` specified (either in view or serializer).


To explain more fully:

Assume a single model called "Entity", with the following basic structure:

```
name = CharField()
kind = CharField(choices...)
parent = models.ForeignKey(
    'self',
    null=True,
    related_name='children',
)
```

For the `kind` field, assume it follows a geographical hierarchy such as "Country", "State", "City".  Thus, an `entity` instance could be named "USA", and have children named "California", "Nevada", etc,, and then the `entity` instance named "California" would have a parent of "USA" and children including "San Francisco", "Los Angeles", etc.   

For my purposes, I'm trying to expose endpoints that correspond to the various kinds `api/countries`, `api/states` etc., and have set up the filtered ModelViewSets and Serializers accordingly, with the specified `resource_name` on each serializer to reflect the proper type. 

The renderer will return the instance with the correct resource name as specified, if requesting through `api/state` then the instance type will be "state".  However, the relationship instances' types are called by the master model (in my example, "Entity").  This is causing problems for my clients, since they don't know what the Entity is -- I'm hoping to have that simply be an internal reference.  

I've tried to dig into the code to see how the type is set, but it is referred to in so many places that I"m getting lost. So my questions are:

- Is it reasonable that you could refer to different parent/child types in this way?  
- What is the proper way to ensure the type is specified to my needs, particularly since the parent/child relationship types rely more on the "Kind" of the individual instance rather than the instance type itself.  


THnaks

**Comment by sliverc** [comment]
When I understand your problem correctly I think this should be possible with assigning `resource_name`.

See https://django-rest-framework-json-api.readthedocs.io/en/stable/usage.html?highlight=included_serializers#included 

Documentation is unfortunately not very clear on relationships (needs to be improved) but what you need to do is define [included_serializers](https://django-rest-framework-json-api.readthedocs.io/en/stable/usage.html?highlight=included_serializers#included) of all relationships with different resource name. This way relationships will be assigned to correct resource name as well.

Does this help?

**Comment by sliverc** [comment]
I assume above comment has helped. Closing this ticket therefore. If there are still questions please feel free to comment.
