### ISSUE TITLE
Release 2.2?

### ISSUE THREAD

**Issue by mblayman** [django-json-api/django-rest-framework-json-api#338]
Hi, @jerel! I was looking at the commit history this morning and it looks like it's been about 6 or 7 months since the last release and there is a lot of changes that have happened that aren't out in the wild on PyPI.

Would it be possible to cut a new release soon? I'd be happy to learn how you release stuff if you'd like me to do some releases in the future.

**Comment by jerel** [comment]
Yes, I'll try to do this before the week's end.

**Comment by mblayman** [comment]
That sounds great. Perhaps the release process could be documented so that another maintainer could release when you're swamped. Thoughts?

**Comment by jerel** [comment]
Ok, v2.2.0 is out. I did overlook something before tagging, the changelog. Looks like CHANGELOG.md hasn't been updated since 2.1.1, would you want to update it or shall I do it based on the git log?

**Comment by mblayman** [comment]
Looks like my compatibility update didn't make it into the release. I added a brief changelog for that one. Maybe you could merge PR #341 and sprinkle in some stuff from the git log, then cut a release for 2.2.1. I'd take a crack at the changelog, but a majority of the items happened before I took on any maintainership role.

Would that work?
