### ISSUE TITLE
Better error handling

### ISSUE THREAD

**Issue by erichonkanen** [django-json-api/django-rest-framework-json-api#34]
Hey,

So recently I started looking at improving error handling in a project that uses this and I realized that currently if I do e.g. `raise BadRequest('You've got an error')`, the response might look like:
```
{
    'someResourceName': {
        'detail': 'You've got an error'
    }
}
```
when in fact what I want is:
```
{
    'error': {
        'message': 'You've got an error'
    }
}
```
So the second part is easily changed by implementing a custom exception handler but the first part which is important because I want to implement consistent error responses site-wide, is not so intuitive to solve.

Do you guys have any ideas on how we can override the resource name automatically to handle error responses?

The only other way so far I know to do it is to manually add `self.resource_name = 'error'` before raising an error, but that seems like an ugly thing to have to add in my code.

Will keep looking into it...

Cheers,
-Eric

**Comment by jerel** [comment]
Hey @erichonkanen, that's a good question and it's one we need to solve for the JSON API spec. Would it be reasonable to change the output automatically in the renderer based on the HTTP status code? If the status code is >= 400 then the result becomes:

    {
        'errors': [
            {
                'detail': "First Name must be shorter than 100 characters",
                'source': {
                    'parameter': 'first-name',
                },
            },
            {
                'detail': "Last Name may not be blank",
                'source': {
                    'parameter': 'last-name',
                },
            }
        ]
    }

The [spec states](http://jsonapi.org/format/#document-top-level) that `data` and `errors` **MUST NOT** coexist in the same response so from that angle it seems safe.

**Comment by erichonkanen** [comment]
Hey @jerel, that seems like a reasonable approach...  If it's status 200 etc then return the default response with resource name wrapping it. If its a 400 or 500 etc then return something like what you pasted above..  at first I was thinking of implementing some type of decorator for the CBV mixins to catch errors but if we can handle it in this repo that'd be great!

**Comment by erichonkanen** [comment]
@jerel so are we just leaving error handling out for now until a large refactor is done? the PR had a way to check for error and return proper error object

**Comment by jerel** [comment]
I feel like this is best handled by 2.0 via the JSON API spec. Current plan is to merge 6674473 to the develop branch
