### ISSUE TITLE
Passing extra arguments to included serializers

### ISSUE THREAD

**Issue by aidanlister** [django-json-api/django-rest-framework-json-api#343]
It would be cool to have something like this:

```
    included_serializers = {
        'assigned_to': 'abas.apps.accounts.api.serializers.UserSerializer',
        'assigned_office': 'abas.apps.accounts.api.serializers.UserSerializer',
        'technician': 'abas.apps.accounts.api.serializers.UserSerializer',
        'round': 'abas.apps.tasks.api.serializers.RoundSerializer',
        'client': 'abas.apps.clients.api.v2.serializers.ClientSerializer',
        'property': 'abas.apps.properties.api.v2.serializers.PropertySerializer',
        'billingcard': 'abas.apps.billing.api.serializers.BillingCardSerializer',
        'category': 'abas.apps.tasks.api.v2.serializers.TaskCategorySerializer',
        'tags': 'abas.apps.tasks.api.serializers.TaskTagSerializer',
        'job': 'abas.apps.jobs.api.v2.serializers.JobSerializer',
        'branch': 'abas.apps.branches.api.v2.serializers.BranchSerializer',
    }

    serializer_kwargs = {
          'branch': { excluded_fields = ('round', 'task', ) }
    }
```

e.g. being able to dynamically modify the behaviour of serializers based on where it's being included from means we can leave off relations that don't make sense in the context, which would be a big performance improvement.

If not possible, would this be something you'd support via a PR?

**Comment by tpilara** [comment]
@aidanlister Check out [sparse fieldsets](http://jsonapi.org/format/#fetching-sparse-fieldsets) and see if this might accomplish what you're looking for. I know this package does support sparse fieldsets although I don't think I've ever tried to use them across an include. Definitely worth checking out though.

It does differ slightly from what you've proposed as you must specify the query params for each request on which you want to get a subset of fields returned, even if that happens to be every time you include that related resource. Also they work the inverse of what you've proposed where you need to specify the fields you want to be included as opposed to the ones you want excluded, so depending on how many fields are on the serializer it can result in a lengthy query string.

**Comment by mblayman** [comment]
I like this idea. Having finer grain control over a serializer seems like it could add some nice flexibility.

I'd certainly support a PR that makes it happen.

**Comment by aidanlister** [comment]
Sparse fieldsets looks like an easy solution for my immediate problem, and we'll get a PR in for the factory method.
