### ISSUE TITLE
Demo site 500 

### ISSUE THREAD

**Issue by elena** [django-json-api/django-rest-framework-json-api#356]
Following links on demo site return Server Error 500:
[http://json-api.jerel.co/](http://json-api.jerel.co/)

```
       "blogs": "http://json-api.jerel.co/blogs",
       "entries": "http://json-api.jerel.co/entries",

```

Note other links work:
```
        "authors": "http://json-api.jerel.co/authors",
        "comments": "http://json-api.jerel.co/comments"

```
Cheers.

**Comment by mblayman** [comment]
Thanks, @elena. I believe this runs on the personal website of @jerel. If I had to venture a guess, the site is probably missing some database migrations that were recently added the demo project.

**Comment by jerel** [comment]
It's running on a private server. I'll try to take a look, probably an
issue with the reset script or migrations

On Jun 10, 2017 7:32 PM, "Matt Layman" <notifications@github.com> wrote:

Thanks, @elena <https://github.com/elena>. I believe this runs on the
personal website of @jerel <https://github.com/jerel>. If I had to venture
a guess, the site is probably missing some database migrations that were
recently added the demo project.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/django-json-api/django-rest-framework-json-api/issues/356#issuecomment-307598252>,
or mute the thread

**Comment by jerel** [comment]
So, it's throwing `ImportError: No module named polymorphic`. Merely installing `django-polymorphic` doesn't fix it. Evidently there's a package missing from the requirements file. But does, or should, the demo even use polymorphism out of the box?

**Comment by mblayman** [comment]
@jerel, I believe that the polymorphic branch that was merged *did* update the demo project to use polymorphic models in some locations. I'm surprised (saddened?) that installing `django-polymorphic` doesn't solve the problem.

Do you have any details on what it is reporting after you install `django-polymorphic`? Did you get past the `ImportError`?

**Comment by jerel** [comment]
So, I've worked with this a bit and found the demo hadn't applied migrations correctly. The `/blogs` endpoint is working fine but `/entries` is throwing `Could not resolve URL for hyperlinked relationship using view name "entry-relationships".`

I'm out of time for the moment but hopefully that gets somebody else pointed in the right direction. You can replicate by checking out the `develop` branch and running `django-admin.py runserver --settings=example.settings`

**Comment by mblayman** [comment]
@leo-naeka or @astronouth7303, something is wrong with the demo site and I'm guessing it's related to the polymorphic changes. Could one of you take a quick look and see if you could figure out the problem? I'd hope to see the demo site working again before a release goes out.

**Comment by astronouth7303** [comment]
I have found a few bugs:

1. The example now requires `packaging` (`example/serializers.py`). I'm guessing this is the actual cause of the bug.
2. `/entries` produces `ImproperlyConfigured at /entries`: `Could not resolve URL for hyperlinked relationship using view name "entry-relationships".`
3. `/projects` produces `AttributeError at /projects`: `'list' object has no attribute '_meta'`

**Comment by astronouth7303** [comment]
From @leo-naeka:

> Actually the `ImproperlyConfigured at /entries: Could not resolve URL for hyperlinked relationship using view name "entry-relationships".` bug was introduced before the polymorphic feature merge: occurs in 629d1d6.
