### ISSUE TITLE
Can't get a proper JSON API 'relationships' part in the generated responses

### ISSUE THREAD

**Issue by rodolfojcj** [django-json-api/django-rest-framework-json-api#363]
I'm using Django + Django REST Framework + Djoser with success. Now I want to switch to generate JSON API compatible responses, which is blocking me a little. I'm trying to use django-rest-framework-json-api to ease my work, as described at http://django-rest-framework-json-api.readthedocs.io/en/stable/usage.html

The problem I'm facing is that I can't get the **"relationships"** part in in the generated JSON output, as illustrated with the following sample.

Any help with that?

Thanks!

##### a) for user type

    {
        'data': {
            'id': '1',
            'attributes': {
                'date-joined': '2017-07-18T23:05:54.713532Z',
                'email': 'jdoe@acme.com'
            },
            'type': 'users'
        }
    }

#### b) for user profile type

    {
        'data': {
            'id': '1',
            'attributes': {
                'last-name': 'Doe',
                'first-name': 'John'
            },
            'type': 'userProfiles'
        }
    }

#### a) for user type

    {
        'data': {
            'id': '1',
            'attributes': {
                'date-joined': '2017-07-18T23:05:54.713532Z',
                'email': 'jdoe@acme.com'
            },
            'relationships': {
                'profile': {
                    'links': {
                        'related': 'http://localhost:8000/profile/'
                    }
                }
            }
            'type': 'users'
        }
    }

#### b) for user profile type

    It's ok as generated, then there is no problem here.

#### demo.users models.py

    from django.db import models
    from django.contrib.auth.models import (
        BaseUserManager, AbstractBaseUser
    )
    from django.contrib.auth import get_user_model
    from django.utils import timezone
    from django.utils.translation import ugettext_lazy as _
    
    
    class UserManager(BaseUserManager):
        """Custom manager for our User model, created we have a different sef of
        fields that those defined by Django's default UserManager class."""
    
        def create_user(self, email, password=None):
            if not email:
                raise ValueError('Users must have an email address')
    
            user = self.model(
                email=self.normalize_email(email)
            )
            user.set_password(password)
            user.save(using=self._db)
            return user

    class User(AbstractBaseUser):
        """Custom User model created because we want the email address to be the
        field used to uniquely identify each registered user, like a customer or
        a staff person."""

        email = models.EmailField(_('email address'), unique=True)
        is_active = models.BooleanField(default=False)
        date_joined = models.DateTimeField(_("date joined"), default=timezone.now)

        objects = UserManager()

        USERNAME_FIELD = 'email'

        class Meta:
            verbose_name = _('demo user')
            verbose_name_plural = _('demo users')
            db_table = 'demo_user'

    class UserProfile(models.Model):
        """
        User profile associated to a user model
        """

        user = models.OneToOneField(
            get_user_model(),
            on_delete=models.CASCADE,
            primary_key=True,
            related_name='profile',
        )

        first_name = models.CharField(_('first name'), max_length=25)
        last_name = models.CharField(_('last name'), max_length=25)

        class Meta:
            verbose_name = _('demo user profile')
            verbose_name_plural = _('demo users profiles')
            db_table = 'demo_user_profile'

#### demo.api serializers.py
    
    #
    # I tried several variations, but I'm leaving the simplest starting point here
    #
    
    from rest_framework_json_api import serializers
    
    from django.contrib.auth import get_user_model
    
    from demo.users.models import UserProfile
    
    
    User = get_user_model()
    
    
    class UserSerializer(serializers.ModelSerializer):
    
        class Meta:
            model = User
            fields = tuple(User.REQUIRED_FIELDS) + (
                User._meta.pk.name,
                User.USERNAME_FIELD,
                'date_joined',
                'profile',
            )
            read_only_fields = (
                User.USERNAME_FIELD,
                'date_joined',
            )
    
    
    class UserProfileSerializer(serializers.ModelSerializer):
        class Meta:
            model = UserProfile
            fields = ('first_name', 'last_name')
    
    
#### demo.api views.py
    
    from django.shortcuts import get_object_or_404
    
    from rest_framework import generics, permissions
    
    from demo.users.models import UserProfile
    
    from .serializers import UserProfileSerializer
    
    
    class UserProfileView(generics.RetrieveAPIView):
        """
        Use this endpoint to retrieve a user profile
        """
        serializer_class = UserProfileSerializer
        permission_classes = (
            permissions.IsAuthenticated,
        )
    
        def get_object(self, *args, **kwargs):
            """
            Custom get_object implementation, overriding the one provided by
            GenericAPIView, because we specifically need the user profile
            belonging to the current authenticated user. Note that this way
            we are not using the queryset and lookup_field attributes of
            the view
            """
            return get_object_or_404(UserProfile, user=self.request.user)
    
    
#### project urls.py
    
    from django.conf.urls import url
    from django.contrib import admin
    
    from djoser import views as djoser_views
    
    from demo.api import views as demo_views
    
    
    urlpatterns = [
        url(r'^admin/', admin.site.urls),
        url(r'^join/$', djoser_views.RegistrationView.as_view(),
            name='register'),
        url(r'^activate/$', djoser_views.ActivationView.as_view(),
            name='activate'),
        url(r'^login/$', djoser_views.LoginView.as_view(),
            name='login'),
        url(r'^logout/$', djoser_views.LogoutView.as_view(),
            name='logout'),
        url(r'^me/$', djoser_views.UserView.as_view(), name='me'),
        #
        url(r'^profile/$', demo_views.UserProfileView.as_view(), name='profile'),
    ]

#### project settings.py
    
    INSTALLED_APPS = [
        'django.contrib.admin',
        'django.contrib.auth',
        'django.contrib.contenttypes',
        'django.contrib.sessions',
        'django.contrib.messages',
        'django.contrib.staticfiles',
        #
        'rest_framework',
        'rest_framework.authtoken',
        'djoser',
        #
        'demo.users',
        'demo.api',
    ]

    
    # REST Framework and Djoser authentication system
    
    REST_FRAMEWORK = {
        'DEFAULT_AUTHENTICATION_CLASSES': (
            'rest_framework.authentication.TokenAuthentication',
        ),
        'DEFAULT_RENDERER_CLASSES': (
            # 'rest_framework.renderers.JSONRenderer',
            'rest_framework_json_api.renderers.JSONRenderer',
        ),
        'DEFAULT_PARSER_CLASSES': (
            'rest_framework_json_api.parsers.JSONParser',
        ),
        'DEFAULT_METADATA_CLASS': 'rest_framework_json_api.metadata.JSONAPIMetadata',
    }

    DJOSER = {
        'PASSWORD_RESET_CONFIRM_URL': '#/password/reset/confirm/{uid}/{token}',
        'ACTIVATION_URL': '#/activate/{uid}/{token}',
        'SEND_ACTIVATION_EMAIL': True,
        'SEND_CONFIRMATION_EMAIL': True,
        'SERIALIZERS': {
            'user': 'demo.api.serializers.UserSerializer',
        }
    }

    JSON_API_FORMAT_KEYS = 'dasherize'
    JSON_API_FORMAT_TYPES = 'camelize'
    JSON_API_PLURALIZE_TYPES = True

**Comment by rodolfojcj** [comment]
Hi again.

I patiently reviewed again the situation I reported and found that it's not a bug of _django-json-api_. To get what I wanted I used the functionalities of this project, as well as a small customization.

There was a mistake in the sample code I had, because the User object I used for testing did not have its corresponding UserProfile object, being this the reason for not having the "_relationships_" part in in the generated JSON output.

I was very fortunate because someone very gently at the _#rest_framework_ IRC channel helped me to analyse the situation, providing me a [detailed good working and simple sample, which is available as a Gist](https://gist.github.com/freakabcd/9ec94d4fb9e285bc73d328a8a78cedba). The most interesting part of that sample output is this:

    "data": [
      {
        "type": "User",
        "id": "1",
        "attributes": {
          "email": "foo@example.com",
          "is_active": true
        },
        "relationships": {
          "profile": {
            "data": {
              "type": "UserProfile",
              "id": "1"
            }
          }
        }
      }
    ]

There we can see the _relationships_ key appearing, assuming the proper model records exist in the running project database.

After that, I iterated my own project, as follows.

### 1. Almost the starting point, that doesn't work as expected

#### serializers.py

    from rest_framework_json_api import serializers
   
    from django.contrib.auth import get_user_model
    
    from demo.users.models import UserProfile

    class UserSerializer(serializers.ModelSerializer):
    
        class Meta:
            model = get_user_model()
            fields = tuple(User.REQUIRED_FIELDS) + (
                User._meta.pk.name,
                User.USERNAME_FIELD,
                'joined_date',
            )
            read_only_fields = (
                User.USERNAME_FIELD,
                'joined_date',
            )
    
    
    class UserProfileSerializer(serializers.ModelSerializer):
        class Meta:
            model = UserProfile
            fields = ('first_name', 'last_name')

#### views.py

    from django.shortcuts import get_object_or_404
    from django.contrib.auth import get_user_model
    
    from rest_framework import generics, permissions
    
    from rest_framework_json_api import renderers as json_api_renderers
    
    from djoser import views as djoser_views
    
    from demo.users.models import UserProfile
    
    from .serializers import UserProfileSerializer, UserSerializer
    
    
    class UserProfileView(generics.RetrieveAPIView):
        """
        Use this endpoint to retrieve a user profile
        """
        serializer_class = UserProfileSerializer
        permission_classes = (
            permissions.IsAuthenticated,
        )
        renderer_classes = [
            json_api_renderers.JSONRenderer,
        ]
    
        def get_object(self, *args, **kwargs):
            """
            Custom get_object implementation, overriding the one provided by
            GenericAPIView, because we specifically need the user profile
            belonging to the current authenticated user. Note that this way
            we are not using the queryset and lookup_field attributes of
            the view
            """
            return get_object_or_404(UserProfile, user=self.request.user)
    
    
    class UserView(djoser_views.UserView):
        """
        API View to get a user account object
        """
        renderer_classes = [
            json_api_renderers.JSONRenderer,
        ]
        queryset = get_user_model().objects.all()
        # explicit serializer_class seems not to be extrictly needed, probably
        # because it's taken from the 'user' entry of the 'SERIALIZERS' key of
        # the 'DJOSER' configuration declared in the project settings file
        # serializer_class = UserSerializer

#### Generated output

##### For the _user_ endpoint

    curl -X GET http://localhost:8000/me/ -H 'Authorization: Token e62a064539e728ab7c5d8787f05df0c43db3c9b5'

    {
      "data": {
        "type": "users",
        "id": "1",
        "attributes": {
          "email": "a@a.com",
          "joined-date": "2017-07-18T14:10:51.753913Z"
        }
      }
    }

##### For the _user profile_ endpoint

    curl -X GET http://localhost:8000/profile/ -H 'Authorization: Token e62a064539e728ab7c5d8787f05df0c43db3c9b5'

    {
      "data": {
        "type": "userProfiles",
        "id": "1",
        "attributes": {
          "first-name": "John",
          "last-name": "Doe"
        }
      }
    }


### 2. Improving, but not enough

#### serializers.py

    #
    # more or less the same imports as the previous serializers file
    #

    class UserSerializer(serializers.ModelSerializer):
    
        class Meta:
            model = User
            fields = tuple(User.REQUIRED_FIELDS) + (
                User._meta.pk.name,
                User.USERNAME_FIELD,
                'joined_date',
                'profile',
            )
            read_only_fields = (
                User.USERNAME_FIELD,
                'joined_date',
            )
    
    
    class UserProfileSerializer(serializers.ModelSerializer):
        class Meta:
            model = UserProfile
            fields = ('first_name', 'last_name')

#### views.py

Assume same views file as the previous iteration

#### Generated output

##### For the _user_ endpoint

    curl -X GET http://localhost:8000/me/ -H 'Authorization: Token e62a064539e728ab7c5d8787f05df0c43db3c9b5'

    {
      "data": {
        "type": "users",
        "id": "1",
        "attributes": {
          "email": "a@a.com",
          "joined-date": "2017-07-18T14:10:51.753913Z"
        },
        "relationships": {
          "profile": {
            "data": {
              "type": "userProfiles",
              "id": "1"
            }
          }
        }
      }
    }

##### For the _user profile_ endpoint

Assume same output as the previous iteration

### 3. A false move

#### serializers.py

    #
    # more or less the same imports as the previous serializers file
    #

    class UserSerializer(serializers.ModelSerializer):
        profile  = ResourceRelatedField(
            queryset=UserProfile.objects,
            related_link_view_name='profile',
        )
    
        class Meta:
            model = User
            fields = tuple(User.REQUIRED_FIELDS) + (
                User._meta.pk.name,
                User.USERNAME_FIELD,
                'joined_date',
                'profile',
            )
            read_only_fields = (
                User.USERNAME_FIELD,
                'joined_date',
            )
    
    
    class UserProfileSerializer(serializers.ModelSerializer):
        class Meta:
            model = UserProfile
            fields = ('first_name', 'last_name')

#### views.py

Assume same views file as the previous iterations

#### Generated output

##### For the _user_ endpoint

    curl -X GET http://localhost:8000/me/ -H 'Authorization: Token e62a064539e728ab7c5d8787f05df0c43db3c9b5'

Got the exception _Reverse for 'profile' with keyword arguments '{'pk': 1}' not found. 1 pattern(s) tried: ['profile/$']_, because the '_profile_' URL pattern name we are trying to use doesn't receive a '_pk_' keyword argument.

##### For the _user profile_ endpoint

Assume same output as the previous iterations

### 4. Finally, what I wanted!

#### serializers.py

    from rest_framework_json_api import serializers
    from rest_framework_json_api.relations import ResourceRelatedField
    from rest_framework_json_api.utils import Hyperlink
    
    from django.contrib.auth import get_user_model
    
    from django.core.exceptions import ImproperlyConfigured
    from django.urls import NoReverseMatch
    
    from demo.users.models import UserProfile
    
    
    User = get_user_model()


    class ResourceRelatedFieldCustomized(ResourceRelatedField):
        """
        Customized class that offers a get_url method that does not require the
        kwargs param when reversing a view name to its corresponding full URL
        """
    
        def get_url(self, name, view_name, kwargs, request):
            # Builds a URL without requiring kwargs
    
            if not view_name:
                # Return None if the view name is not supplied
                return None
    
            try:
                url = self.reverse(view_name, request=request)
            except NoReverseMatch:
                msg = (
                    'Could not resolve URL for hyperlinked relationship using '
                    'view name "%s".'
                )
                raise ImproperlyConfigured(msg % view_name)
    
            if url is None:
                return None
    
            return Hyperlink(url, name)
    
    
    class UserSerializer(serializers.ModelSerializer):
        profile  = ResourceRelatedFieldCustomized(
            queryset=UserProfile.objects,
            related_link_view_name='profile',
        )
    
        class Meta:
            model = User
            fields = tuple(User.REQUIRED_FIELDS) + (
                User._meta.pk.name,
                User.USERNAME_FIELD,
                'joined_date',
                'profile',
            )
            read_only_fields = (
                User.USERNAME_FIELD,
                'joined_date',
            )
    
    
    class UserProfileSerializer(serializers.ModelSerializer):
        class Meta:
            model = UserProfile
            fields = ('first_name', 'last_name')

#### views.py

Assume same views file as the previous iterations

#### Generated output

##### For the _user_ endpoint

    curl -X GET http://localhost:8000/me/ -H 'Authorization: Token e62a064539e728ab7c5d8787f05df0c43db3c9b5'

    {
      "data": {
        "type": "users",
        "id": "1",
        "attributes": {
          "email": "a@a.com",
          "joined-date": "2017-07-18T14:10:51.753913Z"
        },
        "relationships": {
          "profile": {
            "links": {
              "related": "http://localhost:8000/profile/"
            },
            "data": {
              "type": "userProfiles",
              "id": "1"
            }
          }
        }
      }
    }

##### For the _user profile_ endpoint

Assume same output as the previous iterations

### Some general notes

* The authorization token value _e62a064539e728ab7c5d8787f05df0c43db3c9b5_ used with the _curl_ command corresponds to a sample token stored in the database of my sample project. It will change for other people with a similar sample
* Take care of the _import_ sentences. I'm not completely sure that I used the right ones in the given samples
* I changed the name of the _date_joined_ field to _joined_date_ in the User model, when compared with the original sample I submitted

### Conclusion

I got to a point that solves what I wanted: getting Django + Django REST Framework + Djoser working together to successfully generate JSON API compatible responses.

It's likely that what I did can be improved. Does someone have suggestions for achieving the same results in different or better ways? Which ones?

For me, this issue can be closed, unless someone thinks there is a reason for not doing that.

Thanks a lot for this project and for reading me!

**Comment by sliverc** [comment]
Thanks for sharing your experience.

The way you took is a way to go. What might also have helped is for the api caller to define header: `Accept=application/vnd.api+json` so DRF negotiation knows what renderer type to use.

As you suggest closing this issue.
