### ISSUE TITLE
Unable to patch objects with relationships

### ISSUE THREAD

**Issue by tgrosch** [django-json-api/django-rest-framework-json-api#368]
Hi,

I've encountered an error with current versions of DRF (3.6.3) and DRF-JSON-API (2.2.0). While storing objects like this:

    {
        "data": {
            "type": "Service",
            "id": "64",
            "attributes": {
                "name": "TEST",
            },
            "relationships": {
                "site": {
                    "data": {
                        "type": "Site",
                        "id": "1"
                    }
                }
            }
        }
    }

I always receive an error for field `site` that looks like this:

    Incorrect type. Expected pk value, received OrderedDict.

While having a dive into the processing of requests in your code, i found [this](https://github.com/django-json-api/django-rest-framework-json-api/blob/develop/rest_framework_json_api/parsers.py#L61). In my point of view this line should rather look like this:

    parsed_relationships[field_name] = (field_data or {}).get('id')

Overriding the class with this code works fine for me. Can you verify this, please? Thank you!

Cheers,
Tobi

**Comment by sliverc** [comment]
Your request body looks good to me and has worked for me in my projects. So I am a bit confused how you force this error. Could you provide a full example how your view, serializer etc. look like?

**Comment by sliverc** [comment]
As there hasn't been any feedback closing this issue. In case issue still exists please comment with necessary details and we can reopen this issue again.
