### ISSUE TITLE
Detail-Parameter in Errors invalid

### ISSUE THREAD

**Issue by tgrosch** [django-json-api/django-rest-framework-json-api#369]
Hi,

I'm using the current versios of DRF (3.6.3) and DRF-JSON-API (2.2.0) and I believe there's an issue with the value of `detail` when having an error:

    {
        "errors": [
            {
                "source": {
                    "pointer": "/data"
                },
                "status": "422",
                "detail": {
                    "source":{
                        "pointer": "/data/attributes/description"
                    },
                    "status": "422",
                    "detail": "This field may not be blank."
                }
            }
        ]
    }

As far as I understand the JSON API 1.0 [on this part](http://jsonapi.org/format/upcoming/#errors), I was expecting this:

    {
        "errors": [
            {
                "source":{
                    "pointer": "/data/attributes/description"
                },
                "status": "422",
                "detail": "This field may not be blank."
            }
        ]
    }

Since I'm using a frontend framework with the correct implementation of this, I'm running into problems concerning the type of `detail`. Again, please verify this issue.

Cheers,
Tobi

**Comment by sliverc** [comment]
This is odd this shouldn't happen. Could you provide more information how you reproduce this? View, serializer, rest framework settings etc.? Thanks.

**Comment by sliverc** [comment]
As there hasn't been any feedback closing this issue. In case issue still exists please comment with necessary details and we can reopen this issue again. Thanks.
