### ISSUE TITLE
Documentation or example of creating an object with a Generic Relationship?

### ISSUE THREAD

**Issue by michaelgodshall** [django-json-api/django-rest-framework-json-api#370]
I have an `Attachment` model with a generic relationship that looks like this:

```
class Attachment(models.Model):
    file_type = models.CharField(max_length=8)
    file_path = models.CharField(max_length=255)
    name = models.CharField(max_length=100)
    content_type = models.ForeignKey(ContentType)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
```

I'm trying to figure out how to create a Hyperlinked serializer for this with a writeable `content_object` that sets `content_type` and `object_id`.  Is that possible?  How have other people solved this with `django-rest-framework-json-api`?  I haven't been able to find any examples or documentation for it.  Any help would be appreciated.  Thanks!

**Comment by michaelgodshall** [comment]
For now I'm using `rest-framework-generic-relations` in order to write to the `content-object`.  I'm building the url in the client like `/api/products/1/`, and when the attachment is saved it populates the `content_type` and `object_id` fields accordingly.  I'd still like to know how other people are handling this, especially in a way that fits with the json api spec.

**Comment by kltdwrds** [comment]
@michaelgodshall so when you save the Attachment `/api/products/1/` is a regular `attribute` field in the request body's data object? That's an approach thats working for me too.

Ideally `rest-framework-generic-relations`'s GenericRelatedField was rendered as a relationship as per the spec.  (similar to DJA's ResourceRelatedField)

maybe a new `GenericResourceRelatedField` could do this?

**Comment by sliverc** [comment]
A new discussion started around this issue in terms of how to use generic relationships and to what extend this is actually JSON:API spec conform at #942. There are some example snippets added there which might already answer the initial question.

However it is not quite clear to what extend generic relationships are JSON:API conform. So therefore closing this issue and we can further discuss this issue at #942 to see whether there is an actual issue in DJA.
