### ISSUE TITLE
Switch main branch from develop to master

### ISSUE THREAD

**Issue by mblayman** [django-json-api/django-rest-framework-json-api#384]
The `master` branch is not doing anything and I think that using `develop` is outside of the norm for most GitHub projects. I suggest that the project switch to have the master branch be the primary branch to smooth over one road bump that might prevent contributors from getting involved.

Thoughts?

**Comment by sliverc** [comment]
I totally agree with the switch to `master` as default - I was always a bit confused when working on django-json-api project why it uses `develop` as the default.

**Comment by mblayman** [comment]
I made the switch from `develop` to `master`.
