### ISSUE TITLE
Add support for Django REST Framework 3.7 and Django 2.0

### ISSUE THREAD

**Issue by mblayman** [django-json-api/django-rest-framework-json-api#388]
DJA should be tested against DRF 3.7.x and document that support.

**Comment by mblayman** [comment]
Django 2.0 support doesn't come unless DJA supports DRF 3.7. Since there have been a few requests for Django 2.0 support, I've updated the title so that new visitors will understand the connection.

**Comment by Kazanz** [comment]
Is this in progress?

**Comment by mblayman** [comment]
Yes, please see #394. TLDR: the PR is blocked by an upstream project for now.

**Comment by lucacorti** [comment]
Looks like django-polymorphic 2.0 was released a couple of days ago.

**Comment by mblayman** [comment]
Thanks. I've clearly not been watching it closely so I'll try to get my PR updated soon so we can work toward getting out a new DJA release.
