### ISSUE TITLE
Handling Side-Loading Nicely

### ISSUE THREAD

**Issue by DylanLukes** [django-json-api/django-rest-framework-json-api#39]
Hi all. I wanted to get a little discussion going about how to handle side-loading nicely. After mucking around in the DRF and DJA internals for a bit, I've come to the conclusion that the `Renderer` is the right place to handle this (mostly).

Below is an example of a `JSONRenderer` that examines a `sideloads` dictionary on an `APIView` or `ViewSet` instance. It only supports `ModelSerializer` subclasses for use sideloading.

My use of an additional query for all of the related ids is a hack. Ideally, this should work "in Python" without touching the database again. That way, one can use `select_related` and `prefetch_related` in the view queryset (e.g. `MyModel.objects.select_related('some_o2o').prefetch_related('some_m2m').all()`) for performance tuning without changing the semantics.

It also assumes the use of `PrimaryKeyRelatedField`, and doesn't yet support hyperlinks. That shouldn't be too hard to add.

Simplistic, but it's a place to start. Thoughts?

```python
class MyViewSet(ModelViewSet):
    sideloads = { 'foo': FooSerializer, 'bar': BarSerializer }
    ...
```

```python
class SideloadingJSONRenderer(JSONRenderer):
    def render(self, data, accepted_media_type=None, renderer_context=None):
        view = renderer_context.get('view')
        queryset = view.get_queryset()
        resource_name = get_resource_name(view)

        # for various reasons, we probably don't want to sideload in this case.
        if resource_name == False:
            return super(JSONRenderer, self).render(
                data, accepted_media_type, renderer_context)

        try:
            content = data.pop('results')
            resource_name = format_resource_name(content, resource_name)
            data = {resource_name: content, "meta": data}
        except (TypeError, KeyError, AttributeError) as e:

            # Default behavior
            if not resource_name == 'data':
                format_keys(data, 'camelize')
                resource_name = format_resource_name(data, resource_name)

            data = {resource_name: data}

        # Sideloading
        for attr, serializer in view.sideloads.items():
            rel_objs = getattr(serializer.Meta, 'model') \
                .objects \
                .filter(id__in=queryset.values_list(attr, flat=True).distinct())

            rel_data = serializer(rel_objs, many=True).data
            rel_name = format_resource_name(rel_data, attr)

            data.update({rel_name: rel_data})

        data = format_keys(data, 'camelize')

        return super(JSONRenderer, self).render(
            data, accepted_media_type, renderer_context)
```

**Comment by DylanLukes** [comment]
Other thoughts:

  - The use of format_keys in the "default behavior" is broken, that function doesn't work in place.
  - It might be more appropriate to supply a View, rather than a Serializer, to enforce authorization constraints. Otherwise, it might be too easy to write leaky API views.
  - If using a ViewSet (not just an APIView) rather than Serializer, perhaps sideloading could be treated as an action? That would allow methods to switch on `self.action == 'sideload'` and handle it distinctly.

**Comment by jsenecal** [comment]
I'm kinda trying to understand what you are trying to achieve here. Couldn't that be implemented using the ususal fields assignment in the serializer?
Like this:
```pyhton
class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
    some_field = SomeSerializer()
```

I might be confused though, feel free to correct me ;)

**Comment by jerel** [comment]
I'm guessing you've been studying the `master` branch (which is good; it's stable) but take a look at `develop`. Sideloading should be solved by the `included` feature in the JSON API spec.

In older versions of DJA where the target was Ember Data you could either do like @jsenecal mentions or do something like https://github.com/django-json-api/django-rest-framework-json-api/blob/master/example/api/resources/identity.py#L28-L37

**Comment by DylanLukes** [comment]
Ah yes, I've been exclusively using what is available as `rest-framework-ember` on PyPi. 

@jsenecal Not quite. That embeds the resource. 

Here's the payload for what you suggested (embedding):

```json
...
"users": [
  {"some": {"id": 1, "foo": "bar"}},
  {"some": {"id": 2, "foo": "baz"}},
  {"some": {"id": 3, "foo": "qux"}},
]
```

Versus using Ember-style sideloading:

```json
...
"users": [
  {"some": 1},
  {"some": 2},
  {"some": 3},
],
"somes": [
  {"id": 1, "foo": "bar"},
  {"id": 2, "foo": "baz"},
  {"id": 3, "foo": "qux"}
]
```

Or, in JSON API, you would have `"somes"` inside a sub-root `"includes"` hash.  Ember understands this by convention and will skip the request for `/somes?id[]=1&id=2&id=3` when they're included in that manner.

**Comment by jerel** [comment]
Yeah, to get that last behavior in my rest_framework_ember apps I've done:
``` python
class MyView(viewsets.ModelViewSet):

    def list(self, request, *args, **kwargs):
        response = super(MyView, self).list(request, *args, **kwargs)
        response.data['whatevers'] = WhateverSerializer(whatever.objects.all())
        return response
```
The JSON API version should be more elegant since Ember Data should look for `included`

**Comment by DylanLukes** [comment]
If you do it that way, you're not handling pagination, filtering, etc... All things that affect the output.

Honestly, I've considered just implementing JSON API directly in PL/pgSQL. 

(On that note, you can solve this problem with materialized views particularly nicely, as your handling of PATCH and other partial updates is rolled into your schema.)

**Comment by jerel** [comment]
I'm going to close this as it seems we have the original issue solved in the `develop` branch and it sounds like you may have found a solution for whatever problem you were needing to solve. If that's not correct just shout and I can reopen
