### ISSUE TITLE
Avoid overwriting of pointer when using custom errors

### ISSUE THREAD

**Issue by brettdh** [django-json-api/django-rest-framework-json-api#399]
The code that produces JSON:API error objects assumes that all fields being validated are under `/data/attributes`:

https://github.com/django-json-api/django-rest-framework-json-api/blob/b0257c065ac2439036ac0543139e7f5913755177/rest_framework_json_api/utils.py#L339

and there doesn't appear to be a way to override the `pointer` value when specifying the field on a serializer.

Use case: I would like to be able to specify a serializer for the top-level `"meta"` field and have any validation errors on that data generate responses properly populated with `"source": {"pointer": "/meta/foo"}`.

**Comment by brettdh** [comment]
More generally: I would like to be able to override the `pointer` that DRFJA creates with a custom value per field. I would guess (but have not tested) that the code linked above also doesn't handle specifying indices for individual errors when `data` is a list.

**Comment by sliverc** [comment]
It is currently not possible to have custom error format. It might be handy though also to add other information allowed by [json api](http://jsonapi.org/format/#errors). Maybe needs to be solved with a custom json api `ValidationException` but would need to investigate how this can be done properly.

What you could always do is to return your own [Response](http://www.django-rest-framework.org/api-guide/responses/#response) with the error in the format you need it.

**Comment by sliverc** [comment]
While discussing #776 it occurred to me that it actually is already possible to define custom error objects - see [test code snippet](https://github.com/django-json-api/django-rest-framework-json-api/blob/master/example/api/serializers/identity.py#L18).

Closing this issue therefore. Please comment in case this doesn't solve this issue.

**Comment by Elawphant** [comment]
**serializers.ValidationError** does not support custom `source: { pointer: ... }`. E.g.
```                    
raise serializers.ValidationError([{
        "detail": "This field is required.",
        "source": {
        "pointer": "/data/something"
     }
}])
```
results in 
```
{
    "errors": [
        {
            "detail": "This field is required.",
            "source": {
                "pointer": "/data"
            }
        }
    ]
}
```
This issue needs to be reopen.
