### ISSUE TITLE
Can not include a top-level `meta` section in an error response.

### ISSUE THREAD

**Issue by rockmnew** [django-json-api/django-rest-framework-json-api#403]
When generating an error response, DJA takes the contents of the data provided in the response, and makes it all contents of the `errors` section.  A side effect of this is that you can not have a top-level `meta` section, even though this is permitted by the json:api spec.

 A good fix might be to have DJA use the response as-is if it contains `errors` as a top-level section.  Optionally, also check if `errors` is a list.  Since there are other optional top-level sections, I'm not sure if additional verification (making sure all top-level sections are permitted) is necessary.  I think it might reasonable to assume that someone who includes `errors` as a top-level section knows what they're doing.

For backwards compatibility, anything which does not appear as valid based on what's decided by the previous paragraph would continue the current behavior of making it the contents of a new top-level `errors` section.

**Comment by sliverc** [comment]
I think this is kind of going into the direction requested in #399 .

Closing this issue.

It would certainly be appreciated if you could add your code how you have done in #399 . We might work out a way in DJA from there.
