### ISSUE TITLE
JSON_API_FORMAT_KEYS setting to default to lowercase plural type?

### ISSUE THREAD

**Issue by n2ygk** [django-json-api/django-rest-framework-json-api#414]
While the [spec](http://jsonapi.org/format/#document-member-names) allows upper and lower case characters in `type` names, the [recommendations](http://jsonapi.org/recommendations/#naming) suggest all lowercase. The choice of plural vs. singular for the `type` is undefined but should be used consistently and most examples use plural.

Since PEP8 wants class names to be CapWords, I can enforce a "local standard" such as lowercase plurals with `JSONAPIMeta` `resource_name` in the models.Model like this:
```python
class Widget(Common):
    name = models.TextField()
    qty = models.PositiveIntegerField(blank=True, default=0)

    class Meta:
        ordering = ["name"]

    class JSONAPIMeta:
        resource_name = "widgets"

    def __str__(self):
        return self.name + ' (' + str(self.id) + ')'
```
However this is not DRY.

Alternatively I think I can set these:
```python
JSON_API_FORMAT_KEYS = 'camelize'
JSON_API_PLURALIZE_TYPES = True
```
But `camelize` is not the same as all lowercase.

Would it make sense to add a `JSON_API_FORMAT_KEYS` option for `lowercase` to add to the current list of `('dasherize', 'camelize', 'underscore', 'capitalize')`?

**Comment by sliverc** [comment]
Don't you think `dasherize` covers this? This is also lowercase and simply adds dashes which the recommendation you have referenced mentions as well.

**Comment by n2ygk** [comment]
Yes I think you are correct. In fact, I don't know why I'm not just using pluralize and underscore since I was calling my `CourseTerm` class's JSONAPI type `course_terms`. Thanks!
