### ISSUE TITLE
Handling large number of relationships  - pagination?

### ISSUE THREAD

**Issue by dbinetti** [django-json-api/django-rest-framework-json-api#417]
I have a model that sometimes has a large number of child resources (sometimes many thousands).  Were this a standard list I'd simply paginate the results -- but it isn't obvious to me how to paginate the relationship links.  

It looks like some changes were recently adopted on the `json-api` spec (https://github.com/json-api/json-api/pull/1251) and I've seen #178 here, but I'm not sure what the current recommendation is for handling this case.  

THanks

**Comment by sliverc** [comment]
As discussed in #178 this is as far as I am concerned still not supported out of the box.

There is a possible workaround to this as mentioned here https://github.com/django-json-api/django-rest-framework-json-api/issues/178#issuecomment-166977819 but you would have to try how this works out for you.

But to avoid cluttering issues and discussion I am closing this issue. If you have any other comments or questions concerning this best comment on #178 Thanks. And as always if you get this fixed for you PRs are really welcome or even code snippets as a workaround added to issue #178
