### ISSUE TITLE
CREATE OBJECT AND OBJECT RELATED 

### ISSUE THREAD

**Issue by ramses132** [django-json-api/django-rest-framework-json-api#418]
By default the method to_interval_value(self, data)
Capture the ID if ID is NULL it's raise excepction non primary key I want to create in same view object and its related objects without edit the_interval_value, and validate method... Why is the best practice to make it possible?

**Comment by sliverc** [comment]
There is #155 discussing this issue. Potentially comment in #404 might also help.

Closing this issue to focus discussion in #155
