### ISSUE TITLE
Add a blog_example app with fixtures that can be used for tests and as an example

### ISSUE THREAD

**Issue by jsenecal** [django-json-api/django-rest-framework-json-api#42]
See #40

**Comment by abdulhaq-e** [comment]
Hello @jsenecal 

Are you working on this?

I have a branch full of edits none of which can be merged without tests and this really requires the example app. If you're not, I'll have a shot at it, the example blog app in Django docs is a good starting point.

**Comment by jsenecal** [comment]
@abdulhaq-e I'm working on features more than anything else recently - If you want to work on this, please do, it would definitely help to have more tests!

**Comment by jerel** [comment]
For anybody that happens onto this issue the blog app has been started [here](https://github.com/django-json-api/django-rest-framework-json-api/tree/develop/example) but still needs to be fleshed out a bit.
