### ISSUE TITLE
PUT requires id

### ISSUE THREAD

**Issue by raphaa** [django-json-api/django-rest-framework-json-api#422]
PUT is not just updating an existing resource, it can also create one, so the field id can't be mandatory. This would be an easy fix but would like to discuss it here first.

**Comment by n2ygk** [comment]
The [json-api spec](http://jsonapi.org/format/) doesn't define use of PUT; it's either POST to create a new resource or PATCH to update one so I think it's a bug that PUT is allowed at all (leaking through from DRF?). 

I see that it is in the Allow headers for an item but not for a collection. 

item: `Allow: GET, PUT, PATCH, DELETE, HEAD, OPTIONS`

collection: `Allow: GET, POST, HEAD, OPTIONS`

**Comment by sliverc** [comment]
Here is the specification which states that `PUT` is not specified in json api: http://jsonapi.org/faq/#wheres-put

What the `rest_framework` concerns is that `PUT` is a `PATCH` and they specifically didn't want `PUT` to create resources as well.

See http://www.django-rest-framework.org/api-guide/generic-views/#put-as-create

So if you want to create a resource you need to use `POST`. Closing this issue but if you have questions concerning this please let me know.
