### ISSUE TITLE
Request for new maintainer

### ISSUE THREAD

**Issue by mblayman** [django-json-api/django-rest-framework-json-api#424]
I picked up the maintainer torch about a year ago when the project seemed to be stuck. I was using DJA on a side project, and I needed to fix a bug and get a new release out. Today, I'm no longer working on the side project and my interest in maintaining DJA has waned significantly.

As I'm not being a great steward for the project, I'd like to request that someone else pick it up. This is very much a community effort and code contributions come from a wide variety of contributors. The new maintainer would be most involved with:
1. Review of new Pull Requests and Issues.
2. Deploying new releases to PyPI.

I hope that I've added the right tools that can make management of this project easier for a future maintainer. Static code analysis has removed a lot of friction that might come up as a primary PR reviewer.

If you're in a decent place to step into the maintainer role, please let me know and I can work to transition over project handling to you. I'm happy to help with a bit of training if needed or improving release documentation.

**Comment by mblayman** [comment]
Yes, I think I'm the only active maintainer. My chronology may not be exactly right, but @gaker started the project, @jsenecal maintained it after that, @jerel followed him, and I picked it up from @jerel.

These guys chime in from time to time, but I don't believe that any of them are actively maintaining DJA.

Switching to Jazzband is probably a pretty solid idea if there is no one with the time availability to act as a regular maintainer.

**Comment by sliverc** [comment]
I use DJA in several projects and therefore would be interested in a well maintained DJA. I do not think though I would have the time to be a sole active maintainer and I also think it won't be good for the project in the long run.

For the future of the project moving it to JazzBand could be a good idea. If it is decided to go down this way I would be willing to help out in the transition.

**Comment by n2ygk** [comment]
I would be happy to back you up @sliverc. I just joined Jazzband, FWIW.

**Comment by mblayman** [comment]
I'm happy to pass the baton to the two of you as you both have actively contributed within the last year. I think I would need to add you to the django-json-api team. Ultimately, I can give one or both of you the upload permission to the PyPI package.

I think I should probably start a `CONTRIBUTING.md` file so that if the team ultimately decides to move to Jazzband, that work will at least be done.

**Comment by sliverc** [comment]
@mblayman If you could add me to the team and give PyPi upload rights that would be great.
I see when I get around but I will try to get the current PRs reviewed and get a release out.

I do not really wanna review my own PRs (would miss the whole point of reviews... :)) so I think it would be great if someone else would be regularly active to review those (someone who is already part of the team or @n2ygk if you see yourself in the position to review PRs and work through the open issues would be great too)

Once those tasks are cleared out we can then still consider whether it would be good to move to JazzBand or not. I hope though that the other team members might help out once in a while as well and then it might not be necessary.

**Comment by jerel** [comment]
> Yes, I think I'm the only active maintainer. My chronology may not be exactly right, but @gaker started the project, @jsenecal maintained it after that, @jerel followed him, and I picked it up from @jerel.

Yeah, gaker and myself open sourced this project from a company that we worked together at. I still have DJA in production but that project is in maintenance mode so I don't have the time to focus on ongoing development here. Thanks to everyone who has stepped up to keep this library alive!

**Comment by simkimsia** [comment]
This is weird. I only recently looked at DJA just a week ago because I may need it in a project.

My situation is similar to @sliverc I be happy to help with transitioning this to jazzband. It's in my interest to see this well maintained.

I am not particularly skilled. but be happy with some simple grunt coding tasks if given some training.

**Comment by n2ygk** [comment]
@sliverc Happy to review your PRs.

**Comment by n2ygk** [comment]
@mblayman what are the next steps?

**Comment by mblayman** [comment]
@n2ygk I would add you to the `django-json-api` team, but I see that I don't have permission to do that.

@jerel, could you add @n2ygk and @sliverc to the DJA team?

**Comment by jerel** [comment]
Hmm, I thought you had access. Oh well, I added both. Thanks

**Comment by jerel** [comment]
@sliverc done

**Comment by sliverc** [comment]
@jerel Thanks.

I suggest we could close this issue for now what you think? In the future we could ask contributors more actively whether they want to become maintainers to keep growing the team.

**Comment by mblayman** [comment]
Thanks @sliverc and @n2ygk! I really appreciate you two stepping up to take care of this project.

**Comment by n2ygk** [comment]
@mblayman @jerel @sliverc something is broken with Travis: "continuous-integration/travis-ci Expected — Waiting for status to be reported" in #434. Any idea how to resolve this? Is this related to recent changes of maintainers?

**Comment by n2ygk** [comment]
moved to maintainers group
