### ISSUE TITLE
Exception handling with nested resources

### ISSUE THREAD

**Issue by skeezus** [django-json-api/django-rest-framework-json-api#438]
I'm parsing a nested data structure that I receive from a client using Django Rest Framework's ValidationError class in the exception module. If the top level data has an error, the json api exception formats properly as shown further down, however when the nested data has an error django's exception handling is used (also shown further down).

The data structure looks something like this:
```
{
   "business":"foo enterprises",
   "user": {
        "first_name":"foo",
        "last_name":"bar",
   }
}

```
When I parse this request and an error turns up on the top level of the structure such, ie: the client left out the business field, DRF returns the error in the following format:

```
{
    "errors": [
        {
            "source": {
                "pointer": "/data/attributes/business"
            },
            "detail": "This field is required.",
            "status": "400"
        }
    ]
}
```
However when the client fails to include nested data such as the first name of the user, the format of the error is this:

```
{
    "errors": [
        {
            "first_name": [
                "This field is required."
            ]
        }
    ]
}
```
My serializers look like this:

```
class UserSerializer(serializers.Serializer):
    first_name = serializers.CharField(max_length=75)
    last_name = serializers.CharField(max_length=75)

```
```
class RequestSerializer(serializers.Serializer):
    email = serializers.CharField(max_length=100)
    user = UserSerializer(required=True)
```

The goal is to have a JSON Api formatted response when the nested serializer finds an error. For now I'm going to either roll my own exception handler or flatten nested error dictionary but is there a better way?

**Comment by n2ygk** [comment]
Take a look at #437 to see if it does the right thing for you.

**Comment by nattyg93** [comment]
I've come across this same issue in a slightly different context. I'm happy to consider working on a pull request. Is this something that you folks are interested in getting tackled?

This same issue occurs when the child field of `ListField` raises a `ValidationError`. `ListField` will raise something like `{1: '"asdf" is not a valid choice.'}` and hence the error handler will skip formatting the error.

As a quick work around I added this:
```
class SerializerWithListField(serializers.ModelSerializer):
    """Serializer with a ListField."""

    validated_list = serializers.ListField(
        child=serializers.ChoiceField(choices=[("choice_1", "choice_2")])
    )

    def __init__(self, *args, **kwargs):
        """Record which fields are ListFields."""
        super().__init__(*args, **kwargs)
        self._list_fields = {
            field_name
            for field_name, field in self.fields.items()
            if isinstance(field, serializers.ListField)
        }

    def to_internal_value(self, data):
        """Flatten nested error dict."""
        try:
            return super().to_internal_value(data)
        except ValidationError as error:
            if not isinstance(error.detail, dict) or not self._list_fields:
                raise error
            errors = {}
            for key, value in error.detail.items():
                if key in self._list_fields and isinstance(value, dict):
                    # flatten nested dict out into parent dict
                    for list_key, list_value in value.items():
                        errors[f"{key}/{list_key}"] = list_value
                else:
                    errors[key] = value
            raise ValidationError(errors)

    class Meta:
        """Serializer meta information."""

        model = ModelWithList
        fields = ["validated_list"]
```

This solution is very much bespoke for this specific use case, however, so by no means useful as a generic solution. Ideally we could work towards improving the error handler - perhaps looking to tackle #413 also.

**Comment by sliverc** [comment]
@nattyg93 Thanks for bringing this issue back to attention.

With #776 we have introduced nested structure within a attribute value. Outstanding in this case is still the error handling part see #787. 

I think with the approach taken in that PR your issue with `ListField` should also be solved but not the initial use issue of this report. This needs to be added as test case to be sure though.

I would certainly be interested in tackling those hanging error handling issues but we need to be careful not to overlap different initiatives. I don't know when or if @sapiosexual has time to continue working on #787 - so if you want to work on those issues best to coordinate with him.

**Comment by nattyg93** [comment]
@sliverc Excellent! I'll take a look at #787 and see if I can help out there. Cheers.
