### ISSUE TITLE
Can't find example app

### ISSUE THREAD

**Issue by ThibaultLemaire** [django-json-api/django-rest-framework-json-api#452]
It looks like the readme is outdated concerning the example app.

In the section [Running the example app](https://github.com/django-json-api/django-rest-framework-json-api#running-the-example-app), the last command

``` sh
django-admin.py runserver --settings=example.settings
```

doesn't run because there is no `django-admin.py`

**Comment by ThibaultLemaire** [comment]
The [same section in the docs](http://django-rest-framework-json-api.readthedocs.io/en/stable/getting-started.html#running-the-example-app) is more detailed, and seems little bit more up to date; Although it has its own problems.

Should I open an other issue for that?

**Comment by sliverc** [comment]
This looks odd and needs to be adjusted indeed.

As it both addresses documentation how to use the example app one issue should be good.

I think there are other errors in the documentation as well but it should surely be `django-admin` without the `.py` and for this to be there django needs to be installed.

**Comment by ThibaultLemaire** [comment]
New issue created concerning the doc -> #454

**Comment by n2ygk** [comment]
```bash
(env) django-training$ which django-admin
/Users/alan/src/django-training/env/bin/django-admin
(env) django-training$ which django-admin.py
/Users/alan/src/django-training/env/bin/django-admin.py
```

**Comment by n2ygk** [comment]
Closing - see #454
