### ISSUE TITLE
Clarify "included" documentation

### ISSUE THREAD

**Issue by erichonkanen** [django-json-api/django-rest-framework-json-api#456]
I just want to clarify that with the [included](https://django-rest-framework-json-api.readthedocs.io/en/stable/usage.html#included) functionality, the included extra resources are only returned if the client requests them by doing a query like `GET /articles/1?include=comments` using the [json-api `include`](http://jsonapi.org/format/#fetching-includes) parameter?

The current documentation does not make it clear if the included extra data is conditionally returned versus always returned. The behavior should be conditional so I'm just checking.

**Comment by sliverc** [comment]
It's conditional so it is only included when the include query param is passed on as the JSON API specification states.

Documentation seems to imply this as it follows the JSON API specification, but a link to the specification would certainly be good.

PRs are welcome.

**Comment by erichonkanen** [comment]
thanks!
