### ISSUE TITLE
move isort and flake8 tests to the top

### ISSUE THREAD

**Issue by n2ygk** [django-json-api/django-rest-framework-json-api#460]
isort and flake8 tests are not run until all other tests. They should go first in .travis.yml. Also make isort and flake8 tests part of the tox testenv commands.

**Comment by sliverc** [comment]
Technically they should run in parallel but usually there are queued up on travis. So moving flake8 and isort up is certainly a good idea.
We could also do isort and flake8 check in one run using [flake8-isort](https://github.com/gforcada/flake8-isort) which would improve those checks.

Maybe even better is to check flake8 and isort before they are even committed with pre-commit hooks e.g. using https://pre-commit.com/

**Comment by n2ygk** [comment]
Let's start with fixing tox.ini to include flake8 and isort as the first tests in the main testenv, maybe documenting developer guidelines and adding a local pre-push or pre-commit hook.

I don't know if there's value in [combining tox and travis](https://stackoverflow.com/questions/37016688/how-to-run-tox-with-travis-ci) to keep things DRY. I expect this would lose the parallelism but it would at least guarantee that a succesful local tox run would likely succeed with travis as well.  

I don't have enough experience to judge whether this is worth doing, but I can at least make sure documenting running tox w/flake8 and isort locally before pushing happens.

**Comment by n2ygk** [comment]
Maybe add:
```
before_script:
  - tox -e flake8-isort
``` 
and remove from the matrix:
```
    - python: 3.6
      env: TOXENV=flake8
    - python: 3.6
      env: TOXENV=isort
```
so if the flake8-isort fails, then don't waste time running all the other script steps.

**Comment by sliverc** [comment]
not sure... I still see some value when I have flaking errors and the test still runs and might fail on a particular Python version I can fix both issues at the same time. Otherwise I have to fix the flaking error and then push again and wait till the CI runs through.

Let's just keep it in moving up the isort and flake8 up the list I think that's good enough. Documenting is also a good thing for sure.
