### ISSUE TITLE
Json-api renderer breaking when paired with JWT packages (simple-jwt & drf-jwt)

### ISSUE THREAD

**Issue by josh91hickman** [django-json-api/django-rest-framework-json-api#473]
Ran into this issue today while setting up a backend -

`line 479, in build_json_resource_obj
    ('id', encoding.force_text(resource_instance.pk) if resource_instance else None),
AttributeError: 'dict' object has no attribute 'pk'`

Found out that is occurring from this line of code located inside of renderers.py
```
('id', encoding.force_text(resource_instance.pk) if resource_instance else None),
```
[link-to-code](https://github.com/django-json-api/django-rest-framework-json-api/blob/master/rest_framework_json_api/renderers.py#L479)

in particular its the "resource_instance.pk" thats blowing up. This occurs whenever I'm using JWT packages [simple-jwt](https://github.com/davesque/django-rest-framework-simplejwt) or [drf-jwt](https://github.com/GetBlimp/django-rest-framework-jwt/issues?q=is%3Aissue+json+api+is%3Aclosed)

If I change the line to 
```
('id', encoding.force_text(resource_instance['user'].pk) if resource_instance else None),
```
Everything works. Ideally I'd like to avoid having to go down the route of forking, does anyone know how I could get past this? It seems the renderer is making an assumption about how the resource_instance should be returned from the JWT serializer.

**Comment by sliverc** [comment]
I have used drf-jwt before as well and didn't have any issues with JSON API.

Could you post a short code snippet what exact views and seraializers you use?

**Comment by sliverc** [comment]
This serializer looks a bit odd because it returns user as data but doesn't define field. If it wouldn't need to be serialized it would need to be defined as `RelatedField` marked as read_only.

Also I just quickly tested it and cannot reproduce an error:

Test code:
```python
    url = reverse('rest_login')

    data = {
        'data': {
            'attributes': {
                'password': 'password',
                'username': 'admin',
            },
            'type': 'loginViews'
        },
    }
    response = client.post(url, data=data)
    assert response.status_code == 200
```

This reproduces following output:
```
{'data': {'attributes': {'key': 'a1c94b5cfd5d503d95cafc5d08be8afa1c0dbbc7'},
          'id': 'a1c94b5cfd5d503d95cafc5d08be8afa1c0dbbc7',
          'type': 'loginViews'}}
```

Maybe overwriting serializer and marking user as related field might help you already.

Otherwise could you provide a PR potentially which reproduces this error within the json api example?

**Comment by josh91hickman** [comment]
@sliverc what version of django-rest-framework-json-api did you test this with? the only reason I ask is your response is different than what im used to on the version Im on - 'type': 'loginViews' doesn't work for me, it must explicitly be 'type': 'LoginView' - not sure if this is a typo or how the response actually came back. Can you also confirm for me that you're authenticating through django-rest-auth? I'm trying to pin-point where the exact issue is.

**Comment by sliverc** [comment]
See my branch where I have tried to reproduce it:
https://github.com/sliverc/django-rest-framework-json-api/blob/rest_login/example/tests/test_views.py

If you do something different feel free to adjust the branch so it is reproducible.

**Comment by josh91hickman** [comment]
@sliverc I was able to get past this error by subclassing the serializer as you stated. I also changed the login/signup renderers to JSON. Closing - thank you for your help.

**Comment by ewelinabuturla** [comment]
Hi, could you please share how did you fix it? Also having same issue

**Comment by ewelinabuturla** [comment]
I have exactly the same issue. I use rest_auth with drf-jwt and want to switch to json api. 
When trying to register user I got the same error.  
I see that resource_instance contains both token and user instance, so changing to `resource_instance['user'].pk ` helps. But how to avoid that. This is how my serializer looks like:
```
class UserSerializer(serializers.ModelSerializer):
    class Meta:
        model = get_user_model()
        fields = ("pk", "email", "first_name", "last_name")

```

**Comment by sliverc** [comment]
@ewelinabuturla 
This issue is old and even though your issue might look similar it might not be. And when I read through it seems that I was actually never able to reproduce this issue.

I am locking this conversation. But if your issue still exists best open a pull request with a reproducing test for your issue (can also be an example application or similar if this is easier).
