### ISSUE TITLE
Resource name with inherited models

### ISSUE THREAD

**Issue by skeezus** [django-json-api/django-rest-framework-json-api#491]
I'm having trouble getting the proper resource_name returned in the relationships object when using model inheritance. For instance, if I have a parent model (users) and child model (employees), the resource_name of the child model is generally returned as users even though I've set it as employees in the JSONAPIMeta tag on my inherited employees model.

The employee is returned in the relationships object on my business serializer. On this serializer I don't specify a serializer for employee so it seems to get serialized as a user, not an employee. My serializer code is something like this:

```
class BusinessSerializer(serializers.ModelSerializer):
	class Meta:
		model = Business
		resource_name = 'businesses'
		fields = ('id', 'name', 'address', 'employees')

```

And my model:

```
class Employee(User):
	employees = models.ForeignKey(
		'businesses.Business',
		related_name='employees',
	)

    class JSONAPIMeta:
		resource_name = 'employees'
```

I know that defining the resource_name on the serializer is best due to the hierarchy however this requires me to define a serializer for employees which increases dependency in my application. The long-term solution may be to restructure my serializers to handle dependency / circular imports better but I'm wondering if there's another solution here.

**Comment by sliverc** [comment]
Not sure but it could be that there is an issue with reverse relationships. It would be good to have a reproducing test within a DJA code base to have a better understanding.

In any case I think models should be a representation of the database layer and serializers the representation on the API itself. Hence the resource_name should be put on the serializer itself and using `included_serializers` this also works for relationships.

**Comment by sliverc** [comment]
As there hasn't been any feedback for a while I assume above comment helped or you have found another solution. Closing this issue. But if there are still questions please feel free to comment.
