### ISSUE TITLE
Add support for python 3.7

### ISSUE THREAD

**Issue by simkimsia** [django-json-api/django-rest-framework-json-api#495]
I like to contribute with a PR regarding adding python 3.7

I read https://github.com/django-json-api/django-rest-framework-json-api/blob/master/docs/CONTRIBUTING.md

and my changes are in my fork.

https://github.com/simkimsia/django-rest-framework-json-api/commit/c23c3189faeb7999af5ead8bbe3d0831ee3abbb3

Can I proceed?

**Comment by sliverc** [comment]
Current DRF version doesn't officially support Python 3.7 as of issue #486.

So for official Python 3.7 support DRF 3.9 needs to be released. Also only Django 2.0+ supports Python 3.7. Django Filters as of version 2.0

However feel free to open a PR where update of DRF and Python is prepared and can be merged once it is released.

**Comment by simkimsia** [comment]
@sliverc from what I understand, I think master branch of DRF already has 3.7 python. Not sure if this means it's out in 3.8.2 or not.

See https://github.com/encode/django-rest-framework/commit/7f77340b331e68357535a83e90eb0f8e1002b943

But I did realise that Django 1.11 is not supporting python 3.7 https://github.com/django/django/pull/10371, so i guess this is a moot point. I will close this ticket then.

Personally I am only interested to use only LTS versions of Django to reduce complexity. Thanks :)
