### ISSUE TITLE
HyperlinkedRelatedField is incompatible with HyperlinkedModelSerializer

### ISSUE THREAD

**Issue by hmpf** [django-json-api/django-rest-framework-json-api#521]
If HyperlinkedRelatedField raises SkipField, HyperlinkedModelSerializer does not catch it, leading to a 500 Server Error. Is this a feature or a bug? If a feature, where is it documented?

**Comment by sliverc** [comment]
Technically this should work, so if it doesn't this is most likely a bug.

Some example code, traceback or at best a PR with a reproducing test might be helpful to investigate the problem further.
