### ISSUE TITLE
Object relationships is always rendered

### ISSUE THREAD

**Issue by masarliev** [django-json-api/django-rest-framework-json-api#528]
No matter if `include=comments` in send I always get `post.relationships.comments`. `include=comments` just adds comment objects in `included` 
Is this default behaviour (always return object relations ) or I am missing something

**Comment by sliverc** [comment]
In my opinion this is the correct behavior according to JSON API spec.

The [relationships](https://jsonapi.org/format/#document-resource-object-relationships) always need to be represented to give the api caller the option what way full object of a relationships can be retrieved.

API caller has basically three options:
1. Using [link objects](https://jsonapi.org/format/#document-links)
2. Using [resource linkage](https://jsonapi.org/format/#document-resource-object-linkage)
3. Using [include](https://jsonapi.org/format/#document-compound-documents)

When relationships would only be rendered when using `include` parameter option 1 and 2 wouldn't be an option.

Hope this clarifies?

**Comment by sliverc** [comment]
In case you only want partial fields you can use
https://jsonapi.org/format/#fetching-sparse-fieldsets which DJA also supports.

Hope this answers your question. Closing issue. Please comment if not.
