### ISSUE TITLE
Customizing relationships

### ISSUE THREAD

**Issue by pattisdr** [django-json-api/django-rest-framework-json-api#54]
<h1> Problem </h1>
 `extract_relationships` should be able to handle specialized cases, like allowing a `links` or `meta` object instead of a `data` object. For example, in our application it needs to: 

1. recognize other field types as relationships
2. return a `links` object instead of a `data` object with type/id 

The relationship data is read-only.
<h1> Desired </h1>
![screen shot 2015-08-04 at 3 28 42 pm](https://cloud.githubusercontent.com/assets/9755598/9071636/599be0c6-3ac4-11e5-9778-1983ffe75510.png)

<h1> Potential solutions </h1>
@jerel suggested a serializer hook like `add_relationships` for customization.

According to the spec, under `relationships` you must include a `links`, `data`, or `meta` object.  http://jsonapi.org/format/#document-resource-object-relationships.  The current `extract_relationships` just allows for a `data` object.  It would be valuable for users to be able to have a `links` object, instead.

**Comment by jsenecal** [comment]
Commenting for clarity: According to the spec, a "relationship object" **MUST** contain at least **one** of the following: `links`, `data`, or `meta` object. 

Going through the data included in fields looking for link-like data would require too much processing power and IMO introduce too much magic.

What is your API structure if you don't mind?

**Comment by pattisdr** [comment]
What do you mean by API structure?

**Comment by jsenecal** [comment]
I'm trying to get a glimpse of what/how you are using the endpoints. What are your registered URLs looking like?

On Aug 17, 2015 10:05 AM, Dawn Pattison <notifications@github.com> wrote:

What do you mean by API structure?

**Comment by pattisdr** [comment]
We have projects, called 'nodes'.   If I want to access node detail, I get this:
![screen shot 2015-08-17 at 10 19 38 am](https://cloud.githubusercontent.com/assets/9755598/9306911/3f4a57e8-44c9-11e5-9d8e-606a3e99cf88.png)
Note: To get this formatting I am using a fork of your package https://github.com/pattisdr/django-rest-framework-json-api/commit/f12101fba5b5e0a05e586a3ae12490ed9cdea648.  The relationships like `children` and `contributor` are using a custom HyperlinkedIdentityField that returns a link, optional meta information like `count`, and optional link type like `self` or `related`.

From Swagger docs, here is a list of available url's:
![screen shot 2015-08-17 at 10 21 42 am](https://cloud.githubusercontent.com/assets/9755598/9306950/763c38ac-44c9-11e5-82c6-aadfb9d38002.png)

**Comment by jsenecal** [comment]
Okay, so I introduced support for HyperLinkedIdentityField in #80 (Commit https://github.com/django-json-api/django-rest-framework-json-api/commit/389db446457c99c1e3d2d1cf35ed2eccbfaac60d)

Please check if this solves your use case.

**Comment by jerel** [comment]
@pattisdr closing this based on feedback in Gitter chat room. If it was premature let me know
