### ISSUE TITLE
Analyse JSON API Version 1.1 RC 1

### ISSUE THREAD

**Issue by sliverc** [django-json-api/django-rest-framework-json-api#547]
New release candidate of JSON API specification has been released.

There is now also a changelog to be reviewed at https://jsonapi.org/#update-history

A quickly browsed through it and it seems a few small changes would be needed to be done in DJA.

Opening this issue as a task to analyze what single steps needs to be done in DJA to support 1.1. Best is to open a new each for each single task.

**Comment by n2ygk** [comment]
@sliverc Thanks for following these updates with JSON API. I've reviewed the release notes and created an issue for each item.  Note that it is not yet a release but a release candidate, so there's always some chance there will be further changes before the official release. Now is a good time to review these and see what work is required.

Should I create a milestone to track this? We don't necessarily have to include all these items in a new release though....

**Comment by sliverc** [comment]
from jsonapi.org:
> JSON:API v1.1 RC1 has been published! Please review and try out this upcoming version of the spec before its planned release date of January 31, 2019.

Keeping this in mind we can discuss the different issues in its respective issue. If there are still questions concerning specification we should raise it to the jsonapi.org in time. After this deadline has passed I guess we can implement the different issues as time permits (without having a milestone).

**Comment by auvipy** [comment]
we can start work on this now

**Comment by sliverc** [comment]
Even thought the date has passed long ago version 1.1 has not officially been released yet (hint still set on https://jsonapi.org/)

But of course it would be good to get started with those issues if someone has time at hand as the spec won't change much from what it is now.

**Comment by auvipy** [comment]
any suggestions for me on how can i update them in current code?

**Comment by sliverc** [comment]
#553 might be an easy one to start with.

**Comment by n2ygk** [comment]
FYI - JSONAPI 1.1 has reverted to a working draft so hold off on any implementation work. See https://github.com/json-api/json-api/issues/1403#issuecomment-518263298

**Comment by sliverc** [comment]
Interesting what's happening with the spec. I guess we have enough tasks at hand anyway so can easily wait... :smile: it seems though the spec might mainly change around profiles though.

**Comment by sliverc** [comment]
@n2ygk 
It seems like the JSON API spec 1.1 won't be released anytime soon. There are now quite a few 1.1 issues cluttered in our database which we cannot really resolve. I would prefer we close them and once it is clear what to implement we can always reopen them again. What do you think?

**Comment by sliverc** [comment]
Closing as explained at https://github.com/django-json-api/django-rest-framework-json-api/issues/547#issuecomment-538026511

Once JSON API spec is moving forward we need to double check which issue need to be reopened.

**Comment by auvipy** [comment]
- 2020-08-20: 1.1 Release candidate 2 released. 
  - [Extensions](https://jsonapi.org/format/1.1/#extensions) were added and the
    scope of [profiles](https://jsonapi.org/format/1.1/#profiles) were reduced
    since their introduction in RC1.
  - [Links](https://github.com/json-api/json-api/pull/1348) can be represented
    as [RFC 8288](https://tools.ietf.org/html/rfc8288)-style web links.
  - A new [`describedby`](https://github.com/json-api/json-api/pull/1447) [links member](https://jsonapi.org/format/1.1/#document-top-level)
    was added so that implementors can incorporate description documents (e.g.
    [OpenAPI](https://www.openapis.org/) or [JSON Schema](https://json-schema.org/specification.html))
    directly into their APIs.
  - [Local IDs](https://jsonapi.org/format/1.1/#document-resource-object-identification)
    were [introduced](https://github.com/json-api/json-api/pull/1244) so that a
    client can create a relationship to a resource yet-to-be created by the
    same request.

**Comment by auvipy** [comment]
We can re-open this & analyze JSON-API 1.1 RC2 and modify the related closed issues. it seems with new extensions and other overhauls it is not so far from release this time.
