### ISSUE TITLE
JSON API 1.1: cursor-pagination profile

### ISSUE THREAD

**Issue by n2ygk** [django-json-api/django-rest-framework-json-api#548]
See #547. Analyze new [cursor-pagination profile](https://jsonapi.org/format/1.1/#profiles)

**Comment by sliverc** [comment]
As far as I understand is this is rather an example and not an actual profile as JSON API is still [pagination strategy agonistc](https://jsonapi.org/format/1.1/#fetching-pagination).

I think in case of profile the only relevant issue for DJA at this point is #558

**Comment by n2ygk** [comment]
See https://github.com/json-api/json-api/blob/gh-pages/_profiles/ethanresnick/cursor-pagination/index.md which looks like cursor pagination is a registered profile.  

Profiles adds a new [profile media type parameter](https://jsonapi.org/format/1.1/#profile-media-type-parameter) and [query parameter](https://jsonapi.org/format/1.1/#profile-query-parameter), so at a minimum QueryParameterValidation would need to add this as well?

**Comment by sliverc** [comment]
OK let's leave this issue open then. I seems it duplicates #320 and I guess we should close one of those two? As this is additional profile as I understand it is it not necessarily needed to fully support JSON API 1.1 but rather an addition which an implementation might implement.

I have split up media and query parameter support #560 which will be the base once the first additional profile is implemented.

The profile change in JSON API 1.1 seems to be a fairly big change which we certainly have to have a closer look what it really involves before we implement.

**Comment by sliverc** [comment]
Closing as explained at https://github.com/django-json-api/django-rest-framework-json-api/issues/547#issuecomment-538026511

Once JSON API spec is moving forward we need to double check which issue need to be reopened.
