### ISSUE TITLE
JSON API 1.1: @-Members

### ISSUE THREAD

**Issue by n2ygk** [django-json-api/django-rest-framework-json-api#549]
See #547. Anaylze [@-Members](https://jsonapi.org/format/1.1/#document-member-names-at-members)

**Comment by sliverc** [comment]
As I see it this should only affect the DJA parser and should be straight forward to implement.

**Comment by sliverc** [comment]
Closing as explained at https://github.com/django-json-api/django-rest-framework-json-api/issues/547#issuecomment-538026511

Once JSON API spec is moving forward we need to double check which issue need to be reopened.
