### ISSUE TITLE
JSON API 1.1: error object 'type' links

### ISSUE THREAD

**Issue by n2ygk** [django-json-api/django-rest-framework-json-api#550]
See #547. Analyze error-object [type links](https://jsonapi.org/format/1.1/#error-objects)

**Comment by n2ygk** [comment]
See also #431. In general the existing code does not return comprehensive JSON API error objects.

**Comment by sliverc** [comment]
At this point I do not see a case where error links could be relevant for DJA internally.

For DJA users it could be of interest to return error links of specific errors. An implementation could allow to raise a specific exception with a link which is then rendered accordingly.
Of all the JSON API 1.1 specification this has rather low priority in my opinion.

**Comment by sliverc** [comment]
potentially related to #399

**Comment by sliverc** [comment]
Closing as explained at https://github.com/django-json-api/django-rest-framework-json-api/issues/547#issuecomment-538026511

Once JSON API spec is moving forward we need to double check which issue need to be reopened.
