### ISSUE TITLE
JSON API 1.1: query parameters

### ISSUE THREAD

**Issue by n2ygk** [django-json-api/django-rest-framework-json-api#551]
See #547. Analyze updated content about [query parameters](https://jsonapi.org/format/1.1/#query-parameters).

**Comment by sliverc** [comment]
in my opinion is DJA already compliant to this json api specification.

**Comment by sliverc** [comment]
Closing as explained at https://github.com/django-json-api/django-rest-framework-json-api/issues/547#issuecomment-538026511

Once JSON API spec is moving forward we need to double check which issue need to be reopened.
