### ISSUE TITLE
JSON API 1.1: status codes for specific responses

### ISSUE THREAD

**Issue by n2ygk** [django-json-api/django-rest-framework-json-api#552]
See #547. Analyze newly-documented status codes for specific responses: https://github.com/json-api/json-api/pull/1036 & https://github.com/json-api/json-api/pull/1029

**Comment by sliverc** [comment]
* Delete of nonexistent resource should already lead to a 404 as this is the default behavior of DRF.  Test needs to be added though
* Referencing an nonexistent related resource currently leads to an 400 error. This will need to be changed (might be a bit tricky...)

**Comment by sliverc** [comment]
Closing as explained at https://github.com/django-json-api/django-rest-framework-json-api/issues/547#issuecomment-538026511

Once JSON API spec is moving forward we need to double check which issue need to be reopened.
