### ISSUE TITLE
JSON API 1.1: Always return 'included' when 'include' requested

### ISSUE THREAD

**Issue by n2ygk** [django-json-api/django-rest-framework-json-api#553]
See #547. Analyze whether we always return `included` when `include` requested. https://github.com/json-api/json-api/pull/1236

**Comment by sliverc** [comment]
This doesn't seem to be the case at this point.

See https://github.com/django-json-api/django-rest-framework-json-api/blob/master/rest_framework_json_api/renderers.py#L661

**Comment by sliverc** [comment]
Closing as explained at https://github.com/django-json-api/django-rest-framework-json-api/issues/547#issuecomment-538026511

Once JSON API spec is moving forward we need to double check which issue need to be reopened.
