### ISSUE TITLE
JSON API 1.1: CamelCased names

### ISSUE THREAD

**Issue by n2ygk** [django-json-api/django-rest-framework-json-api#554]
See #547. Analyze [recommendation that we SHOULD use CamelCased names](https://jsonapi.org/recommendations/#naming).

**Comment by sliverc** [comment]
I see three different options to implement this:

1. add recommendation to documentation to set `JSON_API_FORMAT_FIELD_NAMES` and `JSON_API_FORMAT_TYPES` to `camalize`. This is fairly simple and is backwards compatible
2. Change default field format from `underscore` to `camelize`. Not backwards compatible but easy for new users to follow json api recommendation.
3. Drop support to have custom formatting and always `camelize`. This would remove complexity of DJA but as it is only a recommendation it would also restrict DJA users.

I tend towards first option.

**Comment by sliverc** [comment]
Closing as explained at https://github.com/django-json-api/django-rest-framework-json-api/issues/547#issuecomment-538026511

Once JSON API spec is moving forward we need to double check which issue need to be reopened.
