### ISSUE TITLE
What format is expected when doing a post?

### ISSUE THREAD

**Issue by philippeluickx** [django-json-api/django-rest-framework-json-api#56]
I am trying to migrate to this json api format, when using rest_auth https://github.com/Tivix/django-rest-auth

Everything works with the standard DRF, but blocks when using drf-json-api. I tracked it down to having an empty self.request.DATA in my post method, which leads me to think that I might have to encapsulate my post request data?

Anyhow, some docs on this would be great!

**Comment by jerel** [comment]
This is the test coverage we currently have on POST which tests against the standard JSON API Create/Update format: https://github.com/django-json-api/django-rest-framework-json-api/blob/develop/example/tests/test_model_viewsets.py#L153-L181

**Comment by philippeluickx** [comment]
That seems to do the trick, thanks for the pointer! Just wondering if it would make sense and would be possible to have meaningful error messages when formatting is incorrect?

**Comment by jsenecal** [comment]
I might add that most of the expected behavior is meant to follow the JSON:API Spec. In regards of posting, your login endpoint expect posted data to be like the creation of a resource, the info on that matter is over here: http://jsonapi.org/format/#crud

**Comment by philippeluickx** [comment]
@jsenecal Thanks for the pointer to the docs!
What got me confused here is that this is not an actual CRUD operation, so there is no type with attributes... I had tried to simply add my data in the {data: {a: b, c: d}} structure, but in order to have it work it has to be {data: {attributes: {a: b, c: d}}}
