### ISSUE TITLE
SerializerMethodResourceRelatedField does not include meta section in relationship response.

### ISSUE THREAD

**Issue by BillBrower** [django-json-api/django-rest-framework-json-api#572]
`SerializerMethodResourceRelatedField` does not include a meta section in the relationship response like `ResourceRelatedField` does. This doesn't make sense, because `SerializerMethodResourceRelatedField` extends `ResourceRelatedField` and both seem to return every related record in the response (for the record I've only tried with a little over a thousand related records).

So for example if you had an ObjectA with a has many relationship with ObjectB:

```python
    objectbs = SerializerMethodResourceRelatedField(
        source='get_objectbs',
        many=True,
        model=ObjectB,
        read_only=True
    )

    def get_objectbs(self, obj):
        return ObjectB.objects.filter(objecta=obj)
```

then your response would look like:

```json
"relationships": {
  "objectb": {
   "data": [...]
  }
}
```

instead of:

```json
"relationships": {
  "objectb": {
    "meta": {
      "count": 2
    },
   "data": [...]
  }
}
```

**Comment by sliverc** [comment]
Thanks for reporting. This seems to be inconsistent. 

At a first glance:
[Source code](https://github.com/django-json-api/django-rest-framework-json-api/blob/master/rest_framework_json_api/renderers.py#L202) where `SerializerMethodResourceRelatedField` doesn't seem to pass through as `SerializerMethodResourceRelatedField` doesn't resolve into `ManyRelatedField`

PR is welcome.
