### ISSUE TITLE
POST request with include query parameter

### ISSUE THREAD

**Issue by ro70** [django-json-api/django-rest-framework-json-api#596]
if I do a
```POST /x/?include=y```
request I receive the desired instance of `y` included.

Now I'd like to update the instance `y` during the creation of `x` (in the `XViewSet(rest_framework_json_api.viewsModelViewSet).perform_create()` method). The `included` list in the response does still contain the instance `y` with the old, unmodified values. Is it somehow possible to pass the modified instance to the response?

**Comment by sliverc** [comment]
Could you add a full example of `perform_create` to see where the problem could be?

**Comment by ro70** [comment]
@sliverc Thanks for your reply. It's more or less something like
```
class XViewSet(ModelViewSet):
    queryset = models.X.objects.all()
    serializer_class = serializers.XSerializer

    def perform_create(self, serializer):
        data = self.request.data
   
        y = models.X.objects.get(pk=data['y']['id'])
        utils.do_something_with_y(y)
        y.save()

        serializer.save(
            owner=self.request.user,
            ... 
       )
```

**Comment by sliverc** [comment]
I do not see how this should be a problem.

Do you think you can add a test case to https://github.com/django-json-api/django-rest-framework-json-api/blob/master/example/tests/test_model_viewsets.py reproducing this issue?

**Comment by ro70** [comment]
I didn't manage to write a test. But I added
```
    def perform_update(self, serializer):
        entry = self.get_object()
        comment = entry.comments.first()
        comment.body += 'AAA'
        comment.save()
        serializer.save()
```
to the `EntryViewSet`. Then I made a `PUT /entries/1` request. The response was
```
{
    "data": {
        "type": "posts",
        "id": "1",
        ...
    },
    "included": [
        {
            "type": "comment",
            "id": "1",
            "attributes": {
                "body": "Love this article!AAA"
            },
            ...
```
Perfect! As it should be. Well my case seems a bit more complicated. Among other things I use  [polymorphic  classes](https://github.com/apirobot/django-rest-polymorphic). Could that be the reason why it does not work for me?

**Comment by sliverc** [comment]
I haven't used polymorphic classes myself but I cannot see how this could be a problem in this case.

The test example above uses a M2M relations. Have you tried a OneToMany relation to reproduce the issue (such is actually added as a property on the instance)? 

A `instance.refresh_from_db()` at the end of your custom perform_update resp. perfrom_create. code might also solve your problem.

**Comment by ro70** [comment]
@sliverc A `refresh_from_db()` on the "serializer.saved" instance did it. A big thank you. (In your example app this refresh does not seem necessary, neither in the `perform_update` nor in the `perform_create` method for m2m or one2many relations.)
