### ISSUE TITLE
RelatedMixin get_serializer_class AttributeError View object has not kwargs in line 139

### ISSUE THREAD

**Issue by sandrabg86** [django-json-api/django-rest-framework-json-api#603]
When it is called `view.get_serializer_class` if view inherid from `rest_framework_json_api.ModelViewSet` then get an error in `rest_framework_json_api/views.py` line 139, because View object has not attribute kwargs at this point.

**Trace** 
rest_framework_json_api.renderersJSONRenderer().render -> line 541
rest_framework_json_api.utils.get_resource_name -> line 61
rest_framework_json_api.views.RelatedMixin.get_serializer_class. -> 139

**Comment by sliverc** [comment]
kwargs is usually set during request response cycle representing url keyword arguments.

Could it be that this error only happens during unit testing? If so the test needs to make sure that kwargs are set. Otherwise a code example would be good to figure out what's going on.

**Comment by sandrabg86** [comment]
Yes, this error happens when I am runing unit testing.

**Comment by sliverc** [comment]
what does `self.view()` exactly do?

A view cannot be simply instiantiated for testing but needs to be setup with a request. 

See [example](https://www.django-rest-framework.org/api-guide/viewsets/#example) how to get view from a viewset and 
[testing guideline](https://www.django-rest-framework.org/api-guide/testing/) how to get request to build a setup view.

This way the view has kwargs set (which is always done when rendering it in DRF)

Hope this helps?

**Comment by sliverc** [comment]
As there hasn't been any feedback I assume this issue has been solved so closing. If not please comment.
