### ISSUE TITLE
Deprecation warning in renderers.py

### ISSUE THREAD

**Issue by Yelinz** [django-json-api/django-rest-framework-json-api#613]
```
.../python3.7/site-packages/rest_framework_json_api/renderers.py:5: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    from collections import Iterable, OrderedDict, defaultdict
```

Python 3.7 throws a deprecation warning for the collections import in renderers.py

**Comment by sliverc** [comment]
@Yelinz Thanks for reporting. It seems only the Iterable has moved to collections.abc. Such is also referenced in relations.py and views.py. 

We could fix this similar as done in DRF where a compat.py is created which does the collections import correctly.

See e.g. https://github.com/encode/django-rest-framework/pull/6473/files

Would you have time to open a PR?

**Comment by Yelinz** [comment]
When I have some spare time I can do it.
