### ISSUE TITLE
remove ModelViewSet PUT/update() method?

### ISSUE THREAD

**Issue by n2ygk** [django-json-api/django-rest-framework-json-api#614]
DJA uses DRF's viewsets.ModelViewset which includes both PUT (update()) and PATCH (partial_update()) methods. However,  the JSONAPI spec only defines [PATCH](https://jsonapi.org/format/#crud-updating). DJA allows the PUT method. This becomes more apparent when using the new DRF openapi schema generator since it wants to document the PUT method. While DJA implements PUT identically to PATCH, it might be better to not expose this method as the PUT [semantics](https://tools.ietf.org/html/rfc7231#section-4.3.4) defines a full replacement, which DJA's PUT does not do, since it's just implementing [PATCH](https://tools.ietf.org/html/rfc5789).

I'm not sure exactly where the PUT method gets defined but I think the change is to replace DRF's ModelViewSet with a DJA-specific version that replaces
DRF's `mixins.UpdateModelMixin` with one that doesn't define it. 

https://github.com/django-json-api/django-rest-framework-json-api/blob/de7021f9e011615ce8b65d0cb38227c6c12721b6/rest_framework_json_api/views.py#L189-L192

You can see this by doing an `OPTIONS http://localhost:8000/blogs/1` as in this example:
```json
{
    "data": {
        "name": "Blog Instance",
        "description": "",
        "renders": [
            "application/vnd.api+json",
            "text/html"
        ],
        "parses": [
            "application/vnd.api+json",
            "application/x-www-form-urlencoded",
            "multipart/form-data"
        ],
        "allowed_methods": [
            "GET",
            "PUT",
            "PATCH",
            "DELETE",
            "HEAD",
            "OPTIONS"
        ],
        "actions": {
            "PUT": {
                "name": {
                    "type": "String",
                    "required": true,
                    "read_only": false,
                    "write_only": false,
                    "label": "Name",
                    "max_length": 100
                },
                "tags": {
                    "type": "GenericField",
                    "relationship_type": "OneToMany",
                    "relationship_resource": "taggedItem",
                    "required": false,
                    "read_only": true,
                    "write_only": false,
                    "label": "Tags",
                    "child": {
                        "type": "Serializer",
                        "required": false,
                        "read_only": true,
                        "write_only": false,
                        "children": {
                            "tag": {
                                "type": "Slug",
                                "required": true,
                                "read_only": false,
                                "write_only": false,
                                "label": "Tag",
                                "max_length": 50
                            }
                        }
                    }
                },
                "copyright": {
                    "type": "GenericField",
                    "required": false,
                    "read_only": true,
                    "write_only": false,
                    "label": "Copyright"
                }
            }
        }
    }
}
```

**Comment by sliverc** [comment]
I agree this is a bug as it doesn't follow the specification. Also see [FAQ](https://jsonapi.org/faq/#wheres-put).

I haven't tested this but would it not work if we overwrite `update` and raise a `AttributeError` when partial in kwargs is False?

Something like this:
```python
def update(self, request, *args, **kwargs):
  if not kwargs.get('partial', False):
    raise AttributeError()
  return super().update(self, request, *args, **kwargs)
```

Needs to be tested whether this works.
