### ISSUE TITLE
When using the ListCreateApiView, the action has to be differentiated

### ISSUE THREAD

**Issue by schtibe** [django-json-api/django-rest-framework-json-api#62]
I had the problem that I couldn't use the generics.ListCreateAPIView for both, getting a list of all models and posting a new model.

If I set the action to 'list', I could correctly deliver a JsonAPI list of all the models; but when posting, the JSONRenderer had a problem on line 63 (`results = (data["results"] if isinstance(data, dict) else data)`) because there is no 'results' in the data dict. 

However, when I removed the `action = 'list'` from my view, the post was done correctly, but the list of models wasn't in JsonAPI.

I now set up my view like this:

    class AddressList(generics.ListCreateAPIView):
        """List of addresses"""
        serializer_class = models.AddressSerializer

        def get(self, request, *args, **kwargs):
            self.action = 'list'
            return super(AddressList, self).get(request, *args, **kwargs)

            [...]

which works, but I wonder, if this is the best way to go...

**Comment by jsenecal** [comment]
what is your DRF configuration? are you using any paginator?

**Comment by jsenecal** [comment]
Sorry, @leifhauks, my colleague, made me understand your request. What does your post/create method looks like?

**Comment by jsenecal** [comment]
And why arent you using the DRF ModelViewSet for what you need ?

**Comment by schtibe** [comment]
Quite simply because I didn't know about ModelViewSet. I'm very new to all of this.
Thanks and sorry for the fuss.

**Comment by jsenecal** [comment]
No problem @schtibe ;)

**Comment by leifurhauks** [comment]
@schtibe , no worries! also, if you don't need all the CRUD actions (e.g. if you only need list, create, and retrieve but don't need update or delete) you can compose a custom viewset using DRF's mixins:
http://www.django-rest-framework.org/api-guide/viewsets/#custom-viewset-base-classes
