### ISSUE TITLE
get_related_resource_type failing for polymorphic serializers

### ISSUE THREAD

**Issue by favll** [django-json-api/django-rest-framework-json-api#621]
We have run into a problem where DRF JSON API resolves the wrong related resource type when trying to include a resource using a polymorphic serializer. Specifically, DRF JSON API will resolve the base model instead of the inherited model.

Below is an abbreviated example for the issue we are running into. In the following example `utils.get_related_resource_type` will resolve the `parent_model` to `models.Product` instead of `models.ArtProduct` (line [here](https://github.com/django-json-api/django-rest-framework-json-api/blob/eb445137ba3731b091c99e269d82adcea36b60e0/rest_framework_json_api/utils.py#L257)). Subsequently, the method will try to access `art_details` on the `parent_model` which will fail since it only exists on `models.ArtProduct` and not `models.Product` (line [here](https://github.com/django-json-api/django-rest-framework-json-api/blob/eb445137ba3731b091c99e269d82adcea36b60e0/rest_framework_json_api/utils.py#L264)). 

A proposed fix would be to resolve the `parent_model` by checking if the `parent_serializer` is a polymorphic serializer and resolving the `parent_model` with something along the lines of: 
`parent_serializer.get_polymorphic_serializer_for_instance(parent_serializer.instance).Meta.model`

If desired, I can provide further clarification and prepare a PR. 

```python3
class ArtProductSerializer(serializers.ModelSerializer):
    price = MoneyField(max_digits=19, decimal_places=4)

    included_serializers = {
        "art_details": ArtDetailSerializer,
    }

    class JSONAPIMeta:
        included_resources = ("art_details",)
        resource_name = "ArtProduct"

    class Meta:
        fields = (
            "id",
            "price",
            "art_details",
        )
        model = models.ArtProduct


class PolymorphicProductSerializer(serializers.PolymorphicModelSerializer):
    polymorphic_serializers = [ArtProductSerializer]

    class Meta:
        model = models.Product


class CartItemSerializer(serializers.ModelSerializer):

    included_serializers = {
        "product": PolymorphicProductSerializer,
    }

    class Meta:
        model = models.CartItem
        fields = ("id", "product")


class CartSerializer(serializers.ModelSerializer):
    included_serializers = {
        "items": CartItemSerializer,
    }

    class Meta:
        model = models.Cart
        fields = ("id", "items")
        read_only_fields = ("id", "items")

    class JSONAPIMeta:
        included_resources = ("items", "items.product")
```

**Comment by sliverc** [comment]
It would be great if you could open a PR which reproduces this error and a potential fix.

Once a reproducing test is ready it might also be clearer whether your suggested fix works or whether there are better solutions.

**Comment by ro70** [comment]
@favll Probably I ran into the same problem. Any news on this?

**Comment by David-Guillot** [comment]
@favll @ro70 did you make sure you're properly using the `PolymorphicResourceRelatedField` as indicated in [the docs](https://django-rest-framework-json-api.readthedocs.io/en/stable/usage.html#working-with-polymorphic-resources)?

Defining a polymorphic serializer is enough when using it directly for its model endpoint, but for related models, as in your example @favll , a `PolymorphicResourceRelatedField` referring to your polymorphic serializer should do the trick, i'm seeing it working right now on my own project.

**Comment by sliverc** [comment]
As there hasn't been any feedback and as of comment of @David-Guillot I assume this issue has been solved so closing. Please don't hesitate to comment if this issue still exists though.
