### ISSUE TITLE
@six gone missing with DRF 3.10.x

### ISSUE THREAD

**Issue by n2ygk** [django-json-api/django-rest-framework-json-api#629]
It looks like the upcoming DRF 3.10 release drops Py2 support and the `six` module. It used to import it here: https://github.com/encode/django-rest-framework/blob/3.9.x/rest_framework/serializers.py#L26 and it is gone in master now.

Apparently it is used only one place in DJA: https://github.com/django-json-api/django-rest-framework-json-api/blob/26e65a14b27c82b16cd393a3d5821a966464de51/rest_framework_json_api/serializers.py#L261

and must have been importing it from here: https://github.com/django-json-api/django-rest-framework-json-api/blob/26e65a14b27c82b16cd393a3d5821a966464de51/rest_framework_json_api/serializers.py#L5

"noqa" indeed!

**Comment by n2ygk** [comment]
@leo-naeka in case you want to fix this...
```
61406625 (leo-naeka 2017-06-05 22:23:17 +0200 261) @six.add_metaclass(PolymorphicSerializerMetaclass)
```

**Comment by leo-naeka** [comment]
Indeed @n2ygk, I'll take a look soon!
