### ISSUE TITLE
PyPi package name is wrong in the docs

### ISSUE THREAD

**Issue by jsenecal** [django-json-api/django-rest-framework-json-api#63]
The line
> pip install rest_framework_json_api

should be `pip install djangorestframework-jsonapi`

Either that or rename the PyPi package name to conform with the documentation.

**Comment by mtermoul** [comment]
I just tried that and I got the following error:

Downloading/unpacking djangorestframework-jsonapi
  Could not find a version that satisfies the requirement djangorestframework-jsonapi (from versions: 2.0.0-alpha.1, 2.0.0-alpha.2, 2.0.0-alpha)
Cleaning up...
No distributions matching the version for djangorestframework-jsonapi
Storing debug log for failure in /Users/mida/.pip/pip.log

**Comment by mtermoul** [comment]
Also I am a bit confused, because the master branch has a folder called:
rest_framework_ember

but on the development branch there is a folder called:
rest_framework_json_api

So are these packages the same? which one should I be using? my goal is to be able to connect to Django Rest Framework APIs from Ember using RESTAdapter.

Please let help, I am really stuck here.

Thanks.

**Comment by jsenecal** [comment]
While my system installs this without issues, try installing a specific version:
>pip install djangorestframework-jsonapi==2.0.0-alpha.2

**Comment by jsenecal** [comment]
@mtermoul please go in gitter: https://gitter.im/django-json-api/django-rest-framework-json-api

**Comment by mtermoul** [comment]
Wow!!! that worked I got:
Successfully installed djangorestframework-jsonapi
Cleaning up...

One last question, I am trying the connect to Django Rest Framework API from Ember using RESTAdapter. Would this package help?

Alos I am using the APIView from the DRF side... anything else I should be paying attention to? because my ember project data is empty!!!

**Comment by jsenecal** [comment]
I am in no way an Ember specialist (never ever touched it actually) @jerel might be a better help there. But the new JSONApi is meant to be natively compatible with Ember-data if I am not mistaken.

**Comment by mtermoul** [comment]
Sorry 

After installing successfully, I am getting this error when I try to browse the REST API

TypeError at /api/celebs/
list indices must be integers, not unicode
Request Method:	GET
Request URL:	http://127.0.0.1:8001/api/celebs/
Django Version:	1.8.3
Exception Type:	TypeError
Exception Value:	
list indices must be integers, not unicode
Exception Location:	/Users/mida/.virtualenvs/spdial/lib/python2.7/site-packages/rest_framework_json_api/utils.py in extract_id, line 181
Python Executable:	/Users/mida/.virtualenvs/spdial/bin/python
Python Version:	2.7.6
Python Path:	
['/Users/mida/Documents/betaworks/speed_dial',
 '/Users/mida/.virtualenvs/spdial/lib/python27.zip',
 '/Users/mida/.virtualenvs/spdial/lib/python2.7',
 '/Users/mida/.virtualenvs/spdial/lib/python2.7/plat-darwin',
 '/Users/mida/.virtualenvs/spdial/lib/python2.7/plat-mac',
 '/Users/mida/.virtualenvs/spdial/lib/python2.7/plat-mac/lib-scriptpackages',
 '/Users/mida/.virtualenvs/spdial/Extras/lib/python',
 '/Users/mida/.virtualenvs/spdial/lib/python2.7/lib-tk',
 '/Users/mida/.virtualenvs/spdial/lib/python2.7/lib-old',
 '/Users/mida/.virtualenvs/spdial/lib/python2.7/lib-dynload',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages',
 '/Users/mida/.virtualenvs/spdial/lib/python2.7/site-packages',
 '/Users/mida/Documents/betaworks/speed_dial']


I also changed the settings based on the docs as the following:

REST_FRAMEWORK = {
    'PAGINATE_BY': 10,
    'PAGINATE_BY_PARAM': 'page_size',
    'MAX_PAGINATE_BY': 100,
    # DRF v3.1+
    'DEFAULT_PAGINATION_CLASS':
        'rest_framework_json_api.pagination.PageNumberPagination',
    # older than DRF v3.1
    'DEFAULT_PAGINATION_SERIALIZER_CLASS':
        'rest_framework_json_api.pagination.PaginationSerializer',
    'DEFAULT_PARSER_CLASSES': (
        'rest_framework_json_api.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser'
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework_json_api.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ),
}
