### ISSUE TITLE
Add information on how to integrate JSON API with with DRF built-in coreapi documentation

### ISSUE THREAD

**Issue by arielpontes** [django-json-api/django-rest-framework-json-api#638]
I followed the instructions in the DRF docs to generate documentation for my project but it doesn't show the correct expected payload format in PATCH/POST endpoints. It shows the following standard messages in all endpoints:

> The request body should be a "application/x-www-form-urlencoded" encoded object, containing the following items.

And then it shows a list of the attributes that are supported, but there is no mention of the JSON API format, which should be:

```
{
    "data": {
        "type": "ResourceType",
        "attributes": {
            ...
        }
    }
}
```

How can I customize the DRF documentation so that it shows the proper format and content-type expected?

**Comment by n2ygk** [comment]
DRF is deprecating coreapi and replacing it with openapi. I’ve been working
on prototyping openapi support for DJA and have had to submit a number of
PRs to DRF to enable this. I’m close to being ready to share this for
review and hope to be able to do so soon.

**Comment by n2ygk** [comment]
@arielpontes Here's a preview of what I've been working on: https://columbia-it-django-jsonapi-training.readthedocs.io/en/latest/documenting-api.html

**Comment by sliverc** [comment]
@n2ygk Could we close this issue in favour of #604?

**Comment by n2ygk** [comment]
Closing as this is covered by #604
