### ISSUE TITLE
Adapt SerializerMethodResourceRelatedField behaviro to DRF SerializerMethodField

### ISSUE THREAD

**Issue by David-Guillot** [django-json-api/django-rest-framework-json-api#639]
Hi there,

[DRF's SerializerMethodField](https://github.com/encode/django-rest-framework/blob/master/rest_framework/fields.py#L1827-L1868) makes it easy to avoid defining a method name as it auto-computes a method name by prepending `get_` to the field source.

With DJA's SerializerMethodResourceRelatedField, one *has to* define the `source` attribute as without it, the method name conflicts with the field name (i'm not sure to be crystal-clear here :confused: ).

I find it:

* Annoying (in a very minor way)
* Not consistent with what developers are used to with vanilla DRF

So if you agree with me, i can probably open a PR that adds this bit of sugar (although i'm not sure to understand all the implications for the read/write use case, but i can give it a try).

So what do you think?

**Comment by sliverc** [comment]
I see your point and I think it would be great if `SerializerMethodResourceRelatedField` could be consistent with `SerializerMethodField`. It would be great if you could give it a try.

Such a change might be related to #632

**Comment by auvipy** [comment]
does this need to be worked yet?

**Comment by sliverc** [comment]
This hasn't been worked on yet and any help is appreciated.
