### ISSUE TITLE
missing DjangoFilterBackend.get_schema_operation_parameters()

### ISSUE THREAD

**Issue by n2ygk** [django-json-api/django-rest-framework-json-api#644]
Upstream DRF's `generateschema` requires filter backends to have a `get_schema_operation_parameters()` in order to generate a query parameter schema. This is missing from DjangoFilterBackend. This is a pre-req for #604.

**Comment by n2ygk** [comment]
Missing in upstream https://github.com/carltongibson/django-filter/issues/1083

**Comment by sliverc** [comment]
I just wanted to write the same thing... :smile: Can we close this issue then and reference upstream issue in #604 ?

**Comment by n2ygk** [comment]
moved to #604.

**Comment by n2ygk** [comment]
Actually I'm going to reopen this as the upstream still needs DJA customization for wrap the filter names in `filter[]`
