### ISSUE TITLE
POST with nested relationships isn't functional

### ISSUE THREAD

**Issue by adcooley** [django-json-api/django-rest-framework-json-api#65]
DRF expects nested objects to be dictionaries, and we're passing them as Strings (the `id`)

<img width="514" alt="screen shot 2015-08-18 at 5 46 34 pm" src="https://cloud.githubusercontent.com/assets/573274/9346400/1e7a8c32-45d1-11e5-8380-d9021703e37f.png">

Doesn't appear there are any tests for this either. Anyone working this? I'll throw up a PR if not.

**Comment by jsenecal** [comment]
I was working on this recently but got sidetracked - If you want to contribute feel free to do so, this project is very active and we review and accept PRs quite fast.

Thanks for your help !

**Comment by jsenecal** [comment]
@adcooley I'm currently working on this - have you done any work regarding that issue ?

**Comment by jsenecal** [comment]
@adcooley commit d654c757e9c034961261b642987c86a8affc2392 now makes shure that the data is properly sent to the parser - It also requires that a compatible field must be configured to parse the resource identifier objects.

We will now close this issue - Feel free to let us know if you think this is unjustified.
