### ISSUE TITLE
Cleaning up code for release 3.0.0

### ISSUE THREAD

**Issue by sliverc** [django-json-api/django-rest-framework-json-api#662]
DRF 3.10 is cleaning up its code base quite a bit so I suggest we also take the opportunity to clean up DJA as well by planning a major release 3.0.0

Following steps would I see:
* releasing 2.8.0 (notes to be the last release for Python 2.7, 3.4 and DRF <3.9)
* dropping support for Python 2.7 and 3.4 (#658)
* dropping support for Django Filter 1.1
* dropping support for all DRF versions <3.9
* remove all DJA deprecated code
* solving DRF deprecation issue (like #657 and others)

This version of course will only be released once DRF 3.10 is as well.

@n2ygk What do you think? If we agree on the steps I hope to find some time to work on this (starting with releasing 2.8.0)

**Comment by n2ygk** [comment]
Sounds like a plan. I’ll be away for the next 10 days or so but then can
put in some time.
