### ISSUE TITLE
Automated testing

### ISSUE THREAD

**Issue by abdulhaq-e** [django-json-api/django-rest-framework-json-api#67]
I have made a pull request https://github.com/django-json-api/django-rest-framework-json-api/pull/66 in which I included automated testing. This will hopefully satisfy the requirement for the v2.0 roadmap https://github.com/django-json-api/django-rest-framework-json-api/issues/40. A few notes regarding the PR:

1- I have used `pytest` as the test tool. It's better imo than Django Testing. The original tests have not been touched as `py.test` is compatible with them. Nonetheless, if you don't like it, automation can be done without it and I can edit the PR (see the examples on the pytest [website](http://pytest.org/latest/contents.html))

2- `pytest` is able to generate a `runtests` script which I did, so `python runtests.py` would run the tests without the user invoking `py.test` manually.

3- `Tox` has been used to test different environments. It's a great tool for such purposes and it goes well with `pytest` but it's not a necessary. (see [docs](https://tox.readthedocs.org/en/latest/)).

Now this is the worse part:

4- If we're to test a combination of `python2.7`, `python3.2`, `python3.3`, `python3.4`, `django1.6`, `django1.7`, `django1.8`, `drf2.4`, `drf3.0`, `drf3.1`, `drf3.2` Then only a handful of these tests will pass. Anything other than `python{27,33,34}, django18, drf{31,32}` will FAIL. I had a quick look at the failures, some of them are easy to fix and some are not. However, I didn't fix anything in order to follow a *branch per feature* process.

Finally, thanks to [drf-json-api](https://github.com/kevin-brown/drf-json-api) as I got the idea for automated testing from it. That project is **identical** to this but this is more mature and active and the code is quite clean (despite the fact that the above tests **all** work in *drf-json-api* excluding `drf2.4`) . Sad fragmentation in OSS.

**Comment by abdulhaq-e** [comment]
I've enabled all the other tests in the second commit.

**Comment by jerel** [comment]
Thanks for this @abdulhaq-e! I've merged your code to branch [feature/test-all-versions](/django-json-api/django-rest-framework-json-api/tree/feature/test-all-versions) and once all tests are passing on that branch we can merge it to develop. Anybody that contributes to test fixes should preferably open their Pull Request against that branch

**Comment by jerel** [comment]
@abdulhaq-e thanks! Your code has been merged to the `develop` branch. On a different PR I believe you mentioned adding more tests... do you already have some that make use of relationships in pytest/factoryboy fixtures? I'm new to factoryboy so if you already have some tests that could help me get up to speed quickly

**Comment by abdulhaq-e** [comment]
@jerel Sorry for the delay, PR https://github.com/django-json-api/django-rest-framework-json-api/pull/100 has a factory with relationships.

I'm new to pytest/factoryboy as well and I'm still trying to get a hang of it.
