### ISSUE TITLE
Use extra requires to seperate optional features django-filter and polymorphic

### ISSUE THREAD

**Issue by sliverc** [django-json-api/django-rest-framework-json-api#674]
The optional features (Polymorphic and Django filter) should define their dependencies as extra.

Currently this is only done as test requires but actual users won't have enforced minimum requirements.

Once this is done a user can simply add following into their requirements to properly activate an optional feature:

```
djangorestframework-jsonapi[django-filter] == 2.8.0
```

see 
https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies

**Comment by n2ygk** [comment]
@sliverc should this be done using something similar to DRF's [compat.py](https://github.com/encode/django-rest-framework/blob/master/rest_framework/compat.py)

**Comment by n2ygk** [comment]
@sliverc I've been staring at this for a bit... One issue is that I want to have the following extra-requires but one of them has it's own Django version constraints:

`django-oauth-toolkit>=1.2.0` only when `django>=2`. If `django>=1.11,<2`, then `django-oauth-toolkit>=1.1,<1.2` -- but my `TokenMatchesOASRequirements` is only implemented in DOT 1.2, so DOT not even need for 1.1 (I suppose I could back port it...). You can see this in tox.ini/.travis.yml changes I've made in #689.

I'm not sure if setup.py's `extra_requires` can be customized based on Django version. Do you know if it can?

**Comment by sliverc** [comment]
I don't think this is possible. However #689 will need some discussion also around the oauth feature.

This shouldn't affect implementing this issue for `django-filter` and `django-polymorphic` though. And I am sure for #689 we will find a suitable option.
