### ISSUE TITLE
Using a non primary key column for the id attribute

### ISSUE THREAD

**Issue by charlieallatson** [django-json-api/django-rest-framework-json-api#675]
I have a use case where my model has a normal primary key which is an integer but I don't want to expose this value to consumers of the api. Instead I want the id attribute to be a separate column which is a uuid. Is this something this project could support?
My proposal would be to have a meta class defined on the model which tells us to use a different field rather than the primary key.

**Comment by sliverc** [comment]
That is currently not possible and you would have to make the UUID your primary key.

Also see #155 where this issue is being discussed.

Closing this issue as duplicate.
