### ISSUE TITLE
Json-API in combination of django-rest-framework-jwt

### ISSUE THREAD

**Issue by schtibe** [django-json-api/django-rest-framework-json-api#68]
In my unit tests, when I do a post, I get the following error:

    ======================================================================
	ERROR: test_get_one_vehicletype_in_french (masterdata.tests.VehicleTypeTest)
	----------------------------------------------------------------------
	Traceback (most recent call last):
	  File "/usr/src/app/cardispo2/masterdata/tests.py", line 206, in setUp
		super(VehicleTypeTest, self).setUp()
	  File "/usr/src/app/cardispo2/cardispo2/test_helper.py", line 83, in setUp
		self.client.login(username='tester', password='blabla')
	  File "/usr/src/app/cardispo2/cardispo2/test_helper.py", line 57, in login
		response = self.post('/api/v1/auth/login', {"username": username, "password": password})
	  File "/usr/local/lib/python3.4/site-packages/rest_framework/test.py", line 168, in post
		path, data=data, format=format, content_type=content_type, **extra)
	  File "/usr/local/lib/python3.4/site-packages/rest_framework/test.py", line 89, in post
		data, content_type = self._encode_data(data, format, content_type)
	  File "/usr/local/lib/python3.4/site-packages/rest_framework/test.py", line 64, in _encode_data
		ret = renderer.render(data)
	  File "/usr/local/lib/python3.4/site-packages/rest_framework_json_api/renderers.py", line 36, in render
		resource_name = utils.get_resource_name(renderer_context)
	  File "/usr/local/lib/python3.4/site-packages/rest_framework_json_api/utils.py", line 32, in get_resource_name
		view = context.get('view')
	AttributeError: 'NoneType' object has no attribute 'get'

If you look at the last three steps in the trace, there is `ret = renderer.render(data)` which calls `rest_framework_json_api.JSONRenderer.render` without a `renderer_context` argument. It then passes None (default value) to `rest_framework_json_api.utils.get_resource_name` where it tries to call `view = context.get('view')` on None... which of course can't work.

My DRF settings:

	REST_FRAMEWORK = {
		'PAGINATE_BY': 30,
		'PAGINATE_BY_PARAM': 'page_size',
		'MAX_PAGINATE_BY': 100,
		#'EXCEPTION_HANDLER': 'rest_framework_json_api.exceptions.exception_handler',
		'DEFAULT_PAGINATION_CLASS':
			'rest_framework_json_api.pagination.PageNumberPagination',
		'DEFAULT_PARSER_CLASSES': (
			'rest_framework_json_api.parsers.JSONParser',
			'rest_framework.parsers.MultiPartParser',
		),
		'DEFAULT_RENDERER_CLASSES': (
			'rest_framework_json_api.renderers.JSONRenderer',
			'rest_framework.renderers.BrowsableAPIRenderer',
		),
		'TEST_REQUEST_RENDERER_CLASSES': (
			'rest_framework_json_api.renderers.JSONRenderer',
		),
		'DEFAULT_AUTHENTICATION_CLASSES': (
			'rest_framework_jwt.authentication.JSONWebTokenAuthentication',
		),
		'DEFAULT_PERMISSION_CLASSES': (
		    'rest_framework.permissions.IsAuthenticated',
		),
		'EXCEPTION_HANDLER': 'cardispo2.exceptions.custom_exception_handler',
		'TEST_REQUEST_DEFAULT_FORMAT': 'json'
	}

**Comment by jsenecal** [comment]
@schtibe I think this issue is occurring because you are sending username and password in the incorrect format. See [here](http://jsonapi.org/format/#crud)
 
I personally use https://github.com/GetBlimp/django-rest-framework-jwt and I prefer to submit and retrieve jwt related stuff in the application/json format.

**Comment by schtibe** [comment]
@jsenecal I actually could get it working by removing TEST_REQUEST_RENDERER_CLASSES  - almost. But I think, the current problem I have is not a problem of the json-api implementation, as I found that other people have the same problem too: https://github.com/GetBlimp/django-rest-framework-jwt/issues/127

**Comment by jsenecal** [comment]
Hmm, I see - let us know if you get any progress there :)

**Comment by schtibe** [comment]
I think I have a content negotiation problem, since the JWT data should be plain json and the api data jsonapi.

Depending on the order of of the parsers and renderers in settings.py (I currently have both, rest_framework.renderers/parsers and rest_framework_json_api.renderers/parsers) and accept headers I can either get
* all of my unit tests working but not the JWT-Auth request (testing with curl)
or
* the JWT-Auth-Request but not the unit tests **except** the get requests

working.

Since you're saying "I prefer to submit and retrieve jwt related stuff in the application/json format." I suspect you know the correct combination of configuration and Accept headers (maybe content-type too?) :) 

Sorry for being a bit off topic here.

**Comment by jsenecal** [comment]
@schtibe sorry for the long delay, I dont know if you managed to get this working but what I do is register the default JSONRenderer and parser and set the appropriate accept/content headers.

It is most likely something that could be done as well in your tests.

**Comment by schtibe** [comment]
@jsenecal no problem. Currently I'm using a custom negotiator that explicitly selects the jsonapi renderer and parsers.

**Comment by jsenecal** [comment]
Shall we close this then?

**Comment by jerel** [comment]
I'm closing this since it appears to be resolved. If that's not the case let me know.

**Comment by schtibe** [comment]
Sorry, yes!
