### ISSUE TITLE
Changing ids while using custom serializer.

### ISSUE THREAD

**Issue by ro70** [django-json-api/django-rest-framework-json-api#682]
Hello

I use the django-json-api and have a problem with a custom serializer. The following code is a simplified version but should describe the issue.

In the BookSerializer there is a a custom PublicTagSerializer:
```
class BookSerializer(ModelSerializer):
   tags = PublicTagSerializer(
      many=True,
      read_only=True,
   )
   ...

class Book(Model):
    tags = models.ManyToManyField(
        Tag,
        related_name='books',
        blank=True,
    )
   ...
```
And this is the PublicTagSerializer:
```
class FilterPublicListSerializer(ListSerializer):
    def to_representation(self, data):
        data = data.filter(public=True)
        data = super().to_representation(data)
        for t in data:
            print(t) # <===== Ids are still correct.
        return data

class PublicTagSerializer(ModelSerializer):
    class Meta:
        list_serializer_class = FilterPublicListSerializer
        model = models.Tag
        resource_name = 'tags'
        fields = '__all__'
```
In my database I have three tags:
```
<class 'core.models.Tag'>: {'id': 3, 'public': False, 'color': '#333333', ...}
<class 'core.models.Tag'>: {'id': 5, 'public': True, 'color': '#555555', ...}
<class 'core.models.Tag'>: {'id': 6, 'public': True, 'color': '#666666', ...}
```
The print statement above returns
```
OrderedDict([('id', 5), ('public', True), 'color': '#555555', ...])
OrderedDict([('id', 6), ('public', True), 'color': '#666666', ...])
```
what is correct.
But the `relationships` object in the response contains
```
{'type': 'tags', 'id': '3'} 
{'type': 'tags', 'id': '5'}
```
Somewhere between the `to_representation()` method of the ListSerializer and the output the ids change. Maybe someone can help me?

EDIT:
I did a trial with an `included_serializer = {'tags': PublicTagSerializer}`. The response contains the following `included` tag objects:
```
{'type': 'tags', 'id': '3', 'attributes': {'color': '#555555', 'public': True, ...}, ...}
{'type': 'tags', 'id': '5', 'attributes': {'color': '#666666', 'public': True, ...}, ...}
```
I added the `color` attribute as well. As you can see the attribute values in the response are correct. The ids are not.

**Comment by ro70** [comment]
I researched the JSONRenderer by overwriting its `render` method. Everything is ok there.
```
class MyJSONRenderer(JSONRenderer):
   def render(self, data, accepted_media_type=None, renderer_context=None):
      print(data) # <===== Ids are still correct.
      ret = super().render(data, accepted_media_type=None, renderer_context=None)
      print(ret) # <===== Ids are still correct.
      return ret
```
Where should I look further to solve the issue above?

**Comment by ro70** [comment]
It seems that I found the reason. Please have a look at https://github.com/django-json-api/django-rest-framework-json-api/blob/5650bd1e143c728b2db8f987222a0156fed8d5f5/rest_framework_json_api/renderers.py#L249-L274

`relation_instance` (L250) contains all tags:
```
<class 'core.models.Tag'>: {'id': 3, 'color': '#333333', 'public': False, ...}
<class 'core.models.Tag'>: {'id': 5, 'color': '#555555', 'public': True, ...}
<class 'core.models.Tag'>: {'id': 6, 'color': '#666666', 'public': True, ...}
```
Whereas `serialized_data` (L258) only contains the public tags (it respects my filter):
```
OrderedDict([('id', 5), ('color', '#555555'), ('public', True), ...])
OrderedDict([('id', 6), ('color', '#666666'), ('public', True), ...])
```
Now there's a problem with this loop (from L261 on):
```
for position in range(len(serializer_data)):
   nested_resource_instance = resource_instance_queryset[position]
   ...
```
The `resource_instance_queryset` list is built with the `relation_instance` value (L259) and does NOT accord with the `serialized_data` list.

**Comment by ro70** [comment]
We could do something like
```
serializer_data = resource.get(field_name)
serializer_data_ids = [sd['id'] for sd in serializer_data]
resource_instance_queryset = list(
                    filter(lambda ri: ri.id in serializer_data_ids, relation_instance))
```
Something similar is needed for included resources.

I don't know if this solution will work in any case. I don't have the necessary overview.

**Comment by sliverc** [comment]
I see the issue I am just not so sure whether overwriting `to_representation` in `ListSerializer` is the right way here.

Couldn't you use something like the following instead?

```
tags = ResourceRelatedField(many=True, queryset=Tag.objects.filter(public=True))
```

**Comment by ro70** [comment]
@sliverc Thanks for your reply. I tried your proposal
```
tags = ResourceRelatedField(many=True, queryset=Tag.objects.filter(public=True))
```
The response still includes all tags (why?):
```
{'type': 'tags', 'id': '3'}
{'type': 'tags', 'id': '5'}
{'type': 'tags', 'id': '6'}
```
In fact my filter case is a bit more complicated (I posted a simplified version above). I have to access the request user too. That's why I overwrite the `to_representation` method of the `ListSerializer`.
Furthermore I need such a serializer as `included_serializer` too.

**Comment by ro70** [comment]
@sliverc I found a solution without modifying your code. But I'm not sure if that is the real way to do it. I overwrite the `get_queryset` method of the book view. There (under certain circumstances) I prefetch the public tags. Then the `relationships` as well as the `included` only contain public tags.
```
class BookViewSet(ModelViewSet):
    queryset = models.Book.objects.all()
    serializer_class = serializers.BookSerializer

    def get_queryset(self):
        ...
        public_tags = models.Tag.objects.filter(public=True)
        prefetch = Prefetch('tags', queryset=public_tags)
        self.queryset = self.queryset.prefetch_related(prefetch)
        ...
        return self.queryset
```

**Comment by sliverc** [comment]
Yeah I was a bit too quick with my answer - overwriting `queryset` only works to restrict writing but not reading.

What I otherwise suggested is to use `SerializerMethodResourceRelatedField` which only works for reading though.

I like your solution though and this is totally legit and also avoids query explosions.

**Comment by ro70** [comment]
@sliverc Thank you very much for your help and your great work on this package!
