### ISSUE TITLE
PKOnlyObject gives unexpected "id" result in ResourceRelatedField#to_relationship

### ISSUE THREAD

**Issue by BlaiseGratton** [django-json-api/django-rest-framework-json-api#684]
I have two models configured in a one-to-many relationship (`User` and `Group`). On the User serializer, I have `group = relations.ResourceRelatedField(queryset=Group.objects)`, as well as a group serializer for `related_serializers` and `included_serializers`. I can fetch an individual user or group and include the converse resource (e.g. `/api/groups/1?include=members` and vice versa), but seeing this weird output on a serialized user:

```json
"type": "user",
"id": "1",
"attributes": {
  ...
},
"relationships": {
  "group": {
    "data": {
      "type": "group",
      "id": "Colectivo (1 members)"
    }
  }
}
```

It's calling `str()` on the actual db object, not the pk pointing to that entity. I've found this is happening in the `to_representation` method of `RelatedResourceField`, around lines 244-253 in `relations.py`. When the `value` parameter passed in is a PKOnlyObject, calling `str(value.pk)` is just using the `__str__` representation of that db entity. 

I have a bandaid fix:
```python
if type(pk) is not int: 
    pk = pk.id
```

But this feels like there is a deeper underlying issue. Either I'm setting something up incorrectly, or somehow this PKOnlyObject is being unexpectedly passed in. Would love to hear your thoughts on this!

**Comment by sliverc** [comment]
This is weird the pk of PKOnlyObject should actually be the pk and not the whole object.

Could you paste your serializers and views? This  might shed some light on the issue.

**Comment by BlaiseGratton** [comment]
@sliverc we actually figured out the cause of this issue, and it's not on your end. A property on one of the models had a getter returning a single related entity that was declared as a many-to-many in the schema, so when normally DRF would receive a key to look up in the related table, it was getting the entire object. Closing and sorry for the false alert!
