### ISSUE TITLE
How to include choices for ResourceRelatedField?

### ISSUE THREAD

**Issue by arthur-s** [django-json-api/django-rest-framework-json-api#701]
I need to get choices for ResourceRelatedField, when I make OPTIONS request. How to do it?
```python
# serializer:
self.fields['members'] = ResourceRelatedField(
    queryset=Profile.objects.filter(is_active=True),
    many=True
)
```
Current output:
```json
                "members": {
                    "type": "Relationship",
                    "relationship_type": "ManyToMany",
                    "relationship_resource": "profiles",
                    "required": false,
                    "read_only": false,
                    "write_only": false,
                    "label": "Members",
                    "initial": "[]"
                },
```
If I remove this [line](https://github.com/django-json-api/django-rest-framework-json-api/blob/master/rest_framework_json_api/metadata.py#L135), (It is what I want) I get desired output:
```json
                "members": {
                    "type": "field",
                    "required": false,
                    "read_only": false,
                    "label": "Members",
                    "relationship_type": "ManyToMany",
                    "choices": [
                        {
                            "value": "{\"type\": \"profiles\", \"id\": \"1\"}",
                            "display_name": "Arthur"
                        },
                        {
                            "value": "{\"type\": \"profiles\", \"id\": \"2\"}",
                            "display_name": "Tom"
                        }
                    ]
                },
```
Can we remove `not field_info.get('relationship_resource') and` from choices condition, or how to generate output that I want (without modifying `metadata.py`)?

**Comment by arthur-s** [comment]
I can add `include_choices` attribute to `ResourceRelatedField` and create PR.

**Comment by sliverc** [comment]
DJA excludes choices as Django REST Framework does as well.

See https://github.com/encode/django-rest-framework/issues/3751 https://github.com/encode/django-rest-framework/pull/4021 for more details why this is.

As of now it seems the way to include choices for related fields in Django REST Framework is a custom metadata class - see https://github.com/encode/django-rest-framework/pull/4021#issuecomment-224642312

As DJA we try to follow Django REST Framework standards as much as possible. So in this case if you think an option `include_choices` would be a good idea you would need to request such feature upstream. Once it is applied we can then follow up with the same option in DJA as well.

**Comment by arthur-s** [comment]
Closing this issue, since they recommend use custom meta class.
