### ISSUE TITLE
Django 3.0 support

### ISSUE THREAD

**Issue by auvipy** [django-json-api/django-rest-framework-json-api#732]
DRF 3.11 is also planning to dro django 1.11 support

**Comment by sliverc** [comment]
Django 1.11 is supported till April 2020 and in DJA we do not have any compat/workarounds etc. for it, so it don't see that we have to remove support for it until official support has ended (removing from title).

In terms of support for Django 3.0 PR is welcome which tests it with the current beta version.

**Comment by auvipy** [comment]
OK
