### ISSUE TITLE
I do not accept to put a size to the answer in the parameter size_page

### ISSUE THREAD

**Issue by johnnyvargast** [django-json-api/django-rest-framework-json-api#735]
I'm trying to put the size of the answer and it doesn't work for me.
the page_size of the StandardResultsSetPagination class is working.

libraries I use:
-  [Django REST framework JWT](https://jpadilla.github.io/django-rest-framework-jwt/)
-  [Django REST Framework JSON API](https://django-rest-framework-json-api.readthedocs.io/en/stable/index.html) 

(no parameters)
![01](https://user-images.githubusercontent.com/26862562/68792583-98756180-0619-11ea-82ba-f32a6fc64c68.png)

(with parameters)
![02](https://user-images.githubusercontent.com/26862562/68792711-eab68280-0619-11ea-97b8-4ef0b55b9459.png)

----------------------
settings.py
![03](https://user-images.githubusercontent.com/26862562/68792910-4e40b000-061a-11ea-903d-8bd06468521c.png)

pagination.py
![04](https://user-images.githubusercontent.com/26862562/68792935-57318180-061a-11ea-9fb0-846fe724605c.png)

**Comment by johnnyvargast** [comment]
Solution:
![05](https://user-images.githubusercontent.com/26862562/68796804-767fdd00-0621-11ea-9ace-a9e5330e45ac.png)


![06](https://user-images.githubusercontent.com/26862562/68796815-7aabfa80-0621-11ea-98bf-7243ee830f99.png)

**Comment by sliverc** [comment]
Thanks for posting your question and solution.

query parameter `page_size` is not a valid JSON api spec query parameter hence the error. So in case you want to use a non-standard query parameter like `page_size` overwriting `QueryParamterValidationFilter` as you did is correct. I would recommend though to use `page[size]` query parameter instead which is JSON api spec compliant. Closing this issue as solution has been proposed though.
