### ISSUE TITLE
Misleading docs on `field_name_mapping` for overriding related_field in urls

### ISSUE THREAD

**Issue by BlaiseGratton** [django-json-api/django-rest-framework-json-api#748]
In the end of [this section](https://django-rest-framework-json-api.readthedocs.io/en/stable/usage.html#relationshipview), the key and value of this dictionary should be swapped:
```python
field_name_mapping = {
    'line_items': 'order_items'
}
# should be:
field_name_mapping = {
    'order_items': 'line_items'
}
```
The language for overriding related_name in a url is a bit confusing and it took me a bit to realize this map was the problem, and wanted to save others the trouble of messing around with this configuration.

**Comment by sliverc** [comment]
Thanks for reporting. The documentation is invalid indeed. Fixing it with #756

**Comment by BlaiseGratton** [comment]
Awesome!
