### ISSUE TITLE
Dasherize field names.

### ISSUE THREAD

**Issue by ro70** [django-json-api/django-rest-framework-json-api#754]
I use the settings
```
JSON_API_FORMAT_KEYS = 'dasherize'
JSON_API_FORMAT_FIELD_NAMES = 'dasherize'
JSON_API_FORMAT_TYPES = 'dasherize'
JSON_API_PLURALIZE_TYPES = True
```

With DJA 2.8.0 all keys are converted according to the settings.
```
{
  "data": {
    "type": "users",
    "id": "1,
    "attributes": {
      "permissions": {
        "update-first-name": false,
        ...
      },
      "first-name": "a",
      ...
    },
    ...
}
```

With DJA 3.0.0 this does not happen any more (not for nested keys?). Is that intended?
```
{
  "data": {
    "type": "users",
    "id": "1",
    "attributes": {
      "permissions": {
        "update_first_name": false,  // <=======
        ...
      },
      "first-name": "a",
      ...
    },
    ...
  }
}
```

**Comment by sliverc** [comment]
Yes this is intended. `JSON_API_FORMAT_KEYS` actually got deprecated in version 2.5.0 which had this behavior and got removed in the new major release 3.0.0. Only option `JSON_API_FORMAT_FIELD_NAMES` now exists which only formats the field names.

For better understanding:
In the json api specification there are no nested fields/keys, but only an attribute field name and its value. And a value if desired can be any [valid json](https://jsonapi.org/format/#document-resource-object-attributes).

So before when DJA formatted all nested keys it actually adjusted the value. This led to invalid data see #313 and #420 for more details - basically this was a bug and not intended by the specification.

So hence `JSON_API_FORMAT_FIELD_NAMES` only formats the field names but not the keys of a value. If you still want to format the nested keys in a JSONField or DictField you would need to adjust your serializer.

Hope this explains?

**Comment by ro70** [comment]
@sliverc The description in #313 makes totally sense. I will adjust my serializer for the `permissions` dict to have dasherized keys.
