### ISSUE TITLE
DRF J-A renders nested serializers out of spec.

### ISSUE THREAD

**Issue by sapiosexual** [django-json-api/django-rest-framework-json-api#769]
Hi there.
Json-api spec states:

> Attributes may contain any valid JSON value.

>Complex data structures involving JSON objects and arrays are allowed as attribute values. However, any object that constitutes or is contained in an attribute MUST NOT contain a relationships or links member, as those members are reserved by this specification for future use.

Source: https://jsonapi.org/format/#document-resource-object-attributes

However, considering [this](https://github.com/django-json-api/django-rest-framework-json-api/blob/master/rest_framework_json_api/renderers.py#L63) and [this](https://github.com/django-json-api/django-rest-framework-json-api/blob/master/rest_framework_json_api/renderers.py#L246) any nested serializer would be rendered as resource relations even though the nested structure is not a resource.

**Comment by sliverc** [comment]
I see your point that nested serializers should actually be serialized as json value. The only thing I am a bit worried about when implementing this is backwards compatibility. If someone uses nested serializer though I guess it would only work with `ModelSerializer` with the current implementation.

So an implementation could be that nested model serializer continue to be serialized as relations but a deprecation warning will be printed that `ResourceRelatedField` should be used.
All other serializers can then render to a json value. 

This is just an idea but open for discussion and PRs.

As a side note currently when using using [JSONField](https://www.django-rest-framework.org/api-guide/fields/#jsonfield) it is possible to contain any JSON value in attribute which might be used as a workaround till a fix has been developed for this issue.

**Comment by sapiosexual** [comment]
Actually it is possible to implement two strategies and configure which one to be used in settings:
The first strategy is to leave it as it works now, and the second is to serialize any nested serializer as an attribute. 

For now, the first strategy would be set as default with a deprecation warning, and we will change this behavior in the future releases.

Or we can think about a mechanism to specify how to treat each nested serializer separately which is even more flexible.

**Comment by sliverc** [comment]
I like your first idea with a strategy setting. This way the deprecation warning can warn new users which might think nested serializer serialize to json and what they need to do if they want to. And for old users it shows them that they should adjust their code to use `ResourceRelatedField`.
