### ISSUE TITLE
Add bulk operations

### ISSUE THREAD

**Issue by danielfranca** [django-json-api/django-rest-framework-json-api#771]
Following this experimental feature of JSONApi:
https://springbot.github.io/json-api/extensions/bulk/

I came to this while trying to implement a bulk operation and finding out that it was cumbersome to implement on DJA

Especially in cases that we need to insert a huge amount of rows it is not effective to do one by one.

PS: Let me know if it is already possible or easy to implement

**Comment by sliverc** [comment]
See https://github.com/django-json-api/django-rest-framework-json-api/pull/393#issuecomment-353579753 for an example on how to implement custom bulk support. It needs to be noted though that this extension is not even considered experimental anymore but has been completely removed from the specification as discussions continue in https://github.com/json-api/json-api/pull/1197 
So if you need bulk support it will be fully custom in your implementation.

I hope example in referenced comment helps you though. Closing this issue as discussion first need to happen in the specification before we can implement anything in DJA.
