### ISSUE TITLE
Percent-encoded "[" and "]" in links

### ISSUE THREAD

**Issue by mcovalt** [django-json-api/django-rest-framework-json-api#775]
The URLs are percent-encoding brackets: 

- `[` to `%5B`
- `]` to `%5D`

This is immediately noticeable in the top-level `links` object. For example, with the example app on the `/blogs` endpoint we have:
```json
{
  "links": {
    "first": "http://127.0.0.1:8000/blogs?page%5Bnumber%5D=1",
    "last": "http://127.0.0.1:8000/blogs?page%5Bnumber%5D=1",
```
But it should be this according to the JSON:API spec:
```json
{
  "links": {
    "first": "http://127.0.0.1:8000/blogs?page[number]=1",
    "last": "http://127.0.0.1:8000/blogs?page[number]=1",
```
Possible solutions:

1. Implement a version of [`replace_query_param`](https://github.com/encode/django-rest-framework/blob/5cc6ace9c45ac42cf59d52643ab9cbb6c565d23e/rest_framework/utils/urls.py#L6-L15) that provides the `safe='[]'` parameter to [`urllib.parse.urlencode`](https://docs.python.org/3/library/urllib.parse.html#urllib.parse.urlencode) for use in [`JsonApiPageNumberPagination.build_link`](https://github.com/django-json-api/django-rest-framework-json-api/blob/master/rest_framework_json_api/pagination.py#L19-L23). This is assuming the pagination is the only place where this issue occurs.
2. Monkeypatch the standard `urllib` early in the program invocation to globally allow `safe='[]'`. This seems like an awful idea, but I'm putting it here in case someone needs a quick (and potentially dangerous) fix:
```python
from urllib import parse
parse._ALWAYS_SAFE_BYTES = parse._ALWAYS_SAFE_BYTES + b"[]"
```

Python versions: 3.8.2 and 3.7.3

**Comment by n2ygk** [comment]
Actually see the [spec](https://jsonapi.org/format/) where it says (several times):
```Note: The above example URI shows unencoded [ and ] characters simply for readability. In practice, these characters must be percent-encoded, per the requirements in RFC 3986.```
