### ISSUE TITLE
SerializerMethodResourceRelatedField breaks parent chain

### ISSUE THREAD

**Issue by glowka** [django-json-api/django-rest-framework-json-api#780]
If `SerializerMethodResourceRelatedField` is called with `many=True` and creates child field it misses call to `bind()` which would complete setting the relation between parent field and child field.

In effect it breaks the pattern that on every DRF field you can always go up the tree towards the root using `parent` attribute. 

That part of [ManyRelatedField.__init__()](https://github.com/encode/django-rest-framework/blob/master/rest_framework/relations.py#L484) is missing:

```
class ManyRelatedField:
    ...
    def __init__(self, child_relation=None, *args, **kwargs):
        self.child_relation = child_relation
        ...
        self.child_relation.bind(field_name='', parent=self)
```

I am aware that there are some issues related to `SerializerMethodResourceRelatedField` already reported in #639, but since this bug is completely independent thing, I report it as separate issue.

**Comment by sliverc** [comment]
Thanks for the hinter. I agree this is not directly related to #639 and would be an easier fix.

PR is also welcome for whoever want to pick this up.
