### ISSUE TITLE
Add possibility to filter included resources

### ISSUE THREAD

**Issue by gelmiro** [django-json-api/django-rest-framework-json-api#794]
Hi,
Right now we don't have possibility to filter included resources I guess. Example:
We have situation:
```
class Category(models.Model):
    name = models.CharField()

class Movie(models.Model):
    name = models.CharField()
    rating = models.IntegerField()
    category = models.FereignKey(Category, related_name='movies')

class CategorySerializer(ModelSerializer):
    included_serializers = {
         'movies': 'MovieSerializer'
}
    class Meta:
        model = Category
        fields = ('name', 'movies')

class MovieSerializer(ModelSerializer):
    class Meta:
        model = Movie
        fields = ('name', 'rating')
```
In this situation in `relationships` field for `/category/` I will get `movies` with a list of ids. I want to filter `movies` with specific parameter i.e. `/category/?filter[movies.rating.gte]=5&include=movies`

Can I achieve this somehow?

**Comment by sliverc** [comment]
A filter can only be set to filter the requested resource so in your example use case only categories itself. What you are trying to do is not very RESTful and you might rather consider creating an API endpoint `movies` where you have a filter category and your greater than filter.

If you still want to follow your api design what you could do is to use [SerializerMethodResourceRelatedField](https://django-rest-framework-json-api.readthedocs.io/en/latest/usage.html#serializermethodresourcerelatedfield) and in the getter method read the query parameter you use for filtering.

Hope this helps?

**Comment by sliverc** [comment]
As there hasn't been any feedback I assume this issue has been resolved. If not feel free to comment.
