### ISSUE TITLE
JSON_API_FORMAT_FIELD_NAMES = "camelize" - NOT working with nested objects

### ISSUE THREAD

**Issue by mroobert** [django-json-api/django-rest-framework-json-api#796]
I updated Django project with this config: 
**Django version 2.2
django-rest-framework version 3.9.4
django-rest-framework-json-api version 2.8.0**

In the base.py file, JSON_API_FORMAT_FIELD_NAMES = "camelize" and the result is: 

Formatted JSON Data
```
{
   "data":{
      "type":"...",
      "id":"...",
      "attributes":{
         "title":"...",
         "slug":"...",
         "components":[
            {
               "type":"...",
               "id":"...",
               "component_style":"..."
            }
         ]
      }
   }
}
```

The **component_style** is not camelized...
With django-rest-framework-json-api version 2.4.0** this worked.

**Comment by sliverc** [comment]
See https://github.com/django-json-api/django-rest-framework-json-api/issues/754#issuecomment-566156109

Does this clarify your issue?

**Comment by sliverc** [comment]
As there hasn't been any feedback on this issue so I assume this has been clarified. If not feel free to comment.
