### ISSUE TITLE
How to get full request body data

### ISSUE THREAD

**Issue by NFS002** [django-json-api/django-rest-framework-json-api#800]
Hello,

If I have used the package correctly, when you post data to an api endpoint with content type set to appliction/vnd.api+json, and then you access the request.data attribute, it only shows the attributes dict of the posted data, how do you access the full request body ? Thanks

**Comment by sliverc** [comment]
This is currently not possible once it has been passed through the DJA parser as the idea of the parser is to simplify the input data so it can be easily passed through a serializer. You could write your own parser of course if you want to parse the json yourself.

My question would be though what your use case for this is though?

**Comment by NFS002** [comment]
Cheers, solved it now anyway, my use case is related to the PolymorphicSerializer, and that pretty much how 'I' solved it...
