### ISSUE TITLE
Support `field_name_mapping` in `RelatedMixin`

### ISSUE THREAD

**Issue by steder** [django-json-api/django-rest-framework-json-api#805]
I have a case where my client is attempting to access both the `relationships` and `related` views with a different `related_field` name.

I was able to work around this for the relationships view with the `field_name_mapping` but not for my "related" view (based on ModelViewSet).

I poked at things and made a small change to `RelatedMixin` that works around the issue for me.  Would it make sense to submit this or is it intended that the `RelatedMixin` behavior does not support `field_name_mapping`?

**Comment by sliverc** [comment]
As you state in PR #806 this might not be a DJA issue.

Any progress on this whether it is a DJA issue or somewhere in your code base?

**Comment by sliverc** [comment]
I assume you have been able to figure out the issue you had, therefore closing. In case this is still an issue feel free to comment.
