### ISSUE TITLE
Tag new version to release in pip

### ISSUE THREAD

**Issue by kiawin** [django-json-api/django-rest-framework-json-api#814]
Hi @sliverc, great work on DJA. May I know whether we can have a new release? I'm keen to use #781.

Thanks 😄

**Comment by sliverc** [comment]
We are planning a release. There is a blocking issue though explained at https://github.com/django-json-api/django-rest-framework-json-api/pull/787#issuecomment-675384206 

Once we find an solution for this issue we will do another release.
