### ISSUE TITLE
JSON output incorrectly wrapping id in quotes

### ISSUE THREAD

**Issue by GrandSlam90** [django-json-api/django-rest-framework-json-api#818]
I've dropped DRF-JSON-API into my DRF application following all the defaults but I'm getting strange output where the model's `id` is being wrapped in quotations. This is causing issues with my Ember.js frontend as it's unable to properly parse the output.
I've checked the database and the id field is defined as an integer. Every other field seems to be serialized correctly.
What setting am I missing?!

Sample output:
```
{
  "links": {
    "first": "http://localhost:8000/dat/?page%5Bnumber%5D=1",
    "last": "http://localhost:8000/dat/?page%5Bnumber%5D=1",
    "next": null,
    "prev": null
  },
  "data": [
    {
      "type": "Dat",
      "id": "1",
      "attributes": {
        "name": "Nintendo - Nintendo Switch",
        "description": "Nintendo - Nintendo Switch",
        "matched_games": 0,
        "missing_games": 618,
        "last_verified": "2020-08-05T16:43:27.041339Z"
      }
    }
  ],
  "meta": {
    "pagination": {
      "page": 1,
      "pages": 1,
      "count": 1
    }
  }
}

Response code: 200 (OK); Time: 55ms; Content length: 410 bytes

```

**Comment by n2ygk** [comment]
"Every resource object MUST contain an id member and a type member. The values of the id and type members MUST be strings."

Reference: https://jsonapi.org/format/#document-resource-object-identification

**Comment by sliverc** [comment]
As additional hinter there is for instance [following project](https://github.com/adfinis-sygroup/timed-frontend) which uses DJA in the newest version with ember and it works without any problems.

Maybe you can find some hinters there to solve your issue.

**Comment by GrandSlam90** [comment]
Thanks for the quick response and the links for clarity.
I've now refactored my backend and everything now works correctly.
It might be worth updating the README.rst as the opening example shows the `identity` JSON-API response with unquoted IDs. This is partly what sent me down this rabbit-hole.
Keep up the great work 👍👍

**Comment by n2ygk** [comment]
A documentation improvement PR would be gladly accepted!

**Comment by sliverc** [comment]
@GrandSlam90 Very good point. I have created #824 fixing this issue.
