### ISSUE TITLE
Filters negation/exclusion

### ISSUE THREAD

**Issue by sdhawley** [django-json-api/django-rest-framework-json-api#820]
The FilterSet class supports an exclude option but I don't see how to specify that in filterset_fields. Is it possible? Could we get a 'not equal' option?

```python
filterset_fields = {
        'id': ('exact', 'ne'),
}
```

**Comment by n2ygk** [comment]
You'll want to check the upstream https://django-filter.readthedocs.io/en/master/ref/filterset.html#exclude

Simple things you can implemented by setting `filterset_fields` while others require you to subclass `FilterSet`. I think this is one of those.

**Comment by ro70** [comment]
Not sure but is it not rather [this](https://django-filter.readthedocs.io/en/stable/ref/filters.html#exclude) `exclude`?

Then set `filterset_class = XFilter` in your ViewSet and
```
class XFilter(filters.FilterSet):
    id = filters.NumberFilter(
        field_name='id', lookup_expr='exact', exclude=True,)

    class Meta:
        model = X
        fields = ['id', ]
```

**Comment by sdhawley** [comment]
Sorry for the delayed response. @ro70 is correct, I'm looking for the FilterSet exclude functionality so I can search for field != value.

Query string could be something like https://host.com/api/endpoint?filter[field.ne]=value or https://host.com/api/endpoint?filter[field]!=value, though I think the former is more in line with the json api spec and convention.

**Comment by n2ygk** [comment]
I like the former. Implementing `!=` would be difficult

**Comment by sliverc** [comment]
As @ro70 suggested that's how I see this is currently done.

DJA only implements a very thin filter layer which basically wraps query parameters into `field[]`. The rest is all done in `django-filter` itself. Therefore I don't see that this question is DJA specific. If you want to do exclude it differently you would need to discuss this upstream in the [django-filter](https://github.com/carltongibson/django-filter) project.

Closing this issue therefore.
