### ISSUE TITLE
dj_rest_auth with JWT auth break on renderer (login or register)

### ISSUE THREAD

**Issue by educolo** [django-json-api/django-rest-framework-json-api#836]
When I try to register o login I get this error
`AttributeError: 'dict' object has no attribute 'pk'`

The issue raise on renderers.py on the line
`('id', encoding.force_str(resource_instance.pk) if resource_instance else None),`

It works well with Tokens, but breaks with JWT.
dj-rest-auth change the data to serialize when JWT is active like this:
```
           data = {
                'user': user,
                'access_token': self.access_token,
                'refresh_token': self.refresh_token
            }
            return JWTSerializer(data, context=self.get_serializer_context()).data
```

To fix (at least for the moment) this issue, I made that tokens get inside user and with all at the same level It's working, but I think this is not the best solution.
Thanks

**Comment by sliverc** [comment]
json:api spec always needs an id and type. In a JWT authentication it is not quite clear what it would be as there is no real model.

I guess the easiest would be that for authentication you use simple json and for the rest of the API json:api spec. This is also closer to authentication standards like [OpenID Connect](https://openid.net/connect/).

To do this you can define an additional plain JSON parser and renderer as explained [here](https://www.django-rest-framework.org/api-guide/renderers/#setting-the-renderers) and [here](https://www.django-rest-framework.org/api-guide/parsers/#setting-the-parsers).

Does this help?

**Comment by educolo** [comment]
Thanks a lot. I'll check this info, but I think it's more than enough.
