### ISSUE TITLE
how to implement Sparse Fieldsets?

### ISSUE THREAD

**Issue by hnakamur** [django-json-api/django-rest-framework-json-api#84]
I would like the Sparse Fieldsets feature:
http://jsonapi.org/format/#fetching-sparse-fieldsets

I tried to implement it and thought creating a custom serializer and override [rest_framework.serializers.Serializer.fields](https://github.com/tomchristie/django-rest-framework/blob/8cae462b3a3d724cf83fd33572c0ea23f91f2278/rest_framework/serializers.py#L318-L330) property.

However, we need the `resource_name` to get the `fields[TYPE]` query parameter value (TYPE=resource_name).
I find [rest_framework_json_api.utils.get_resource_name](https://github.com/django-json-api/django-rest-framework-json-api/blob/f55076ea92a08a845c09fbd63f3976d264fbb984/rest_framework_json_api/utils.py#L33-L77), however its argument `rendrerer_context` is created after the serializer returns data. For example, in ListModelMixin, `rendered_context` is created in `Response(serializer.data)` at https://github.com/tomchristie/django-rest-framework/blob/8cae462b3a3d724cf83fd33572c0ea23f91f2278/rest_framework/mixins.py#L47-L48)

So how should we implement the Sparse Fieldsets feature?

**Comment by jerel** [comment]
[utils.get_resource_name](https://github.com/django-json-api/django-rest-framework-json-api/blob/f55076ea92a08a845c09fbd63f3976d264fbb984/rest_framework_json_api/utils.py#L33-L77) doesn't appear to need a serializer passed to it. It just fetches `view` off of whatever it is given. So we could call `utils.get_resource_name` anywhere that we have access to the view to get the same `resource_name`. Perhaps [a filter backend](http://www.django-rest-framework.org/api-guide/filtering/#custom-generic-filtering) would make sense for this?

A filter has access to the `view` and from there it may be possible to modify the serializer `fields` tuple for that request. It gets trickier with included or related data though, maybe someone else has additional ideas

**Comment by jerel** [comment]
@hnakamur I just merged a feature from @jsenecal that adds sparse fieldset support e56ef782a56e5e7bcaa3dd1d04ad2c9c33d6493d. If you want to try it out use this serializer `from rest_framework_json_api.serializers import HyperlinkedModelSerializer` or use the `SparseFieldsetsMixin` in an existing serializer.

Let us know here or open a new issue for any problems.

**Comment by hnakamur** [comment]
@jerel @jsenecal Great! Thanks!

**Comment by jsenecal** [comment]
NP @hnakamur ! I needed this myself anyways :P
