### ISSUE TITLE
Add support for DRF 3.12+

### ISSUE THREAD

**Issue by petrosschilling** [django-json-api/django-rest-framework-json-api#845]
I'm having dependency issues because DRF version 3.12 is not supported and I need 3.12 for other dependencies.

here is the issue raised by pip install:
```djangorestframework-jsonapi 3.2.0 requires djangorestframework<3.12,>=3.10, but you'll have djangorestframework 3.12.0 which is incompatible.```

I'm happy to help.

**Comment by petrosschilling** [comment]
I upgraded pip and it worked with no problems.

**Comment by petrosschilling** [comment]
I upgraded from pip-20.2.3 to pip-20.2.4 and it worked.

**Comment by petrosschilling** [comment]
My bad... Issue is still there.

**Comment by n2ygk** [comment]
@sliverc can we do a dependency update 3.x release without yet releasing the other 4.0.0 features....

**Comment by n2ygk** [comment]
@sliverc It occurs to me that we've merged too much into the master branch to do another 3.x release without starting a whole new branch in the project and this is time-consuming.

@petrosschilling meanwhile you can use the master branch which already incorporates the DRF 3.12 requirement.
You can do this by putting `git+https://github.com/django-json-api/django-rest-framework-json-api.git` in your requirements.txt or as argument to the `pip install` command. If you want to pin a version, use a commit id as in:
```
git+https://github.com/django-json-api/django-rest-framework-json-api.git@7efea4
```
