### ISSUE TITLE
migrate to travis-ci.com

### ISSUE THREAD

**Issue by n2ygk** [django-json-api/django-rest-framework-json-api#848]
See https://docs.travis-ci.com/user/migrate/open-source-repository-migration

Apparently travis-ci.org is being shrunk and eventually shut down.

Alternatively switch to github actions.

**Comment by n2ygk** [comment]
@sliverc do I just need to change the webhook from travis-ci.org to travis-ci.com? Not quite sure.

**Comment by n2ygk** [comment]
@django-json-api/core I made a travis-ci.com request for the DJA org but I'm not sure who the request got routed to. I did not receive it.

**Comment by n2ygk** [comment]
I see it probably went to @gaker @sliverc and @jerel for the DJA org.... Will wait on you.

**Comment by sliverc** [comment]
I will take over this hopefully soon. I have done this before in the past.

**Comment by n2ygk** [comment]
> I will take over this hopefully soon. I have done this before in the past.

Thanks. Please let me know what you've done as I need to do the same on another project. It's a bit confusing!

**Comment by sliverc** [comment]
It is done now.

The steps I took roughly:
* Installed the GitHub Travis CI app on the org
* Configure App and (all repositories does not work, need to chose specific repositories)
* Logged into Travis CI com and enrolled into Beta to be able to migrate
* chosen django-json-api org and started migration
* in GitHhub: adjusted settings in protected branches to enforce "Travis CI - Pull Request" check and disabled old travis-ci.org status check (it actually took some minutes for the Travis CI - Pull Request to appear in the list)
* in GitHub: removed travis-ci.org hook from DJA

It seems to be running now and much faster then before. Clean up of badge as of PR #850 currently outstanding.
