### ISSUE TITLE
Feedback requested: what version of Django REST Framework do you use?

### ISSUE THREAD

**Issue by jerel** [django-json-api/django-rest-framework-json-api#85]
How many of you are using DRF 3.0.x or 2.4.x? Since the JSON API spec just recently stabilized on 1.0 I'm guessing that most JSON API compliant APIs will be built using one of the latest versions of DRF.

If that is the case I would like to just support DRF 3.1 and newer. Django (1.6+) and Python (2.7+) support should remain unchanged.

**Comment by jsenecal** [comment]
DRF 3.2.2
Django 1.8.3
Python 3.4.3

**Comment by scottfisk** [comment]
DRF 3.2.2
Django 1.7.10 (moving to 1.8 very soon)
Python 2.7.10

**Comment by mkohram** [comment]
DRF 3.1.3
Django 1.8.3
Python 3.4.3

**Comment by holandes22** [comment]
DRF 3.2.3
Django 1.8.4
Python 2.7.10

**Comment by martinmaillard** [comment]
DRF 3.2.3
Django 1.8.4
Python 2.7.10

**Comment by orf** [comment]
DRF 3.2.3
Django 1.8.4
Python 2.7.x and 3.4.x

**Comment by jerel** [comment]
So far it's looking like everyone is using DRF 3.1+ so we'll not worry about supporting <= DRF 3.0. Thanks for the feedback.
