### ISSUE TITLE
[Feature proposal] Allow choosing included resources from browsable API

### ISSUE THREAD

**Issue by David-Guillot** [django-json-api/django-rest-framework-json-api#851]
Hi there,

Title says it all: our frontend team asked me if it would be possible, in the browsable API view, to choose related resource to include, among the list of possible includes defined by serializers. I think it's a good idea, and actually the code to achieve that is generic enough to be proposed as an addition to this awesome lib.

What do you think?

**Comment by sliverc** [comment]
I like this idea! A PR would be very welcome if this can be implemented in a DJA specific Browsable API view which doesn't need to overwrite too much functionality of DRF.

**Comment by David-Guillot** [comment]
Great thank you! I just created #854 about this, but for now it lacks tests (that are fairly tricky to write because of the internals of DRF's `BrowsableAPIRenderer`), documentation and so on. By the way, the PR template is great :+1:
