### ISSUE TITLE
Constrain RelationshipView to selected relationships

### ISSUE THREAD

**Issue by uliSchuster** [django-json-api/django-rest-framework-json-api#853]
I have a model with, say, two relationships; e.g., an `Order`with `line_items` and `modifications`.  I want to expose an `order` resource at `/api/v1/orders/<pk>/`, provide related resources at `/api/v1/orders/<pk>/line_items/` and `/api/v1/orders/<pk>/modifications/`. In addition, I want to provide a _relationships_ view for the line items only.

When I use the `RelationshipView` as described in the documentation, it requires a URL-mapping like so:
```python
    path(
        "orders/<pk>/relationships/<related_field>/",
        view=OrderRelationshipView.as_view(),
        name="order-relationships",
    )
```
with corresponding `OrderRelationshipView`:
```python
class OrderRelationshipView(RelationshipView):
    queryset = Order.objects
    self_link_view_name = "order-relationships"
```

The problem I'm having is that this will create a valid route `/api/v1/orders/<pk>/relationships/modifications/`, which I do not want to provide, because the relationship to the modification resource cannot be altered.

Is there a way to extend the `OrderRelationshipView` such that it only handles the `line_items` relationship? or alternatively, provides safe operations (GET, HEAD, OPTIONS) only on the `modifications` relationship?

**Comment by sliverc** [comment]
Could you not write a permission_class which return false when the `views.kwargs['related_field']` is `modifications` and `request.method` is not GET, HEAD or OPTIONS?

See https://www.django-rest-framework.org/api-guide/permissions/

**Comment by uliSchuster** [comment]
Thanks for the hint, I will give it a try!

**Comment by sliverc** [comment]
I assume with the above hint and the discussion in the partly related issue #864 this has been resolved and can be closed.

If there is still a question concerning this issue, please comment.
