### ISSUE TITLE
improve CONTRIBUTING

### ISSUE THREAD

**Issue by n2ygk** [django-json-api/django-rest-framework-json-api#861]
Improve the [CONTRIBUTING.md](https://github.com/django-json-api/django-rest-framework-json-api/blob/master/docs/CONTRIBUTING.md) to document local development and testing steps prior to pushing/submitting a PR.

**Comment by sliverc** [comment]
It is actually there on the [README.rst](https://github.com/django-json-api/django-rest-framework-json-api/blob/69a720a87f3bdbabb3ce0591a45d0c9b44ab9125/README.rst#running-tests-and-linting).

A normal DJA user is not interested in this though so I think this part should be moved to CONTRIBUTING.md and potentially adjusted.
