### ISSUE TITLE
QueryFilters - Nested Relation Filters 

### ISSUE THREAD

**Issue by mtnntn** [django-json-api/django-rest-framework-json-api#865]
Hi everyone,

according to the [documentation](https://django-rest-framework-json-api.readthedocs.io/en/stable/usage.html#djangofilterbackend) seems that should be possible to filter resources based on their relationships using a query string like `?filter[inventory.item.partNum]=123456`.

I have the following models:
```python
class Genre(models.Model):
    name = models.CharField(unique=True, max_length=255)

class Film(models.Model):
    title = models.CharField(unique=True, max_length=255)
    genres = models.ManyToManyField('films.Genre')
```
I have the following serializers:
```python
class GenreSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = Genre
        fields = ['name']

class FilmSerializer(serializers.HyperlinkedModelSerializer):
    included_serializers = { 'genres': GenreSerializer }
    genres = ResourceRelatedField(queryset=Genre.objects, many=True)
    class Meta:
        model = Film
        fields = ["title", "genres"]
```
And I have this view:
```python
class FilmsViewSet(views.ReadOnlyModelViewSet):
    queryset = Film.objects.prefetch_related('genres')
    serializer_class = FilmSerializer
    filterset_fields = {
        'title': ('icontains', 'iexact', 'contains',),
        'genres': ("exact",),
    }
```

Unfortunately I had some issues trying to:
- filter out films based on their `genres.name` (or properties in general, i.e: `filter[genres.name.icontains]=abc` )
- filter out films based on their `genres.id` (specifying other lookup functions, i.e: `filter[genres.id.in]=1,2`)
  I know that for this specific case is possible to use this form `fitler[genres]=1&filter[genres]=2` but it would be nice to customize this behavior to avoid long urls (I think it is slightly counterintuitive too since the conditions should represent AND clauses not OR, but this is only a personal idea).

It would be nice to add more information on the docs.
Thanks!

**Comment by sliverc** [comment]
For each filter you want to use you need to define a filterset field. There are some more complex examples [here](https://github.com/django-json-api/django-rest-framework-json-api/blob/master/example/views.py#L155) which might help you.

With the docs is a bit of a challenge. Because this is actually not a DJA feature but of [django-filter](https://django-filter.readthedocs.io/en/stable/) where how to use `filterset_fields` with relationships should be documented.

Does this hinter help you though?

**Comment by mtnntn** [comment]
Thanks for all the references @sliverc.

I ended up implementing a custom FilterSet Class since I needed custom filtering options.

You're right about the documentation, it's something that should be looked up in the django-filter doc.

Anyway, If you're ok with it I'll submit a pull request to fix 2 links in the docs:
- "ordering filters" in the [Ordering Filters](https://django-rest-framework-json-api.readthedocs.io/en/stable/usage.html#orderingfilter) section. I think [this](https://www.django-rest-framework.org/api-guide/filtering/#orderingfilter) one is the correct one.
- "SearchFilters" in the [Search Filter](https://django-rest-framework-json-api.readthedocs.io/en/stable/usage.html#searchfilter) section. This [link](https://www.django-rest-framework.org/api-guide/filtering/#searchfilter) should be the correct one.

If there is no need to replace them feel free to resolve this issue :)

Thanks for your help and time.

**Comment by sliverc** [comment]
It would be great if you could create a PR to fix those dead links. Thanks.
