### ISSUE TITLE
Django 3.2 compatibility

### ISSUE THREAD

**Issue by Tenzer** [django-json-api/django-rest-framework-json-api#907]
Django 3.2 is now out, but we are currently blocked on upgrading to it due to djangorestframework-jsonapi specifically disallows that and newer versions as dependencies:
https://github.com/django-json-api/django-rest-framework-json-api/blob/0892e3a8a4dbad9630d70e2b78e18b242a8b057d/setup.py#L101

I couldn't find any other issues related to this so thought I would create one.

Are there any specific concerns with loosening the version constraint so users of this library also can upgrade to Django 3.2?

**Comment by sliverc** [comment]
We want to specify each supported release of Django or other dependencies to make sure it actually works by running the test suite through it. See for instance #822 where Django 3.1 had been added and quite a bit of changes were needed.

Currently DRF has released a version which officially supports Django 3.2. This said I would be fine adding Django 3.2 support in DJA before DRF has a new release as long as the test suite runs through.

PR is welcome.

**Comment by Tenzer** [comment]
Thanks! I have made a PR to bump the compatibility in #908.
