### ISSUE TITLE
Release needed for Django 3.2 Update

### ISSUE THREAD

**Issue by TayHobbs** [django-json-api/django-rest-framework-json-api#911]
Hello,

I see that there was a change to allow Django 3.2, but no new release has happened. This is preventing us from upgrading, could we get a new version released?

Thank you!

**Comment by sliverc** [comment]
There are some regressions introduced in version 4.1.0 which I would like to address first before a new release. See PR in progress #904 #900 #897 which need to be cleaned up first though before being merged. I hope to get some time to get around those soon. Once this is ready there will be a new release.
