### ISSUE TITLE
ResourceRelatedField.source doesn't allow nested paths

### ISSUE THREAD

**Issue by SafaAlfulaij** [django-json-api/django-rest-framework-json-api#912]
Compared to how DRF allow nested paths in source:
https://github.com/encode/django-rest-framework/blob/master/rest_framework/fields.py#L401

DJA doesn't allow it:
https://github.com/django-json-api/django-rest-framework-json-api/blob/51daed1a738aadb1536a6a3cbe787cbd88daaf05/rest_framework_json_api/utils.py#L204

Examples here: https://www.django-rest-framework.org/api-guide/fields/#source
`EmailField(source='user.email')`

**Comment by sliverc** [comment]
As far as I see does this only affects `ResourceRelatedField` for all other serializer fields dotted source should work.

I wonder why `relation.get_attribute(model)` is not used there which should solve this issue.

**Comment by bashlyss** [comment]
I'm not sure if this issue still applies in full in the current version. In my own testing of both fk, 1:1 and m2m relationships, only nested m2m fields had any issue. #1065 opened as a fix to this case
