### ISSUE TITLE
Use JSON:API instead of JSON API

### ISSUE THREAD

**Issue by sliverc** [django-json-api/django-rest-framework-json-api#940]
Recently there have been some confusion that DJA got confused with plain DRF like #930 and #894. I guess the naming of the JSON:API specification is not ideal :smile: 

It is though that in our readme and many other spots we use the term "JSON API" in the [json api spec](https://jsonapi.org/format/) "JSON:API" is used though.

So I suggest we find all "JSON API" references and replace it with "JSON:API". Hope this will reduce the confusion.

**Comment by MsMansiDhruv** [comment]
Sure. Sounds like a good way to get into contributing. I can take it up.  

> Recently there have been some confusion that DJA got confused with plain DRF like #930 and #894. I guess the naming of the JSON:API specification is not ideal smile
> 
> It is though that in our readme and many other spots we use the term "JSON API" in the [json api spec](https://jsonapi.org/format/) "JSON:API" is used though.
> 
> So I suggest we find all "JSON API" references and replace it with "JSON:API". Hope this will reduce the confusion.
