### ISSUE TITLE
Inflect component attributes when using the OpenAPI SchemaGenerator

### ISSUE THREAD

**Issue by sliverc** [django-json-api/django-rest-framework-json-api#967]
### Discussed in https://github.com/django-json-api/django-rest-framework-json-api/discussions/966

<div type='discussions-op-text'>

<sup>Originally posted by **mattis-rosenkranz** July 29, 2021</sup>
The generated OpenaAPI-Scheme component attributes are not inflected using the settings described in the docs.
This is not a problem as the parser just leaves the attribute names as they are, but it would be nice to conform the OpenAPI-scheme to the chosen field format.</div>

Most likely this will be fixed in [map_serialzer](https://github.com/django-json-api/django-rest-framework-json-api/blob/master/rest_framework_json_api/schemas/openapi.py#L641) function.

**Comment by SwarajBaral** [comment]
Hey @sliverc, I would like to work on this. Can you guide me a bit so that I can get started ?
