### ISSUE TITLE
Broken unpaginated list view

### ISSUE THREAD

**Issue by martinmaillard** [django-json-api/django-rest-framework-json-api#98]
When pagination is not enabled, the `if` in [`JSONRenderer.render`, L61](https://github.com/django-json-api/django-rest-framework-json-api/blob/develop/rest_framework_json_api/renderers.py#L61) does not pass, and `utils.utils.build_json_resource_obj` breaks when called in [the `else` block](https://github.com/django-json-api/django-rest-framework-json-api/blob/develop/rest_framework_json_api/renderers.py#L85) with the following error: 

    AttributeError: 'QuerySet' object has no attribute 'pk'

**Comment by abdulhaq-e** [comment]
I have this fixed in an updated branch. I need to rebase and write a test as well and submit a PR.

**Comment by jsenecal** [comment]
@abdulhaq-e any luck with that PR ?

**Comment by abdulhaq-e** [comment]
Hi, I submitted the PR, see https://github.com/django-json-api/django-rest-framework-json-api/pull/114

**Comment by jerel** [comment]
This issue should be fixed by 61242bb2df9f4ef8b9ccb7604990f687d49d64c9
